jitsi/lib-jitsi-meet

JitsiConference.js
When moderator mute client he cannot unmute because he is muted on server.
This ensures that client unmutes himself on the server.
=> Unmute client on the server if he was muted by focus

modules/RTC/JitsiTrack.js
Previously, when setting `src` to `null` on jQuery elements, the `src` attribute was just removed.  
Now that it's set on plain DOM elements the `src` is actually set to string "null" which performs a network request for resource "null".
Setting the video `src` to empty string on plain DOM elements stops the old stream and does not initiate a network request.
=> Set video src to empty string instead of null on #detach()

modules/RTC/RTCUtils.js, modules/statistics/statistics.js
* add Firefox to the list of browsers which support changing devices
* adjust `getUserMedia` constraints to force Firefox to select proper device
=> Allow to select devices on Firefox

JitsiConference.js, doc/API.md, modules/RTC/JitsiLocalTrack.js, modules/RTC/RTC.js
Currently jitsi doesn't support multiple video streams, so fail if that happens.
=> Fail if user is trying to add second video track to the conference

modules/RTC/RTC.js
Fixes undefined error in getResourceBySSRC when local video or audio track is stopped, reported to happen sometimes with desktop sharing.
=> Fixes undefined error in getResourceBySSRC

.jshintignore, JitsiConference.js, JitsiConferenceEvents.js, doc/API.md, modules/settings/Settings.js, modules/xmpp/moderator.js
* store session settings userId and callStatsUserName globally (was per-conference)
* move sessionId reading/storing into Settings.js
* propagate conference event AUTH_STATUS_CHANGE
fixes https://github.com/jitsi/lib-jitsi-meet/issues/18
=> Store session settings userId and callStatsUserName globally (was per-conference)

JitsiConference.js, JitsiTrackErrors.js, doc/API.md, modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js
Returns Promise from mute/unmute and ignores requests while mute/unmuting is in progress. Moves mute/unmute methods to JitsiLocalTrack as said in API docs.
=> Syncs mute/unmute calls.

JitsiConference.js
For example:
- The mention of the method sendPresenceComment which does not exist.
- Copied comment which describes a different method and signature.
=> Fixes doc(umentation) comments

modules/xmpp/JingleSessionPC.js
There were multiple cases in which we did:
if (SDPUtil.find_line(x,y,z)) {
... SDPUtil.find_line(x,y,z)...
}
Which was wasteful (and hard to read).
=> Removes wasteful duplicate calls to SDPUtil.find_line().

JitsiConference.js, modules/version/ComponentsVersions.js, modules/xmpp/ChatRoom.js
For now the versions are only printed as a logger.info message, but they will end up being logged to CallStats.io eventually.
=> Captures the versions of conferencing system components.

modules/xmpp/JingleSessionPC.js
(Well, it's a matter of subjective opinion whether it's better.)
1. The check whether to discard ICE candidates was suboptimal and harder to read.
2. The check for event was partial and could still potentially allow the throw of an exception.
3. There's a branch of the code which could potentially lead to seemingly undesired behavior. Luckily, we don't execute that branch of the code. Anyway, I believe it's better to have a FIXME there (because I don't want to spend time fixing the problem now).
=> Better onicecandidate

modules/xmpp/JingleSessionPC.js
The goal of this PR is to make source-remove notifications simpler. That is they will no longer contain SSRC parameters, but only the SSRC value after https://github.com/jitsi/jicofo/pull/73. The client should remove all lines related to that SSRC instead of trying to match the lines for given parameters.
This will fix the issue where we're leaking FF and Chrome recvonly streams which do not come with mslabel. Then later Chrome adds mslabel and msid with 'default' value. Jicofo doesn't know about that changes, so these are not included in source-remove notification.
It will also simplify implementation of lipsync stream merge feature in jicofo, as it will not have to track the peers that received merged or separate version of A/V stream.
=> Ssrc remove

package.json
Enables the library to be used via require. Example usage is a React
Native (mobile) app which bundles its dependencies (in its release
build).
=> Define the main/primary entry point of the library

JitsiConference.js, JitsiConnection.js, JitsiMeetJS.js
While we have JitsiMeetJS defined as a global variable in Jitsi Meet, it
doesn't sound like an absolutely necessary and beautiful requirement
inside the library itself.
=> Don't rely on JitsiMeetJS being global

JitsiConference.js, modules/statistics/CallStats.js
Changes the implementation to use  the roomName for generating the confID. This change will solve the issue with creating entries for 2 different calls in callstats for the same urls written with lower and upper case. For the roomName we are not accepting capital letters.
=> Fixes issue with callstats confID

JitsiMeetJS.js, JitsiTrackEvents.js, doc/API.md, doc/example/example.js, doc/example/index.html, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js, service/RTC/RTCEvents.js
1. Added new methods to JitsiMeetJS (and RTC and RTCUtils respectively)
- isAudioOutputDeviceChangeAvailable
- getAudioOutputDevice
- setAudioOutputDevice
2. Added new events:
- JitsiTrackEvents.TRACK_AUDIO_OUTPUT_CHANGED
- RTCEvents.AUDIO_OUTPUT_DEVICE_CHANGED
3. Update sample from docs to give ability to select output devices
=> Added ability to change output audio device for browsers that support it

JitsiMediaDevices.js, JitsiMediaDevicesEvents.js, JitsiMeetJS.js, doc/API.md, doc/example/example.js, modules/RTC/RTCUtils.js, service/RTC/RTCEvents.js
1. Added ability to discover device list changes by polling ```enumerateDevices()``` each 3 seconds.
2. Extracted all methods related to interaction with media devices from JitsiMeetJS into separate object JitsiMeetJS.mediaDevices:
- enumerateDevices (deprecation note added to ```JitsiMeetJS.enumerateDevices```)
- isDeviceListAvailable (deprecation note added to ```JitsiMeetJS.isDeviceListAvailable```)
- isDeviceChangeAvailable (deprecation note added to ```JitsiMeetJS.isDeviceChangeAvailable```)
- getAudioOutputDevice
- setAudioOutputDevice
3. Added ability to subscribe/unsubscribe to media devices events via ```JitsiMeetJS.mediaDevices.addEventListener```/```JitsiMeetJS.mediaDevices.removeEventListener```
4. New event group ```JitsiMeetJS.events.mediaDevices```
5. Added new events:
- …
=> Added ability to notify about available media device list changes

JitsiMeetJS.js
JitsiMeetJS#init accepts an options object in which the property
disableAudioLevels may optionally be defined and is meant to disable RTC
statistics related to audio levels. Unfortunately, the option was used
in a boolean expression which ignored the value of the option and thus
effectively rendered it unused.
=> Fix JitsiMeetJS option disableAudioLevels

JitsiMediaDevices.js, doc/API.md, modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js
1. New methods added
- JitsiMediaDevices.prototype.isDevicePermissionGranted(type)
- JitsiLocalTrack.prototype.isEnded()
- JitsiLocalTrack.prototype.getDeviceId()
2. Fixed potential memory leaks with not clearing event handlers
3. Updated API document
=> Switch local audio and video tracks when list of available devices changes

doc/API.md, doc/example/example.js, modules/xmpp/moderator.js
Jicofo is smart and can find any bridge with service discovery and/or
pubsub.
=> Nukes the pre-configured bridge from the example config file.

JitsiConferenceEvents.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTCUtils.js, modules/xmpp/ChatRoom.js, modules/xmpp/JingleSessionPC.js
RTCUtils' handleLocalStream deals with the results of obtainAudioAndVideoPermissions. The latter checks the type of the browser and branches in different execution paths depending on that and, eventually, defines .audioAndVideo, .audio, .video, .desktopStream and/or .desktop on handleLocalStream's streams argument.
As part of the development effort to support lib-jitsi-meet on React Native, I've defined a RTCBrowserType.isReactNative() and I've used it in obtainAudioAndVideoPermissions. Unfortunately, I have to use it in handleLocalStream and repeat the logic/checks.
That's practically unnecessary because handleLocalStream may just examine the streams argument's properties and figure out what's available without repeating the browser checks done by obtainAudioAndVideoPermissions (which …
=> Remove browser type check

modules/statistics/RTPStatsCollector.js, modules/statistics/statistics.js
There were at least 3 kinds of repetitions that caused inefficiency and
burdened debugging:
1. Complex if conditions in which the value of one expression was
practically dependent upon the other so it was enough to check 1 of the
2 exressions.
2. getStatValue was called multiple times within the same function to
retrieve the value with 1 and the same key. That was wasteful, harder to
read and hampered debugging (on React Native).
3. getStatValue which is called multiple times within 1 second was
checking the RTCBrowserType of the executing browser. Since the latter
is very unlikely to change during a session i.e. at runtime, I
refactored the source code to perform as many of the checks as possible
just once.
Additionally, getStatValue used to throw an error if the executing
browser is …
=> Remove repetitions

modules/xmpp/JingleSessionPC.js
The previous method was clobbering the JingleSession prototype,
preventing the creation of additional subclasses.
=> Correctly subclass JingleSession

JitsiConference.js, modules/RTC/DataChannels.js, modules/RTC/RTC.js, modules/xmpp/JingleSessionPC.js, service/xmpp/XMPPEvents.js
With this PR merged data channels will be correctly re-established with the new bridge after ICE restart. In order to achieve that we close all currently opened data channels and set remote description without "data" section. This will clean up SCTP association with the old bridge and allow to connect to the new one.
=> Reopen data channels on ice restart

modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js
Instead we subscribe once for this event in RTC, and then go through all our local and remote audio tracks.
Also restored "dispose" functionality as it was before changes done in https://github.com/jitsi/lib-jitsi-meet/pull/103
=> Do not subscribe each JitsiTrack to RTCEvents.AUDIO_OUTPUT_DEVICE_CHANGED event

JitsiConference.js, JitsiMeetJS.js, JitsiTrackError.js, JitsiTrackErrors.js, doc/API.md, modules/RTC/JitsiLocalTrack.js, modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js, modules/statistics/statistics.js
This PR is a 'clone' of https://github.com/jitsi/lib-jitsi-meet/pull/119 into the jitsi organization repository where I have (1) push access and (2) automatic PR testing.
@tsareg wrote:
Following changes are introduced:
- JitsiMeetJS.createLocalTracks is now rejected with JitsiTrackError instance, not a string
- Introduced JitsiTrackError class that is inherited from base JavaScript Error class, so ```"name"```, ```"message"``` and ```"stack"``` properties are available. For GUM-related errors, exposes additional ```"gum"``` property, which is an object with following properties:
- error - original GUM error
- constraints - GUM constraints object used for the call
- devices - array of devices requested in GUM call (possible values - "audio", "video", "screen", "desktop")
- Changed the …
=> Tsareg handle create local tracks errors better

modules/RTC/RTCUtils.js
This should make us to select "front" camera for mobile apps by default. To really work with react-native, needs support for "facingMode" constraint in react-native-webrtc, which will be done by @paweldomas and @lyubomir
=> getUserMedia: prefer the "user" camera if we have not specified the exact device id for mobile devices

JitsiConference.js, JitsiMeetJS.js, JitsiTrackError.js, doc/API.md, modules/RTC/RTCUtils.js, modules/statistics/statistics.js
Currently if browser fails to set audiooutput device on tracks, this error was logged as SignalingError to callstats. This is actually not very obvious, so instead log it as gUM error.
=> Report DOMException when audio output device change fails as gUM error to callstats

modules/RTC/JitsiTrack.js, modules/RTC/RTC.js, modules/RTC/RTCUIHelper.js, modules/RTC/RTCUtils.js
Since React Native doesn't have HTML elements, depend on HTML element properties and don't necessarily depend on them being properties on actual HTML elements but rather assume plain JavaScript objects.
(This PR deals with the dependencies on HTML elements only in the context of JitsiTrack#attach and #detach because that's what we need now in React Native. Of course, in the future we'll very likely want to deal with other dependencies on HTML elements as well.)
=> Reduce the dependency on HTML elements

JitsiConference.js, JitsiConnection.js, JitsiMeetJS.js, modules/statistics/statistics.js
You can call static Statistics methods which will internally handle callstats instances to send stats. Drops handlers and JitsiMeetJS references.
=> Refactor callstats removing improve static calls to Statistics.

modules/RTC/RTCUtils.js
For more details see https://bugs.chromium.org/p/chromium/issues/detail?id=614716.
In Chrome 51 this error happens when "enable-experimental-web-platform-feature" flag is enabled, while in Chrome Canary 53 it fails always.
This is extracted code from https://github.com/jitsi/lib-jitsi-meet/pull/136 as it seems that currently we're not able to fully switch to new style constraints for new browsers due to bugs.
=> Don't mix old and new-style for gUM constraints for Chrome, as it fails with TypeError in new Chrome versions

modules/RTC/RTCUtils.js
This is how we're preventing unnecessary JitsiMediaDevicesEvents.DEVICE_LIST_CHANGED on start and gives us possibility to better mimic original 'devicechange' event that is currently not available in browsers.
=> Don't fire RTCEvents.DEVICE_LIST_CHANGED for the first time we get devices from enumerateDevices()

JitsiMediaDevices.js, JitsiMediaDevicesEvents.js, JitsiMeetJS.js, doc/API.md, modules/RTC/RTCBrowserType.js
Sometimes we need to do some browser/environment detection in code that uses lib-jitsi-meet, so we can re-use this info from lib.
This is required for https://github.com/jitsi/jitsi-meet/pull/701
=> Fire an optional JitsiMediaDevices.PERMISSION_PROMPT_IS_SHOWN event when JitsiMeetJS.createLocalTracks()

JitsiConference.js, JitsiMediaDevices.js, modules/statistics/CallStats.js, modules/statistics/statistics.js
Do not send event to callstats when no audiooutput devices are available.
Fix non-ASCII letter in Statistics.sendActiveDeviceListEvent() method
=> Fix logging audio output device to callstats

JitsiConference.js
If the API client happened to try to add one and the same local video
track twice, the library would throw an error. I find that draconian
because:
1. The error message states that a second local video stream cannot be
added but that is incorrect because the API client is not trying to add
a second local video stream but add one and the same local video stream
multiple times.
2. The jsdoc says that a throw will happen if another local video stream
is added but that is misleading because the API client is not trying to
add another local video stream but add the same local video stream.
3. Adding one and the same local video stream multiple times can be
handled gracefully by the lib-jitsi-meet library. Thus, the library
appears more friendly.
Hence, gracefully handle the case of adding the …
=> Be forgiving towards API clients

JitsiMeetJS.js, doc/API.md
Exposes JitsiTrackError through JitsiMeetJS.errorTypes.JitsiTrackError.
This is a part of bigger PR (#149), which can be merged now.
=> Expose JitsiTrackError through JitsiMeetJS.errorTypes.JitsiTrackError

JitsiConference.js
Wrap thrown errors into Promise.reject for consistency in JitsiConference's addTrack() and removeTrack() methods.
Handle case when JitsiLocalTrack#dispose() is called after track was removed from conference.
Set track's conference reference to null when removing track from conference.
=> Fix JitsiLocalTrack dispose() method

modules/xmpp/xmpp.js
When XMPP authenticated user joins the conference his login is used as MUC nickname. Now if his connection gets interrupted and he stays as a ghost until it times out, he will be unable to join from the new connection. That's because Prosody allows to join twice under the same nickname from the same bare JID. Jicofo will not distinguish between those two users and will not invite the second one to the conference.
=> Append random hex string to MUC nickname with XMPP login

JitsiMeetJS.js, modules/xmpp/strophe.ping.js, modules/xmpp/strophe.util.js
This series of commits prevent Callstats.io from classifying conference as partially failed when that's not really the case.
=> False callstats failures

modules/xmpp/ChatRoom.js
Fixes a problem where, sending that namespace on every presence will make the server think we are joining every time and will return us the message history for the muc.
=> Uses the empty element with namespace for initial presence.

modules/RTC/RTCBrowserType.js
Currently when trying to debug React-Native app, we determined our browser to be Chrome, hich caused bugs.
This PR introduces better React-Native envrionment detection that works for debug mode too.
=> Correctly detect React-Native in debug mode

modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTCUtils.js
Now there is base ```dispose()``` implementation for ```JitsiTrack``` which cleans all attached events.
Also we call ```MediaStream#release()``` for MediaStreams in React-Native environment (https://github.com/jitsi/react-native-webrtc/blob/master/MediaStream.js#L75)
=> Better JitsiTrack#dispose() method to prevent memory leaks

package.json
This is in reference to the same type of issue on the jitsi-meet repo: https://github.com/jitsi/jitsi-meet/issues/694
The other pull request is listed here: https://github.com/jitsi/jitsi-meet/pull/733
=> Change reference to jitsi-meet-logger to use full github url

JitsiConference.js, JitsiConferenceEventManager.js, modules/RTC/RTC.js
Currently ```JitsiConferenceEvents.TRACK_REMOVED``` is fired for remote tracks only on ```XMPPEvents.REMOTE_TRACK_REMOVED``` event (https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L1116-L1132). 
However in the case when participant leaves conference at all and we get into ```JitsiConference#onMemberLeft()``` method, we just silently remove remote tracks without firing any events except for ```JitsiConferenceEvents.USER_LEFT``` (https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L623-L634).
This fact causes inconsistencies for library users. So in this PR I propose to always fire  ```JitsiConferenceEvents.TRACK_REMOVED``` whenever track is removed. Also with this PR we are going to fix warnings "Overwriting remote track!" every time user changes …
=> Fix JitsiConferenceEvents.TRACK_REMOVED is fired inconsistently

JitsiConference.js, JitsiConferenceEventManager.js, modules/xmpp/ChatRoom.js
Fixes attaching chat room listeners for statistics.
Cleans statistics after the participant was kicked.
=> Cleaning resources after leaving (kick)

JitsiMediaDevices.js, JitsiMeetJS.js, modules/RTC/RTCUtils.js
On Safari/IE we have to wait until the WebRTC stack is
initialized in case the plugin is being installed for
the first time.
=> Make 'isDeviceListAvailable' a Promise

JitsiConferenceEventManager.js, modules/xmpp/JingleSessionPC.js, service/xmpp/XMPPEvents.js
This PR triggers conference reload after 'session-accept' request timeout(which currently is unrecoverable error). Also flush() will no longer be called after 'session-accept' request is queued in order to avoid a race condition in Prosody's BOSH request handling which may cause some requests to be ignored and lost completely(see comment on flush() below).
=> Fix session-accept timeout

modules/RTC/JitsiLocalTrack.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js, service/RTC/CameraFacingMode.js
In some cases it's important to know if we are showing 'user' or 'environment' from camera (e.g. if we need to mirror it). This method will help us to determine facingMode of the video track if any.
=> Introduced JitsiLocalTrack#getCameraFacingMode() method and CameraFacingMode enum

JitsiTrackError.js, JitsiTrackErrors.js, doc/API.md, modules/RTC/JitsiLocalTrack.js
For some reason it's not possible to mute/unmute a JitsiLocalTrack when it's not inside a conference. But we need this functionality for React project, where we handle local tracks differently.
=> _setMute refactoring to allow muting/unmuting local tracks when they are not in conference

.jshintrc
Sorts the jshint configuration keys in alphabetical order (which
revealed that latedef was used twice with conflicting values). Removes
the early value of latedef because the late was in effect anyway.
=> Delete latedef repetition

JitsiMeetJS.js, JitsiTrackError.js, modules/RTC/RTCUtils.js
Retrieves real device error in the case where we request audio and video and one of them fails, but we receive successful callback from getUserMedia with one of the medias missing.
=> Improve device errors

doc/API.md, modules/xmpp/moderator.js, modules/xmpp/xmpp.js
This PR enables lipsync by default and removes the option from the conference options.
=> Enable lipsync by default + fixes

JitsiConference.js, JitsiConferenceEventManager.js, modules/RTC/RTC.js, modules/statistics/statistics.js, modules/xmpp/strophe.jingle.js, service/xmpp/XMPPEvents.js
The PR does necessary cleanup required after receiving 'session-terminate' to be able to start the conference again when new participant joins the room.
Required for https://github.com/jitsi/jicofo/pull/120
=> Handle session-terminate

modules/xmpp/xmpp.js
The places of the two arguments of the function createConnection were
switched in the function definition but the call to the function
remained unchanged.
=> Fix createConnection broken in 9781a0d

JitsiConference.js, modules/RTC/DataChannels.js, modules/RTC/RTC.js
This currently fixes problem for participants joining in a room with other participants and trying to send initial value of selected local participant will throw an error. And fixes a potential problem if the UI can select participants before their video is available, before session initiated, can make local state with jvb inconsistent. Also if we want to have multiple selected endpoints or pinned participants and this is done before session-initiate caching should be done before creating data channel (currently selecting multiple is not possible).
=> Moves caching of selected endpoint out of data channel.

modules/statistics/statistics.js
The problem described by the FIXME has been fixed by CallStats. The call restarted after it has been "session-terminated" are now reported correctly on CallStats dashboard.
=> Remove FIXME for CallStats not reporting restarted calls

JitsiConference.js, JitsiConferenceEvents.js, JitsiParticipant.js, modules/RTC/DataChannels.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js, modules/RTC/RTCBrowserType.js, modules/connectivity/ParticipantConnectionStatus.js, service/RTC/RTCEvents.js
This PR adds PARTICIPANT_CONN_STATUS_CHANGED conference event that will be fired when JVB sends notification over the data channel the the user is having problems with media connection.
On Chrome 'onmute' and 'onunmute' events are fired whenever the video tracks stops receiving data and the video freezes. We take those into account and trigger participant connection status updates when those events get out of sync with the video muted signalling.
=> Adds participant connection status notifications

JitsiConference.js, modules/connectivity/ParticipantConnectionStatus.js
This PR changes the amount of time we wait after RTC video track muted event before marking participant's connection as interrupted. It also makes the timeout value configurable, changes the default to 2 seconds and logs status updates on CallStats and analytics.
=> Participant connection status tune up and extra logging

modules/xmpp/strophe.rayo.js
In case of roomPass is undefined, an error occurs: Cannot read property 'length' of undefined.
=> Fixes sip calling.

modules/RTC/JitsiLocalTrack.js
We can not assume that the audio source is not sending any data based on the stat until the media connection has not been established.
=> Fix "no data from source" before ICE has connected

JitsiConference.js, JitsiConferenceEventManager.js, modules/statistics/statistics.js, modules/xmpp/ChatRoom.js, service/xmpp/XMPPEvents.js
Fixes when the promise is resoved and rejected.
Removes unnecessary removal of local streams and participants.
=> Fix JitsiConference.leave

modules/xmpp/JingleSessionPC.js, modules/xmpp/SDP.js
The flag when set to 'true' will enforce ICE failure. It is supposed to be used in automatic testing.
=> Add 'failICE' config option

modules/RTC/JitsiRemoteTrack.js, modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js
Lib-jitsi-meet uses Temasys on Internet Explorer and Safari so it does
not make sense to require its adapter.screenshare.js on React Native,
for example, where it fails anyway.
=> Disable Temasys on React Native

modules/statistics/CallStats.js
The issue was that we were setting  userID to [Object object] since the format of userID was changed from String to Object.
Now the code is simplified and the userID is correct.
=> Fixes callstats feedback

JitsiConference.js, JitsiParticipant.js, modules/RTC/JitsiTrack.js, modules/connectivity/ParticipantConnectionStatus.js
First part of the PR applies some of the comments for the original PR:
https://github.com/jitsi/lib-jitsi-meet/pull/259
The second part addresses an issue where participant's connection status would end up stuck in "disconnected" on device switch/screen sharing(sometimes).
=> Fix participant connection status stuck after device switch

JitsiConnectionEvents.js, modules/xmpp/xmpp.js
The goal of this PR is to trigger the CONNECTION_FAILED event when the XMPP connection is dropped.
=> Page reloads on BOSH HTTP errors

JitsiConference.js, JitsiConferenceEventManager.js, JitsiTrackEvents.js, modules/statistics/CallStats.js, modules/statistics/RTPStatsCollector.js, modules/statistics/statistics.js, service/statistics/Events.js
Removing the audio problem detection that was checking for  remote streams with audioOutputLevel = 0 and  bytesReceived > 10. Detected problems were logged in the console and sent to callstats. Since the detection wasn’t reliable we don’t need it.
=> Remove audio problem detection

JitsiConferenceEventManager.js
This PR fixes:
Logger.js:89 [modules/xmpp/moderator.js] <i.onMucMemberLeft>:  Someone left is it focus ? hxxxxp@conference.beta.meet.jit.si/7e49f474
Logger.js:89 [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read property 'getTracks' of undefined Script: https://beta.meet.jit.si/libs/app.bundle.min.js?v=1429 Line: 37 Column: 21914 StackTrace:  TypeError: Cannot read property 'getTracks' of undefined
at n.<anonymous> (https://beta.meet.jit.si/libs/app.bundle.min.js?v=1429:37:21914)
at n.emit (https://beta.meet.jit.si/libs/lib-jitsi-meet.min.js?v=1429:1:17598)
at n.<anonymous> (https://beta.meet.jit.si/libs/lib-jitsi-meet.min.js?v=1429:23:10144)
at n.emit (https://beta.meet.jit.si/libs/lib-jitsi-meet.min.js?v=1429:1:17598)
at …
=> Fix Uncaught TypeError: Cannot read property 'getTracks' of undefined

modules/connectivity/ParticipantConnectionStatus.js
The PR fixes one case missing from https://github.com/jitsi/lib-jitsi-meet/pull/292
If there was no notification from the JVB about the connectivity status
it means it's connected. That's because the bridge does not send any
notification unless there is a problem.
=> Second attempt on #292

modules/RTC/RTCUtils.js
Since FPS only applies when video is requested, move this block to where the rest of the video constraints are applied.
=> Set the FPS constraints only when video has been requested

modules/statistics/LocalStatsCollector.js
LocalStatsCollector uses a global AudioContext for implementing metrics on webrtc audio streams. If there is an audio stream the stream gets attached to the global AudioContext and metrics for this stream are collected.
When using lib-jitsi-meet with no audio streams (for example only screen sharing) the orphan AudioContext does have a default audio level. In other words even if no audio stream is attached to it the element plays some default sound using cpu/battery and most crucial in clients with virtualized harware causing network traffic to send audio output to local hardware which clients are operating.
The solution provided suspends the global AudioContext right after its creation. Therefore, there is no default audio signal emitted by it.
=> Suspend LocalStatsCollector#AudioContext if not used.

package.json
because older versions don't work with our .jslintrc file
=> chore: Only uses jslint 3+

JitsiTrackError.js
JitsiTrackError extends Error. Due to an issue with babel, extending built-in classes seems not very good idea(https://github.com/babel/babel/issues/3083). 
This PR fixes `instanceof JitsiTrackError` calls.
=> Fixes instanceof JitsiTrackError

modules/connectivity/ParticipantConnectionStatus.js, service/RTC/RTCEvents.js
This PR fixes issue when video muted signalling arrive after the timeout which adjusts user's status to disconnected. It also refactors the logic from event based like advised during https://github.com/jitsi/lib-jitsi-meet/pull/292 review.
=> Connection problems indication stalled when video muted

modules/xmpp/JingleSessionPC.js, modules/xmpp/TraceablePeerConnection.js
The app will crash if the user tries to start screen sharing from "video muted" state.
=> Fix crash on screensharing when video muted

JitsiConference.js, modules/xmpp/ChatRoom.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SdpConsistency.js, modules/xmpp/TraceablePeerConnection.js
Video SSRC has to be generated for the recvonly stream if there are no video tracks in the PeerConnection.
=> Fix conference being broken after someone without any video device joins (ver 2)

webpack.config.js
The configuration of webpack 1 does not fully work on webpack 2 without
modifications.
Unfortunately, webpack 2 produces a larger jitsi-meet bundle at this
time. Since the webpack version of lib-jitsi-meet is restrained by the
webpack version of jitsi-meet, we cannot move to webpack 2 right now.
=> Prepare for webpack 2

modules/RTC/JitsiLocalTrack.js
Some runtimes such as React Native don't have a window.location.protocol
property, so don't check for it, assume removeStream is available.
I tried to do some "git archeology" in order to find why the check was introduced, but I couldn't find anything, it was introduced in https://github.com/jitsi/lib-jitsi-meet/commit/2328443ecb5d4aff8d284a2f92b097d5936c2f7e#diff-922e8edf325ba2a951da3fe2c72eaad4 as part of a larger refactor (the check wasn't present prior to the refactor).
=> fix: remove unneeded test when muting a local stream

doc/API.md, modules/xmpp/SDPUtil.js, modules/xmpp/SDPUtil.spec.js, modules/xmpp/SampleSdpStrings.js, modules/xmpp/TraceablePeerConnection.js
the idea here is to let clients configure a preference for h264 if it's in the offer.  the plan for now is that just ios would exercise this.
=> if enabled, prefer to use h264 (if it exists in the offer)

modules/xmpp/moderator.js
The feature has been replaced so the option no longer applies.
=> cleanup: remove adaptive las N config option

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/xmpp/ChatRoom.js, modules/xmpp/JingleSession.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/TraceablePeerConnection.js, modules/xmpp/strophe.emuc.js, modules/xmpp/strophe.jingle.js
This PR detaches components one from another to end up with JitsiConference managing the jingle session instance instead of the ChatRoom.
=> Move JingleSessionPC from ChatRoom to JitsiConference

modules/RTC/RTCUtils.js
Otherwise Chrome has been seen using a simulcast layer with a resolution of 240
x 135, which can break implementations not supporting odd resolutions, such as
WebRTC on Android.
=> Make sure the minimum resolution is no less than 320 x 180

modules/xmpp/JingleSessionPC.js
This PR fixes a crash when conference is being moved to new JVB.
=> Fix broken 'transport-replace'

modules/RTC/RTCUtils.js
This reverts commit 886bc1519de7830314819f9fded692956b1bbedf.
Turns out Chrome decides to not choose the maximum possible resolution when
given a range. Oh well!
=> Revert "Make sure the minimum resolution is no less than 320 x 180"

modules/RTC/TraceablePeerConnection.js, modules/xmpp/moderator.js, modules/xmpp/xmpp.js
It used to be true by default, enforced by the library, without any
configuration option. This is the case for tag 1631, for example.
Later on, the default was changed to false and the configuration option is now
honored.
This creates a problem in the current situation:
* user A (using a new lib-jitsi-meet) creates the room and passes disableRtx as
false (the new default)
* user B (using the old lib-jitsi-meet) joins the room
* RTX will be used because user B advertised RTX support and the conference has
it enabled
* user B will fail to join because its lib-jitsi-meet is not RTX ready
=> rtx: set disableRtx default to true

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/RtxModifier.js, modules/xmpp/SdpConsistency.js, modules/xmpp/SdpTransformUtil.js
SdpTransformUtil is a utility which encapsulates common operations on 'sdp-transform' lib objects. Currently used by SdpConsistency and RtxModifier, but there are plans for adding new classes in future refactoring towards the peer to peer.
=> Add SdpTransformUtil.js

modules/statistics/RTPStatsCollector.js
Fixes an issue, where on FF we show a lot of addresses and ports (apparently not the correct one).
=> Uses transport date only from succeeded pair.

modules/xmpp/ChatRoom.js
The xmpp kicked event wasn't being emitted because of an undefined method being referenced.
=> Remove references to undefined dispose method

modules/RTC/RTC.js
The first time a lastN was received it was ignored because the old lastN was
null, handle that case properly.
Furthermore, use default function parameters to avoid a conditional.
=> fix(lastN): handle first lastN message correctly

modules/RTC/RTCBrowserType.js
The setting of currentBrowser in RTCBrowserType was
accidentally removed.
=> Set the currentBrowser if Internet Explorer is detected

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/LocalSdpMunger.js, modules/RTC/RTCBrowserType.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/RtxModifier.js, modules/xmpp/SdpConsistency.js
Get rid of detach/attach methods and use SDP direction 'inactive' to stop sending data on JVB connection when switching to P2P.
=> Use media direction in P2P

modules/RTC/RTCUtils.js
Even if EDGE does support getUserMedia and some kind of limited RTCPeerConnection, it does not work yet (work in progress), so ensure that EDGE is identified as an unsupported browser for now.
=> edge: Ensure "unsupported" is triggered for now (until fully supported)

package.json
The net effect is the same, with the bonus that it avoids problems when running
yarn.
=> build: run webpack on postinstall

package.json
=> build: drop babel-pollyfill dependency

JitsiConference.js, JitsiConferenceEvents.js, JitsiMeetJS.js, JitsiParticipant.js, modules/connectivity/ParticipantConnectionStatus.js
The peer connection used to be check with is connection active. Adding new states like active, inactive, when the connection was intentionally stopped by the bridge, interrupted due to network problem and restoring, which is the state of a peer which was inactive as being out of lastN and is now entering lastM and eventually will become active.
=> Adds peer connection statuses (active/inactive/interrupted/restoring).

JitsiConference.js, modules/RTC/JitsiLocalTrack.js
When muted track was added to conference "mute" operation was
executed again which was not executing anything because the state
of the track was already muted.
=> fix(JitsiLocalTrack): Remove unnecessary mute operation

JitsiConference.js
Log when P2P succeeds or fails. Also log when a conference switches back to the JVB connection.
=> feat(p2p): log analytics event

modules/statistics/RTPStatsCollector.js
My JavaScript monitoring tool regularly reports failures inside the `processStatsReport` function in `RTPStatsCollector.js`
The Chrome `getStats` API returns a `RTCStatsResponse` on success, whose result method returns a list of `RTCStatReport` objects.
It appears that sometimes the list of `RTCStatReport` objects may include `undefined` objects.
This PR adds a check for this, and skips trying to process `undefined` objects.
=> Add a check for "undefined" RTCStatsReport objects

modules/statistics/CallStats.js, modules/statistics/statistics.js
Will emit BEFORE_STATISTICS_DISPOSED event, before the last CallStats fabric is terminated to make sure that the final logs batch is reported correctly.
Also adds a check for CallStats instance to queue events when the backend has been initialised, but there is no CallStats instance available to report on. This fixes errors printed to the console, after the call has ended.
=> Fix errors with sending final logs batch to CallStats

modules/connectivity/ParticipantConnectionStatus.js
This PR removes a single event (peer.conn.status) from all analytics output.  This event isn't used anywhere, and is overly chatty.
=> remove analytics event for peer conn status, not used

modules/RTC/RTCUtils.js, modules/RTC/TraceablePeerConnection.js
Avoids having to do browser checks twice.
Fixes: #423
=> tpc: use the peerconnection type constructor from RTCUtils

modules/xmpp/ChatRoom.js
Sending the bare jid, speeds call setup as otherwise jigasi needs to do a feature discovery finding the conference component address and use it to construct the room address to join.
=> Sends the bare jid of the room on call out.

modules/RTC/JitsiTrack.js
For muted tracks, it is possible for undefined to get pushed
into the track's internal containers reference. The fix is
to immediately set the internal container variable in .attach()
to the passed in container value.
=> fix: ensure container is defined while attaching a track

modules/RTC/LocalSdpMunger.js, modules/xmpp/SdpConsistency.js
Currently, when a participant joins hidden/video muted, we add a
recvonly SSRC so that the client sends RTCP reports with that SSRC. This
SSRC doesn't have neither simulcast nor RTX enabled. When the user
decides to enable his video camera, we "enhance" this SSRC with params
for RTX and simulcast. However, Chrome does not take into account these
new params because of
https://bugs.chromium.org/p/webrtc/issues/detail?id=7555. By not adding
a recvonly SSRC, we activate the default behavior in Chrome which is to
send RTCP reports with SSRC 1. So, when the user decides to enable his
video camera, instead of updating/enhancing the existing SSRC, we
initalize the primary SSRC with the correct params.
=> ref(sdp): Do not add recvonly SSRC for muted video tracks.

modules/statistics/CallStats.js, modules/statistics/statistics.js
Internet Explorer is throwing an error when doing a for...of over
Sets. This is because IE needs a Set polyfill, which may be applied
after lib-jitsi-meet has loaded. However, lib-jitsi-meet on load
creates two Sets, one for CallStats.fabrics and another for
Statistics.instances. When the polyfill is then applied, the two
existing Sets do not get new methods. The fix is to lazily
initialize the Sets to allow for polyfills to be applied.
~~Internet Explorer is throwing an error when doing a for...of over
sets. Set.prototype.values() is also throwing an error...so the
compromise was ensuring the sets being iterated over are indeed
arrays.~~
~~I'm open to changing this fix or more opinions on what to try out.
I don't completely understand right now why iterating over sets
would be broken on …
=> fix(stats): lazy initialization for statistics Sets

modules/statistics/RTPStatsCollector.js
We ignore stats that were remotely calculated and take into account only local one.
=> Fixes local stats calculations for Firefox.

modules/RTC/RTCBrowserType.js, modules/RTC/TraceablePeerConnection.js, package.json
Move 'isSimulcastSupported' check from sdp-simulcast to the client.
Depends on https://github.com/jitsi/sdp-simulcast/pull/11
=> Upgrade sdp-simulcast

doc/tokens.md, modules/xmpp/xmpp.js
Token is passed as parameter when creating JitsiConnection and we no longer use it from the options passed to the connection.
=> Removes obsolete config.token.

JitsiConference.js, modules/RTC/RTCBrowserType.js, modules/connectivity/ConnectionQuality.js, modules/statistics/AvgRTPStatsReporter.js, modules/statistics/RTPStatsCollector.js
AvgRTPStatsReporter will calculate arithmetic means of 'n' samples
and submit the values to the analytics module. The 'n' value is
configurable through 'avgRtpStatsN' conference config option. When set
to non-positive value the AvgRTPStatsReporter will be disabled.
The following values are reported:
- average upload bitrate => 'stat.avg.bitrate.upload'
- average download bitrate => 'stat.avg.bitrate.download'
- average upload bandwidth => 'stat.avg.bandwidth.upload'
- average download bandwidth => 'stat.avg.bandwidth.download'
- average total packet loss => 'stat.avg.packetloss.total'
- average upload packet loss => 'stat.avg.packetloss.upload'
- average download packet loss => 'stat.avg.packetloss.download'
- average FPS for remote videos => 'stat.avg.framerate.remote'
- average FPS for …
=> Report average RTP stats to anayltics

modules/xmpp/JingleSessionPC.js
Will emit analytics events for ICE gathering and ICE checks duration,
separately for initiator/responder and p2p/jvb connections. Initiator
and responder have to be separated, because the flow and the values have
significant differences.
XMPPEvents.CONNECTION_ESTABLISHED is emitted outside of 'is stable'
condition, because for the JVB connection the signalling state is often
not in 'stable' ('have-remote-offer') state when ICE goes to
'connected'.
=> Analytics for ICE checks and gathering durations

modules/xmpp/JingleSessionPC.js
Will report total ICE establishment time under
'ice.initiator.establishmentDuration' and
'ice.responder.establishmentDuration' ('p2p.' prefix added for P2P).
It's the amount of time between the time when either checking or
gathering started (whichever starts first) and when ICE entered
'connected' for the first time.
=> feat(JSPC): ICE establishment time

JitsiConference.js
For debugging purposes, it's sometimes useful to override the
infrastructure level channel LastN value via the URL (i.e. by launching
https://meet.example.org/room#config.channelLastN=X). This commit
achieves this by calling the JitsiConference.setLastN method during the
Jitsi conference initialization phase.
=> Allow override of the infrastructure level channel LastN value.

JitsiConference.js, JitsiMeetJS.js, connection_optimization/external_connect.js
Use new global property window.jitsiAnalyticsPermanentProperties to report deployment-specific properties
no longer need to set jitsiRegionInfo from external_connect, instead rely on new global property from Jitsi meet local.html, can be customized by deployment
=> remove jitsiRegionInfo from lib-jitsi-meet

modules/connectivity/ParticipantConnectionStatus.js
When video track is frozen in P2P mode it should be INTERRUPTED instead of INACTIVE.
=> fix(ParticipantConn...Status): bug in p2p status

modules/RTC/JitsiRemoteTrack.js, modules/statistics/RTPStatsCollector.js
Temasys has support for local stats so add it to the supported browser list. In order for stats to display on Internet Explorer, a script error had to be addressed. Internet Explorer tracks returned by temasys do not have addEventListener.
=> fix(stats): Enable stats on temasys

JitsiConference.js, JitsiMeetJS.js, JitsiTrackEvents.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js
Reorders JitsiTrackEvents.TRACK_AUDIO_LEVEL_CHANGED event arguments by
putting TraceablePeerConnection at the end. This way it's easier to
treat it as "library internal".
=> ref(JitsiTrackEvents.TRACK_AUDIO_LEVEL_CHANGED): reorder args

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
The P2P will break and never receive video in case a video track is not added, before the initial offer/answer. That's because we'll sent the media direction as recvonly and it is never updated on the remote side after initial offer/answer. We need to always advertise 'sendrecv' through Jingle. This used to work fine in JVB connection, because it's Jicofo that creates the offer and the media direction is always 'sendrecv'.
Also simplifies signalling for SSRC ownership in P2P where we can always assume that the remote peer owns all SSRCs. Without the fix P2P connection will fail to process 'source-add' notifications.
=> P2P video track added later

modules/xmpp/strophe.jingle.js, modules/xmpp/xmpp.js
Please let me know if this breaks any previous functionality. I don't think we're using anywhere STUN/TURN for the JVB connection, but I may be wrong.
=> ref: Use STUN/TURN for the P2P connection.

modules/RTC/BridgeChannel.js
They are really verbose, and add no real value. In addition, log the channel
type once opened.
=> feat(BridgeChannel): don't log channel objects

modules/xmpp/strophe.jingle.js, modules/xmpp/xmpp.js
Old config.js versions don't have the p2p property.
=> fix: Check for undefined before accessing config.p2p

JitsiConference.js
The P2P session must be stopped with '_stopP2PSession' once accepted.
Fixes the problem with CallStats not being disposed when in 'forced JVB 121' mode.
=> fix(JitsiConf...): stop P2P on JVB121

modules/xmpp/JingleSessionPC.js
Due to it being ran asyncronously, it's possible a replaceTrack operation is
scheduled while there is a valid PC, but by the time it runs was closed.
Accommodate to this situation by pretending everything is just peachy.
=> fix(JingleSessionPC): avoid failures if replaceTrack runs late

JitsiConference.js, modules/statistics/AvgRTPStatsReporter.js, modules/statistics/RTPStatsCollector.js, modules/xmpp/JingleSessionPC.js
A call isn't just relayed. It may be the case that the local participant is using a relayed address, while the remote one is directly connected to the TURN server. We add a 'remoterelayed' and 'localrelayed' in the stats that holds this piece of information.
=> Treats local/remote relayed addresses differently.

modules/xmpp/ChatRoom.js
If we detect a custom <ignore tag in presence unavailable we ignore those presences and do not process them.
=> Allows unavailable presences to contain a ignore tag.

modules/RTC/RTCUtils.js
AP: echoCancellation is a "master switch" for disabling all audio processing.  setting disableAP=true and stereo=true allows fullband, stereo sound.
AGC: misbehaves with certain 'pre-gained' mics. allows to turn off.
HPF: can't hear any effect but it's the last constraint to make configurable.
=> make audio processing constraints configurable

JitsiConference.js, modules/xmpp/JingleSessionPC.js
The 'ondatachannel' even listener must be set as soon as
the TraceablePeerConnection is created and before the offer is accepted.
We've observed situations where the ondatachannel event was missed,
because the listener is bound too late from the JingleSessionPC
'acceptOffer' success callback.
=> fix: never miss 'ondatachannel' event

modules/xmpp/JingleSessionPC.js
In case when the answer is being set for the first time, full sRD/sLD
cycle is required to have the local description updated and SSRCs
synchronized correctly. Otherwise SSRCs for streams added after invite,
but before the answer was accepted will not be detected. The reason for
that is that renegotiate can not be called when adding tracks and they
will not be reflected in the local SDP.
In this commit there's also change in the invite method to call
setLocalDescription after createOffer in order to have local description
updated. Then when answer is being accepted it can be used in
the 'oldSDP' var to compare with the new one in case any streams have
changed.
=> fix(JSPC): local tracks not advertised

JitsiTrackError.js, JitsiTrackErrors.js, doc/API.md, modules/RTC/JitsiLocalTrack.js
Instead of failing with an error if another operation is in progress, which is
impossible to know as a user, chain them using the primises API.
=> feat(JitsiLocalTrack): make mute/unmute more resilient

JitsiConference.js
There are scenarios when it's ok to call setP2PStatus again with
the same value. For example when P2P is stopped, before it starts with
the A/B testing mode enabled. It's only important to know that it
happened, but it's not an error, because the code will not execute
and return immediately.
=> fix(JitsiConference): reduce verbosity level

modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/LocalSdpMunger.js
Local video was being detached when rapidly muting/unmuting, because of the "track ended" event being fired and that was not handled correctly.
=> Fix local video disappearing from local thumbnail

modules/RTC/adapter.screenshare.js
Loading lib-jitsi-meet on an iOS WebView (UIWebView & WKWebView) currently fails due to its user agent string not matching any of the existing checks. This causes the script to fail due to undefined `webrtcDetected...` variables.
This adds a check for those webviews and sets detection variables similar to Safari.
=> Add check for iOS WebViews in screen sharing adapter

modules/RTC/JitsiLocalTrack.js, modules/RTC/LocalSdpMunger.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
The 'setMutedInProgress' flag is unreliable and it can lead to weird
situations when mute operation is in progress, but the removal from
JingleSessionPC is waiting on the queue. In such case LocalSdpMunger
will fake SDP even if the track is in the PeerConnection which may
confuse some parts of the SDP transformation chain.
For example RtxModifier will not attempt to inject Rtx group description
if it sees that the SSRC are already there. But it can happen that even
though the SSRCs are there they do not contain valid track ID, because
the track has changed.
The LocalSdpMunger is supposed to fake the SDP only when the video
MediaStream is not in the PeerConnection. So this commit implements just
that: a way to tell if JitsiLocalTrack's stream is currently in
the PeerConnection (added …
=> ref(JitsiLocalTrack): get rid of 'setMutedInProgress'

modules/RTC/TraceablePeerConnection.js
for p2p, we have to take preferh264 into account when setting the local description, since
that is the offer that will be received by the far side.  if we only do it on the remote description,
like before this change, we'll never actually end up preferring h264 in p2p
=> enforce preferh264 when setting the local description

JitsiMeetJS.js, modules/settings/Settings.js, modules/statistics/AnalyticsAdapter.js, modules/statistics/statistics.js, modules/xmpp/moderator.js
Because the implementation of LocalStorage in jitsi-meet at the time
of this writing is asynchronous with respect to loading and saving,
delay the generation of machineId in order to allow LocalStorage to
load any previously saved value.
=> [RN] Delay the generating of machineId

modules/RTC/RTCUtils.js
The default was still 360p if the option was missing from config.js. In
addition, move the logic outside of a browser check, so all browsers get
glorious HD by default.
=> feat(RTC): fix using 720p resolution by default

doc/API.md, modules/RTC/RTC.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SDPUtil.js, modules/xmpp/SDPUtil.spec.js
This is performed by stripping all traces of H.264 from the local SDP before
passing it to `setLocalDescription`.
=> feat(h264): add ability to disable H.264

JitsiConference.js, JitsiParticipant.js, doc/API.md, modules/statistics/statistics.js, modules/xmpp/ChatRoom.js
The feature is behind a flag which is disabled by default.
=> Uses optional statsId to report to callstats and push it to presence.

modules/RTC/RTCBrowserType.js, modules/RTC/ScreenObtainer.js
To install the chrome webstore extension, the user must already have installed "Download Chrome Extension". On missing extension we open a popup window which allows the user to add the extension and then install it.
=> Enables desktop sharing when using opera.

modules/xmpp/JingleSessionPC.js
Do not log whole objects on Jingle error, as these may cause trouble on iOS react-native.
=> ref(JingleSessionPC): do not log whole objects

JitsiMeetJS.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/RTC.js, modules/RTC/RTCBrowserType.js, modules/RTC/RTCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/connectivity/ConnectionQuality.js, package.json
- Add a new browser check so adapter shim usage can be gated.
- Get track resolution for stats from the track itself to account
for browser resolution fallback logic. Do this only if
we can be sure adapter has shimmed it in.
- Create a new getUserMediaFlow, with RTC being the orchestration
for various RTCUtils calls.
- Remove connection quality stat "resolution" which was being
emitted but not used but listeners.
=> feat(1080p): support on chrome using adapter

modules/RTC/LocalSdpMunger.js, modules/RTC/TraceablePeerConnection.js
Firefox has deprecated modifying a description's sdp through
re-assignment. Safari (without temasys) does not allow it.
As such, wherever the sdp has to be modified instead create
a new description with the modified sdp.
=> fix(peerconnection): create a new description to modify sdp

modules/RTC/LocalSdpMunger.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/RtxModifier.js, modules/xmpp/SDPUtil.js, modules/xmpp/SdpConsistency.js
Safari will be audio only and error handling for missing video or local description has to be modified to prevent renegotiations from being halted by an error.
=> Modify error handling for missing video m-lines and local description

JitsiConference.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js, modules/util/StringUtils.js, modules/xmpp/JingleSession.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/strophe.jingle.js
Re-implements the "suspend video " A/B test. 
The test is enabled if config.abTesting.enableSuspendVideoTest==true.
If the test is disabled the previous behavior is preserved, and no properties are added to the analytics events.
If the test is enabled, the two participants in a p2p call will agree on a boolean value based on the JID of the Jingle initiator (which is essentially selected randomly). If the agreed-upon value is true, the suspend video option will be enabled; otherwise, it will be disabled. The two participants will include this value in analytics events with the "abtestP2PSuspendVideo" property.
=> Video suspend abtest

modules/RTC/TraceablePeerConnection.js, modules/RTC/TraceablePeerConnection.spec.js
Safari will fail to set its remote description if no
supported video codecs are found. This can happen with
config.p2p.disableH264 set to true, as browsers will strip
H264 from their offers. To get around this problem in a way
that can be removed once this is fixed on Safari's side,
add a function to inject H265 before setting the remote
description.
=> fix(adapter): inject h264 into safari's remote description

modules/statistics/AnalyticsAdapter.js
AnalyticsAdapter is initialized on file load. The constructor
calls a method that calls Object.assign. All this happens
before jitsi-meet has loaded polyfills. So, instead
initialize permanentProperties inline with the expected
values, avoiding Object.assign.
=> fix(analytics): initialize permanentProperties inline

modules/RTC/RTC.js, modules/RTC/RTCUtils.js
When a mac's default audio output is changed, audio elements
are not being updated with the new default. A default audio
output change in the OS fires a DEVICE_LIST_CHANGED event,
so use that to always update the sinkId.
Also, use wrapAttachMediaStream for newGumFlow to be ensure
the proper sinkId is set on audio elements being coupled
a remote track.
=> fix(audio-output): update sinkIds on load and device list change

JitsiTrackError.js, modules/RTC/RTCUtils.js
This is a two part fix:
- In the new gum flow, this.getUserMedia supports promises
and rejections were not getting caught. So change
_newGetUserMediaWithConstraints to be promise based instead
of callback.
- The error name returned from blocked device permissions is
NotAllowedError, as adapter shims PermissionDeniedError
to be NotAllowedError.
=> fix(gum): handle NotAllowedError

modules/RTC/JitsiLocalTrack.js
If a mute / unmute operation is queued when the track is disposed, fail with an appropriate error.
=> feat(JitsiLocalTrack): fail mute operation when track is disposed

JitsiMeetJS.js
The error handling block for unsupported resolution can be
skipped because native gum should be doing automatic retries
at lower resolutions and leaving in the handling will only
cause an infinite loop. Analytics for the error still get
sent in the error handling directly below the retry logic.
=> fix(gum): skip retry if using new gum flow

JitsiConference.js, JitsiConferenceEventManager.js, modules/RTC/TraceablePeerConnection.js, modules/statistics/CallStats.js, modules/statistics/statistics.js, service/RTC/RTCEvents.js
Adds rtc.LOCAL_TRACK_SSRC_UPDATED event to be emitted when ssrc is updated for a local track.
Fixes adding rtc listeners for CREATE_ANSWER_FAILED, CREATE_OFFER_FAILED, SET_LOCAL_DESCRIPTION_FAILED, SET_REMOTE_DESCRIPTION_FAILED.
=> Reports ssrc to callstats when screen sharing is started.

modules/xmpp/RtxModifier.spec.js, modules/xmpp/SampleSdpStrings.js, modules/xmpp/SdpTransformUtil.js
this was causing us to generate an rtx ssrc for the fec stream
=> exclude fec-fr secondary ssrcs when looking for primary ssrcs

modules/xmpp/xmpp.js
Strophe's builtin retry mechanism uses exponential backoff, and 5 retries
results in a very long time.
=> feat(xmpp): lower max XMPP retries to 3

modules/RTC/TraceablePeerConnection.js
Calling JSON.stringify on a temasys object causes a stack overflow.
The result is that the JingleSessionPC's work queue never gets
cleared so future work, like video muting, will not get called.
Instead of passing in the candidate directly, manually do
what chrome's implementation of candidate.toJSON does.
=> fix(ie11): do not call JSON.stringify with temasys ice candidate

modules/RTC/TraceablePeerConnection.js
jitsi-meet has been changed to have tpc.js on info by default, so these
logs still won't show by default.
=> move the tpc transform logs to debug

modules/RTC/TraceablePeerConnection.js
In Rect Native it will stall the app as it's huge.
=> feat(TPC): don't log the entire datachannel event

modules/statistics/AnalyticsAdapter.js
Avoid throwing an exception if an analytics handler throws one. Emit a warning
though, so the problem can be eventually caught and fixed in the handler.
=> feat(analytics): shield handler execution

modules/RTC/LocalSdpMunger.js, modules/RTC/RTC.js, modules/RTC/TraceablePeerConnection.js, modules/util/MathUtil.js
This commit will append "-" + tpc.id to every local 'MSID', 'cname',
'label' and 'mslabel', before feeding the local SDP to the Jingle layer.
It will make stream IDs unique across TraceablePeerConnection instances
and prevent from conflicts in some corner cases.
For example this will fix a problem where if the client drops
the conference without leaving the XMPP MUC gracefully and will join
the conference again without recreating the local tracks it would lead
to the MSID conflict, because the stream is still advertised by
"the ghost" participant.
=> feat(TPC): append TPC ID to stream IDs

modules/connectivity/ConnectionQuality.js
In some cases a high bitrate does not equate to a high quality
percentage, because the target itself might be quite high, such
as the case for 1080. In those cases, give credit for the bitrate
being high.
=> fix(connection-quality): set min percentage when exceeding a bitrate threshold

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
This PR exposes the stats gathering functionality that's already built-in the TraceablePeerConnection that has it gather stats from the wrapped PeerConnection. This is useful in debug scenarios as it allows to extract and process the stats.
Please don't merge this yet, it's WIP and I haven't tested it yet.
=> feat: Adds a config.gatherStats parameter.

modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js
Adds stats and audio levels for Safari. Enables the new getStats API for Firefox, that will get rid of the following warning:
'non-maplike pc.getStats access is deprecated, and will be removed in the near future! See http://w3c.github.io/webrtc-pc/#getstats-example for usage.'
=> Implements the promised based getStats. Enables them for Safari and FF.

modules/xmpp/strophe.jingle.js
3478 is default for TURN, but not for TURNS. Reported by @damencho.
=> fix: Don't remove the TURN port if it's the default.

doc/example/index.html
After running `npm install` I end up with a minified library for lib-jitsi-meet. I had to adjust the name to get the example to run
=> Adjust name of the js library

modules/RTC/ortc/RTCPeerConnection.js
Edge does not support trickle ice. In an attempt to work around
such, and get p2p working, some other work was needed to even
get to the point of ice failure. This is that some other work.
=> fix(edge): get p2p working up to ice failure

JitsiMeetJS.js, JitsiTrackError.js, modules/RTC/RTCUtils.js
When it fails we retry with different resolutions, and if that doesn't work we remove device id and let gum to decide which device to use.
=> Switches camera id to mandatory when using old gum flow.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.js, modules/xmpp/ChatRoom.js, modules/xmpp/recording.js, service/xmpp/XMPPEvents.js
- Pass you_tube_broadcast_id to Jibri so it can create a
YouTube link for the live stream.
- Emit the liveStreamViewURL (the YouTube link) when it
is received from the participant doing the recording.
=> feat(recording): show the YouTube live stream URL

modules/RTC/ScreenObtainer.js
When cancelling the prompt to install the extension, instead of
treating it as a generic error treat is as the cancel extension
error. This allows existing logic to trigger that will not show
an error message on cancel.
=> fix(screensharing): set error type for cancelling extension install

JitsiConference.js
JitsiConference shouldn't lie that the leave() was successful when it was not.
=> fix(JitsiConference.leave): reject in case of a timeout

modules/xmpp/JingleSessionPC.js
When switching bridges, removing the "data" section from the SDP
and doing a double offer-answer results in an error starting on
Chrome 63. So on 63 and up, do a single off-answer without
removing the "data" section.
=> fix(migration): do not do double offer-answer for Chrome 63 and up

modules/xmpp/JingleSessionPC.js, modules/xmpp/SDP.js
I've been looking at this with Brian (who has been doing most of the leg work...) and while this works we do not understand exactly why yet. The bridge is getting the sdp without the data channel but it is unknown where that is getting stripped.
Starting on chrome 63, an error occurs when renegotiating
with the new bridge on bridge migration when the SDP sections
do not match, which occurs when removing the data channel
section. Not doing the double renegotiate prevents the data
channel from being reopened. The way around this, while still
avoing the error, is to reject the data channel section instead
of removing it to trigger a new data channel.
=> fix(migration): reject the data channel to restart it

JitsiConference.js
Adds a getter to retrieve JitsiConnection instance used by the JitsiConference.
=> feat(JitsiConference): add 'getConnection' getter

JitsiConference.js, modules/recording/RecordingManager.js, modules/recording/recordingManager.js, modules/xmpp/ChatRoom.js, modules/xmpp/ChatRoom.spec.js, service/xmpp/XMPPEvents.js
VideoSIPGW takes in a chat room and uses instance variables
on the chat room. RecordingManager has been changed to
mirror this approach because of the case where jitsi is
deployed on a domain requiring authentication. In that
case, the initial chat room is created and fails, a
new chat room (connection) is created for authentication,
authentication is put onto the failed chat room, and the
failed chat room is used. As such, recordingManager
should not be tied to chat room creation itself but
rather tied to the first chat room.
=> ref(recording): change implementation to match VideoSIPGW

modules/xmpp/ChatRoom.js
When receiving presence, the XML is converted to JSON. In
the process, Strophe.getText is used, which calls its
xmlescape utility function. This is not desired as the
raw value is desired, especially for display name.
Note: this issue only affects presence as it is the only
place that call the helper packet2JSON, which is the only
place that calls Strophe.getText.
=> fix(presence): do not escape xml values

JitsiConference.js, JitsiConferenceEventManager.js, modules/xmpp/ChatRoom.js, modules/xmpp/ChatRoom.spec.js, service/xmpp/XMPPEvents.js
Depends on https://github.com/jitsi/jitsi-meet/pull/3182, but after merging this will update jitsi-meet PR with the lib-jitsi-meet hash.
=> Skips p2p with bot participants and re-initiate when they leave.

modules/xmpp/xmpp.js
User may decide to abort the connection while it's stuck at connecting.
This is required to fix a corner case on mobile where if there's no network connectivity while the connection is being established if the user will try to hang up it will have no effect. The connection may eventually be established which will then lead to weird side effects. In case it fails the reload screen will be displayed even though the user has decided to leave the conference.
=> fix(xmpp): allow to close the connection while connecting

modules/xmpp/SDPDiffer.js
The case where we had created recvonly streams (start muted on FF) and we are unmuting, this creates a sendrecv stream and adds msid, we need to signal msid so listeners to be notified and create appropriate audio/video element and to start receiving the stream.
=> Detects msid changes in sdp.

modules/RTC/JitsiLocalTrack.js
RTCUtils.attachMediaStream was changed not to return elements;
instead it returns undefined by default. When mapping over
containers and call RTCUtils.attachMediaStream, containers
would be changed to undefined.
=> fix(muting): do not re-assign value of local track containers

modules/RTC/RTC.js
Currently it is possible to try to change the max receive video
frame height before the data channel is open. In that case an error
will be thrown. This change makes it so that the desired frame height
is saved and sent on channel open, avoiding the thrown error the
max receive video frame height logic is exercised through the
JitsiConference api.
=> ref(video-quality): cache max frame height and send on channel open

JitsiConferenceEventManager.js
This simple change helps to prevent `'The conference is has been already left'` error after kick. 
`Conference.leave` will detach chatRoom instance itself.
=> Prevent error after kick user

package-lock.json, package.json, webpack.config.js
js-utils has some, so we need the preset or webpack fails with a syntax error.
=> feat(flow): fix webpack bundling when Flow annotations are used

doc/API.md
As a result of a [Jitsi community discussion](https://community.jitsi.org/t/enable-local-statistics/15070/3) it was determined that `connectivityEvents` had not made their way into the docs.  
This PR updates the API documentation to include `connectivityEvents` and marks `CONNECTION_STATS` as deprecated.
=> Updates API docs to include connectvityEvents

modules/RTC/TraceablePeerConnection.js
Just skip it in such environments, such as React Native.
=> feat(TPC): fix handling layer suspension when RTPSender is not supported

modules/browser/BrowserCapabilities.js
Safari 11 has `navigator.mediaDevices.ondevicechange` but doesn't define
`navigator.mediaDevices.addEventListener`. 🤦
Fixes: https://github.com/jitsi/lib-jitsi-meet/issues/823
=> feat(BworserCapabilities): fix device change detection

modules/statistics/RTPStatsCollector.js
The 'self.errorCallback' was passed incorrectly - it should have been bound to 'self' eventually, but now the arrow function is the preferred way.
=> fix(RTPStatsCollector): this.stop is 'undefined'

modules/RTC/ScreenObtainer.js, modules/browser/BrowserCapabilities.js
getDisplayMedia moved to navigator.mediaDevices and no longer works, falling back to inline installations.
https://github.com/w3c/mediacapture-screen-share/pull/86
=> Fixes getDisplayMedia after moving it to nvaigator.mediaDevices.

JitsiMeetJS.js, modules/RTC/RTC.js, modules/proxyconnection/ProxyConnectionPC.js, modules/proxyconnection/ProxyConnectionService.js, modules/proxyconnection/constants.js, modules/xmpp/xmpp.js
- ProxyConnectionService is exposed and meant to be the
facade for creating and updating a peer connection with
another peer, outside of the muc.
- ProxyConnectionPC wraps JingleSessionPC so the peer
connection handling can be reused.
=> feat(screenshare): support remote wireless screenshare

modules/statistics/CallStats.js, package-lock.json, package.json
It should be provided by the environment, just like on web. This avoids bundling
callstats on web, where it won't be used (we dynamically download it).
This reduces the bundle size from about 1MB to 675KB, almost 40%.
=> feat(callstats): don't inlcude react-native-callstats

modules/xmpp/ChatRoom.js
Currently when a participant removes the local display name, other clients are not updating their UIs because displayName in the nickname presence update is undefined.
=> fix(presence): emit display name change when cleared

modules/RTC/ScreenObtainer.js
=> feat(ScreenObtainer): add getDisplayMedia support for Firefox

package-lock.json, package.json
Strophe 1.2.16 contains a fix for a bug ([strophe/strophejs#299](https://github.com/strophe/strophejs/issues/299)) that also appears when using lib-jitsi-meet with ejabberd.
=> Upgraded Strophe to 1.2.16

modules/RTC/RTCUtils.js
Actually pass in the option to getTrackSSConstraints so it gets
applied to the desktop track.
=> fix(screenshare): constraints use desktopSharingFrameRate option

modules/RTC/RTCUtils.js, modules/proxyconnection/ProxyConnectionService.js
Spot is the consumer of screensharing using a camera
input and through a proxy connection. To differentiate
which one is active, declare a source type on the
created "desktop" stream.
=> fix(screenshare): specify source type for fake and proxy

modules/browser/BrowserCapabilities.js
jitsi-meet-spot currently supports mobile browsers. A
line should be drawn somewhere but maybe not here.
Chrome iOS does not have navigator.mediaDevices so add
a truthy check before checking for getDisplayMedia.
=> fix(screenshare): defensively check for getDisplayMedia

modules/RTC/TraceablePeerConnection.js, modules/statistics/RTPStatsCollector.js
In TraceablePeerConnection: we're no longer injecting a recvonly SSRC
when the local video track is muted, so it's normal that there is no
SSRC found in the local SDP when it's muted.
About RTPStatsCollector: at the time of adding this log statement a case
was missed when local audio track could be replaced in the P2P
connection when a new audio device is selected.
=> fix: remove obsolete warnings

modules/statistics/AnalyticsAdapter.js
If a custom handler has a dispose() function implemented, it will be called if the AnalyticsAdapter's dispose is also called.
=> Call Analytics' handler dispose() if exists.

JitsiConference.js
For now, a developer as a user of the library doesn't see any errors when using .lock() method without moderator role except promise rejection without any error. I've added error throwing with description to clarify the issue for users.
=> Add error description

modules/connectivity/ParticipantConnectionStatus.js
The idea is to not show the frozen video indication for intermittent failures which can be confusing to users.
=> ref(ParticipantConnectionStatus): bump frozen timeout to 10 sec

modules/xmpp/Caps.js, modules/xmpp/ChatRoom.js
Attempts to fix the following issue:
1. Electron user starts the conference join process.
2. Electron user adds remote control capability and
attempts to send presence.
3. Electron user presence send is blocked because the
conference has not been joined.
4. Electron user joins the conference.
5. The remote control capability is not emitted until
some other presence change triggers another
presence send. Until then, other uses will not see
remote control option available for the electron
user.
=> fix(presence): send latest presence on conference join

modules/xmpp/Caps.js
Attemps to fix this race condition:
1. Web client joins a conference
2. Electron client joins the same conference.
3. Web client requests capabilities of Electron
using version 1111.
4. Electron adds remote control capability,
settings its version to 2222.
5. Electron responds to web client's requests
but with features of 2222.
6. Web client caches request under 1111.
=> fix(caps): validate sha before caching features

modules/util/AsyncQueue.js, modules/xmpp/JingleSessionPC.js
Also do not execute any peerconnection callbacks like 'oniceconnectionstatechange', 'onicecandidate' etc. after close.
=> fix(JingleSessionPC): prevent from queueing tasks after close

modules/xmpp/StropheBoshLastSuccess.js, modules/xmpp/xmpp.js
Add 'timeSinceLastSuccess' to the details of connection dropped event.
=> feat: send analytics for the last successful request

modules/RTC/BridgeChannel.js
They contain no information about the failure (this is available in the onclose
event) and the event references the WS object itself, which causes hangs on
mobile.
=> fix(BridgeChannel): don't log WS onerror events

modules/xmpp/xmpp.js
With Octo we need to have all colibri endpoint IDs be 8 hex digits. This PR ensures this by:
1. Disabling the 'useNicks' option which allowed a value from config.js to be prepended to the nickname
2. Disabling prepending the node (part before @) for authenticated users.
In practice this means that jibri will get a new random ID instead of "recorder-xxxxxx" (the x's here being random), and the 'useNicks' option will cease to work. As far as I am aware the 'useNicks' option is not used anywhere, apart from debugging, and nothing depends on the nickname for jibri starting with "recorder" or anything similar for other authenticated users.
If there is a need, we can continue to support the 'useNicks' option, but not together with Octo (we could make that configurable in jicofo).
=> Always uses 8 hex digits for the MUC nickname/endpoint ID.

JitsiConference.js, authenticateAndUpgradeRole.js, modules/xmpp/xmpp.js
This functionality is being brought back for apps
that use ljm for its prosody logic but not for
video conferencing, ie Jitsi-Meet Spot. The desired
use is for Spot-TVs to be identifiable by their
jid alone and for the resource to be the part
that identifies them.
=> feat(xmpp): allow setting resource on room jid

JitsiConference.js, JitsiConferenceEventManager.js, modules/xmpp/ChatRoom.js
This change persists the display name in the chat message itself, so we'll have a display name for messages after rejoin (old participant details lost)
=> Add display name to chat message meta

JitsiConference.js, doc/API.md, modules/statistics/statistics.js
To be sure we always report room name in small case and as mobile and jigasi report this way it will take time for them to adopt which leads to wrong stats.
=> Partially reverts 24bda8e and uses domain/roomname to report to cs.

modules/connectivity/ParticipantConnectionStatus.js
The event TRACK_VIDEOTYPE_CHANGED passes only the video type
along, not the track.
This does remove a listener removal call. Alternatives thought of
- keep a cache of attached listeners to call off from
- change TRACK_VIDEOTYPE_CHANGED to pass "this" or the track ID as a second argument (added second to preserve backwards compatibiltiy)
=> fix(connection-status): pass expected args to type change listener

JitsiConference.js, modules/xmpp/strophe.emuc.js
* If a presence message was received from a room which the Emuc plugin did not know about, it would return undefined, causing Strophe to deregister the listener. Since this is by no means a fatal error, I modified the listeners to return true in such cases as well.
* the "removeCommandListener" method in JitsiConference did not have a handler argument, even though the underlying implementation in ChatRoom required one, so the call actually did not remove anything.
=> Fix listener issues in emuc Strophe plugin and JitsiConference

modules/xmpp/JingleSessionPC.js
If DTLS fingerprint remains unchanged after ice-restart there will be no media flow even thought the ICE connection will be re-established.
The workaround is to set an all zeros fingerprint on the hacky offer/answer cycle which is currently done in order to reset the data channels and the sequence number counters on the RTP receivers.
=> fix(JingleSessionPC): no media flowing after ICE restart

modules/RTC/RTCUtils.js
We had several reports that googSuspendBelowMinBitrate misbehaves, we had been running for a while with that disabled for the bridge, but it was causing problems and for p2p.
=> Removes disableSuspendVideo option.

modules/xmpp/ChatRoom.js
As discussed [here](https://community.jitsi.org/t/focus-user-visible-in-meet-conference/19997/7) presence stanzas not containing the muc presence extension create artifact users in the conference with the default nick. 
By ignoring presences with an undefined jid in the ChatRoom presence handler, this is avoided. Other presence processing remains untouched.
Thank you for your support @damencho  :)
=> ignore undefined from jid

modules/RTC/TraceablePeerConnection.js
Calls to insertDTMF will stop any tone
playing in progress. Prevent such by
checking the tonebuffer for any tones
in play and queue tone playing if
any tones are in play.
=> fix(dtmf): enqueue tones to be played

modules/xmpp/JingleSessionPC.js
We add the capScreenshareBitrate value to the permanent properties so
that it's included with every event that we send to the analytics
backend.
=> Adds the capScreenshareBitrate option to the permaprops.

modules/RTC/JitsiLocalTrack.js, service/RTC/MediaType.js
When the presenter track is unmuted, we do not need to add the track to the conference.
Currently, the lib tries to lookup for the presenter stream by comparing the MediaStreamTrack kind to that of the JitsiLocalTrack media type which is different from "video". When the stream is not found, it throws a TRACK_NO_STREAM_FOUND error. 
We now resolve the promise immediately and not proceed with adding tracks to the conference if the track media type is set to "presenter".
=> fix(presenter mode): Resolve promise instead of throwing error when presenter track is unmuted

modules/xmpp/strophe.jingle.js
As per the WebRTC spec, the RTCIceServer dictionary needs to have `urls` as member instead of `url`. Use of `url` is deprecated and the browsers currently throw a warning.
https://www.w3.org/TR/webrtc/#rtciceserver-dictionary
=> fix: Use RTCIceServer.ulrs instead of RTCIceServer.url

modules/RTC/RTC.js
Set the RTCBundlePolicy to max-bundle so that only one set of ice candidates is generated.
The default policy generates separate ice candidates for audio and video connections.
This change is necessary for Unified plan to work properly on Chrome and Safari.
=> Change the RTCBundlePolicy to 'max-bundle' for all peerconnections

modules/browser/BrowserCapabilities.js
The older version of Bowser (<2.0) reported Edge beta as chrome but now in Bowser 2.7, it comes back as Edge which is not in the list of supported browsers.
We now check if the Edge version > 72 to determine if it is Chromium based Edge (Chredge).
Chredge is added to the list of webrtc-capable browsers but we still display the warning that it is not one of the fully supported browsers.
=> Add Chromium based Edge (Chredge) to the list of webrtc-capable browsers

package-lock.json, package.json
and other chromium-like browsers.
The PR for js-utils - https://github.com/jitsi/js-utils/pull/21
=> dep(js-utils): do not use window.chrome to identify webOS 

modules/RTC/RTCUtils.js
Overconstrainederror occurs when calling gum with "exact"
when on URLs with a hash. To get around this, remove
"exact". Add handling for specified device not being
found, as we can no longer rely on "exact". This
still leaves open the possibility of the wrong
camera being accessed.
=> fix(screenshare): stop using exact for specified device sharing

modules/xmpp/XmppConnection.js
When Jiconop is used to attach to a warmed up BOSH session Strophe goes to ATTACHED instead of the CONNECTED state.
=> fix(XmppConnection): the ATTACHED state equals to CONNECTED with jiconop

modules/xmpp/XmppConnection.js
Copy/paste mistake - there's no such thing as this.connection in the XmppConnection. Hard to track down because no error is logged.
=> fix(XmppConnection): sendUnavailableBeacon

JitsiConference.js, modules/xmpp/ChatRoom.js, service/xmpp/XMPPEvents.js
Send conference.join event only after the peer connection is created.
This way we won't send events for lonely calls.
=> fix(analytics): delay conference.join event

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SDP.js
These are the first set of changes to LJM. The next PR will be take will have changes that will take into account the new sdp-interop module.
1. Reject m-lines with port 0 only when a=bundle-only is not present
2. Use unique session id per TPC.
3. Translate a=rid to Jingle only when simulcast through RIDs, i.e., ssrc-less simulcast is supported.
4. Trigger renegotation only when negotiationneeded event is fired on the browser.
5. Do not disable simulcast for screensharing in unified plan.
6. Fix the order of the simulcast streams for Firefox.
7. Use replaceTrack for applying stream effects in unified plan.
=> Unified plan changes - 1/2

modules/RTC/RTCUtils.js
Some devies may not be able to satisfy it and gUM will fail. Tested with a
crappy old camera which can only do VGA resolution at 4/3 aspect ratio.
=> rtc: remove default aspect ratio constraint

modules/xmpp/ChatRoom.js
Rebased version of https://github.com/jitsi/lib-jitsi-meet/pull/513
When modifying the room protection (setting or unsetting a password), the muc#roomconfig_passwordprotectedroom should always be defined. This fixes issue #512.
=> Modifying room password protection

modules/xmpp/xmpp.js
Prevents from calling disconnect on the Strophe connection if it already has been called or not connected.
=> fix(xmpp): prevent from calling disconnect twice

package.json
at o._interceptDoDisconnect (strophe.stream-management.js:207)
at P.Connection._dataRecv (strophe.umd.js:3140)
at I.Bosh._onRequestStateChange (strophe.umd.js:5012)
Update strophejs-plugin-stream-management to fix the crash for
the stacktrace above. It happens only with BOSH.
=> fix: Uncaught TypeError: CreateListFromArrayLike called on non-object

doc/API.md, modules/xmpp/moderator.js, modules/xmpp/xmpp.js
The LipSyncHack is currently broken in Jicofo and will lead to unstable behavior.
=> ref: disable lipsync by default

modules/xmpp/XmppConnection.js
The 'searchParams' are not implemented on react-native.
=> fix(XmppConnection): use 'search' instead of 'searchParams'

modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js, modules/xmpp/JingleSessionPC.js
Enabled desktop sharing and discontinued support for Safari versions prior to 12.1, i.e., the ones with no VP8 support.
Get rid of isSafariWithWebrtc() and isSafariWithVP8() checks, only check for Safari >= 12.1
=> feat(Safari): Add unified plan support for Safari

doc/e2ee.md
adds a document describing the high-level design of the current e2ee approach
(straight from gdocs)
=> e2ee: add high-level docs

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, package-lock.json, package.json
Get rid of the experimental flag for simulcast support, update js-utils for detecting Edge on Android
=> fix(Firefox): Enable simulcast support on Firefox

modules/xmpp/xmpp.js
If user experiences any failed reconnect during the entire session, even if followed by a success, then the "connectionFailed" flag will trigger JitsiConnectionEvents.CONNECTION_FAILED on hang up while processing the disconnected transition.
=> fix(xmpp): clear any last strophe errors on reconnect

modules/xmpp/strophe.jingle.js
If ICE config object gets modified while there's any native
PeerConnection instance holding a reference, it will cause
an exception about final object being modified.
It happens when trying to reconnect XMPP Websocket on RN and
is caused by the fact that new TURN config is fetched after
the connection is re-established.
=> fix(strophe.jingle.js): exception on ICE config modification

modules/e2ee/E2EEContext.js
This handles decryption errors for audio differently than the
current version. Instead of forwarding horrible noise to the decoder,
replace the bytes with magic opus bytes for silence:
```
0xd8fffe
```
Those bytes were captured on a modified version of
https://webrtc.github.io/samples/src/content/peerconnection/endtoend-encryption/
with more dumping and after disabling the track.
=> e2ee: generate silence in case of audio decryption errors

modules/xmpp/XmppConnection.js
This code fixes a problem we get, when our url of service contains 'ws' symbols inside domain name. Our service url looks like 'wss://vs.myws.com' - In this case keep-alive will fail because of incorrect replace: 'https://vs.myhttp.com'. This pull request should fix this problem.
=> Fix protocol replace for websocket keep-alive

modules/RTC/JitsiLocalTrack.js, modules/RTC/RTCUtils.js
MediaStreamTrack getConstraints on Safari returns an empty object.
Enable device selection on Safari.
=> fix(safari): construct track constraints from getSettings

JitsiConference.js, modules/RTC/RTC.js
also enables e2ee on peer-to-peer connections. While a bit unnecessary
it avoids the confusing UX of things working until a third person joins
=> e2ee: also enable on p2p connections

modules/e2ee/E2EEContext.js
Reverts #1098, that strategy does not work. When switching from garbage to non-garbage the decoder would decode subsequent packets based on the wrong keyframe.
=> e2ee: drop video on decode errors

modules/e2ee/E2EEContext.js
If we are encrypting and the key index from a (potentially unencrypted)
frame exceeds our key ring size (1 currently) drop the frame.
This is a heuristic. We currently don't have the signaling for whether a
remote end does encrypt its frames or not.
=> e2ee: don't pass plain frames to decoder if we are encrypting

JitsiConference.js, doc/API.md, modules/RTC/JitsiLocalTrack.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
For simulcast case, enable the stream encodings that have a resolution <= user setting.
For non-simulcast case, use applyConstraints to change the resolution of the stream.
This currently doesn't work on FF in the simulcast case 
https://bugzilla.mozilla.org/show_bug.cgi?id=1401592 is implementation bug for bringing RTCRtpParameters/setParameters/getParameters up to spec. I will open a new bug for this specific case and update it here.
=> feat(video-quality): control the sender resolution based on video quality settings

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
MediaStreamTrack.getSettings is not implemented.
=> feat(video-quality): fix for mobile

modules/e2ee/E2EEContext.js, modules/e2ee/Worker.js
Mobile breaks otherwise, since creating those types of URLs are supported.
=> e2ee: lazily create the worker URL

modules/xmpp/SDP.js
removes two unused methods for mangling SDP.
=> sdp: remove remove(Session|Media)Lines

JitsiConference.js, modules/xmpp/JingleSessionPC.js
Audio fails on Safari when we try to re-use audio m-lines whose direction has been set to 'inactive'
when the remote source left the conference.
Disable noisy mic detection on Safari as this causes audio input to fail on Safari on iPadOS
=> fix(safari): Do not reuse inactive m-lines

modules/proxyconnection/ProxyConnectionPC.js
...to prevent a crash. The functionality that depends on it
is not required by ProxyConnectionPC.
=> fix(ProxyConnectionPC): shim JitsiConference.on method

modules/connectivity/IceFailedNotification.js, modules/xmpp/JingleSessionPC.js
Switches from using JitsiConference.isJvbConnectionInterrupted flag to peerconnection's ICE state. The interrupted flag is not set if the connection fails initially.
=> fix(ice-failed): initial ICE failure

JitsiConference.js, modules/RTC/JitsiLocalTrack.js
Make sure we inject the encoding function on RTCRtpsenders when tracks are replaced on the peerconnection.
Update the MediaStreamTrack on the JitsiLocalTrack when effects are applied or removed so that
we can find the RTCRtpSender using the MediaStreamTrack
=> fix(E2EE): Apply E2EE on RTCRtpSender when track is replaced on pc

JitsiConference.js, JitsiConferenceErrors.js
Adds ICE_FAILED event emitted when ICE fails and disables it by default.
The reason for that it's currently causing issues with signaling when
Octo is enabled. Also when we do an "ICE restart"(which is not a real
ICE restart), the client maintains the TCC sequence number counter, but
the bridge resets it. The bridge sends media packets with TCC sequence
numbers starting from 0.
The 'enableIceRestart' config option can be used to force it, but it's
not recommended.
=> ref: disable ICE restart by default

karma.conf.js, modules/xmpp/SDP.spec.js
follow-up from #1146. Very high level but this should cover the relevant code paths.
The jingle offer was taken from a current focus offer with a few bits removed:
* ssrc-info element
* web-socket element inside transport
* rtcp-mux element inside transport
* bridge-session element
* bundle element (removed in focus already)
=> test: add a test for jingle to sdp conversion

modules/RTC/TraceablePeerConnection.js
This will make sure we get 30 fps for screenshare on p2p connections
=> fix(screenshare): Add google conference flag only when simulcast is on

doc/e2ee.md, modules/e2ee/Worker.js
derived from the participant id in addition to the salt, separated by a null
byte to avoid ambiguity attacks along the lines of
(someRoom, someParticipant)
(someRoo, mSomeParticipant)
=> e2ee: derive per-participant keys

modules/xmpp/SDP.js
removes the SDES mapping. This is a leftover of the time when
Chrome only supported SDES and shouldn't be required anymore.
=> sdp: remove SDES mapping

JitsiConference.js
Pending constraints were not getting applied on a p2p connection when the settings were changed before joining a p2p call.
=> fix(video-quality): Apply pending video constraints on p2p originator

modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/xmpp/xmpp.js
Add RFC 4588 to the list of advertised features on Firefox.
Use RtxModifier only for cases when simulcast is achieved through SDP munging
This will ensure that RTX is negotiated whenever it is offered by the browser.
=> fix(Firefox): Enable RTX support on Firefox

modules/RTC/JitsiLocalTrack.js, modules/RTC/TraceablePeerConnection.js
This behavior got altered when we correctly update the reference we keep of MediaStreamTrack in JitsiLocalTrack when effects are applied as part of https://github.com/jitsi/lib-jitsi-meet/commit/805eb938ae431cf71d67234fafaa35ae47be6308.
Apply max bitrates only when desktop track is added.
=> fix(presenter): change the max bitrate to 2.5 Mbps when presenter is enabled

JitsiConference.js, JitsiConferenceErrors.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.js, modules/xmpp/ChatRoom.js, modules/xmpp/ChatRoom.spec.js, modules/xmpp/Lobby.js, modules/xmpp/xmpp.js, service/xmpp/XMPPEvents.js
Overview:
1. Let's start with how is backend activated/configured:
```
VirtualHost "jitmeet.example.com"
modules_enabled = {
"muc_lobby_rooms"
}
lobby_muc = "lobby.jitmeet.example.com"
main_muc = "conference.jitmeet.example.com"
Component "lobbyrooms.jitmeet.example.com" "muc"
storage = "memory"
muc_room_cache_size = 1000
restrict_room_creation = true
muc_room_locking = false
muc_room_default_public_jids = true
```
The lobby rooms muc component is a separate one, on which rooms can be created only by admins.
2. When a moderator enables lobby feature, just changes the muc config to be set to members_only https://xmpp.org/extensions/xep-0045.html#enter-members
Also a shared password can be used by adding it as `muc#roomconfig_lobbypassword`.
What happens in the prosody module is that when …
=> Initial implementation of lobby rooms.

JitsiConference.js
VAD processing causes audio input to fail on devices running latest versions of iOS/iPadOS.
=> fix(safari): Disable VAD processing on Safari

doc/tokens.md
There was inconsistent the example `Payload` and the documentation of the
fields shown in the `tokens.md` file. I added the `email` field to the list of
attributes accepted for the `user`
=> Add the missing description of the email field for user context

modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js
We switched to using replaceTrack for Firefox and Safari in the unified-plan rewrite
=> cleanup: remove code no longer used in unified-plan mode

modules/xmpp/moderator.js
Pass a value for Opus' maxaveragebitrate parameter to Jicofo iff opusMaxAvgBitrate is set as configuration option.
Depends on https://github.com/jitsi/jicofo/pull/551
=> Add preferred audio bitrate to createConferenceIq

JitsiConference.js, JitsiConferenceEvents.js, modules/RTC/MockClasses.js, modules/qualitycontrol/QualityController.js, modules/xmpp/JingleSession.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/JingleSessionPC.spec.js, modules/xmpp/MediaSessionEvents.js, modules/xmpp/MockClasses.js, modules/xmpp/XmppConnection.spec.js
Refactors the way send/receive video constraints are managed and puts the high level
logic in a separate module. See QualityController.js for high level overview on how
the constraints are managed now.
Adds events to JitsiConference fired whenever it starts new jvb/p2p session.
Adds event to JingleSessionPC.js when remote party signals receive max frame height.
Also adds signaling of the local recv preference for the p2p mode(only existed for JVB).
=> ref/feat: add QualityController

JitsiMeetJS.js, JitsiTrackError.js, JitsiTrackErrors.js, doc/API.md, doc/example/example.js, modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js
- Use getDisplayMedia on browsers where it is supported.
- desktopSharingChromeDisabled and desktopSharingFirefoxDisabled will no longer be supported.
=> Remove screenshare extension support

modules/RTC/TraceablePeerConnection.js, modules/proxyconnection/ProxyConnectionPC.js, modules/qualitycontrol/QualityController.js, modules/xmpp/JingleSessionPC.js
- Use 'maintain-framerate' for camera tracks and 'maintain-resolution' for desktop tracks.
- Apply cached video constraints/preferences on video unmute. Since the sender encodings are available only after the renegotiation is complete (on chrome/safari), constraints/preferences have to be applied after renegotiation is complete
=> feat: Set degradation preference on video senders

JitsiConference.js, modules/xmpp/ChatRoom.js
Used for extending owner privileges to other participants in the chat room.
=> feat: add granting owner support

modules/browser/BrowserCapabilities.js
Fix for https://github.com/jitsi/jitsi-meet/issues/7241
User interaction is not needed anymore on Safari for unmuting audio/video. 
This issue manifests only on iframe users on Safari.
=> fix: IFrame users on Safari start audio/video muted

modules/RTC/RTCUtils.js, package.json
Override the constraints on Safari because of the following webkit bug.
https://bugs.webkit.org/show_bug.cgi?id=210932
Camera doesn't start on older macOS versions if min/max constraints are specified.
=> fix(safari): override min/max video constraints on safari

modules/RTC/TraceablePeerConnection.js
When the sender resolution is changed on a p2p connection as a result of the receiver constraint change, do not specify the aspect ratio while restarting the video track with the new resolution. We are leaving it to the camera to pick up the best aspect ratio for a given resolution.
=> fix: let camera pick the best aspect ratio when applying sender video contraints

JitsiConference.js
With the introduction of lobby the ChatRoom KICKED event is now also emitted for
ourselves (the kicker) so we want to avoid emitting an event where `undefined`
kicked someone.
=> fix(JitsiConference): skip participant kicked event for kicker

package-lock.json, package.json
Updates strophejs-plugin-stream-management
to 001cf02bef2357234e1ac5d163611b4d60bf2b6a which fixes
few corner cases around XMPP WebSocket reconnect logic.
https://github.com/jitsi/strophejs-plugin-stream-management/pull/8
=> deps: update plugin-stream-management

modules/xmpp/StropheLastSuccess.js, modules/xmpp/XmppConnection.js
An 'item-not-found' or other error on Websocket reconnect will refresh the timestamp which will give misleading information about when the last stanza was received.
=> fix(StropheLastSuccess): refresh the timestamp in connected

modules/RTC/JitsiTrack.js, modules/statistics/RTPStatsCollector.js
The audio levels reported on the audio receivers are lower when compared to the value reported by getStats.
Values reported by getStats on chrome do not follow the the spec and since we have combination of clients using both getStats and getSynchronizationSources, let's stick to one scale to make them look uniform.
Also, the receivers seem to be reporting audio level for a little bit after the remote user has muted. Make sure the track is unmuted before setting the audio level on the track.
=> fix: Scale remote audio levels reported on receiver to getStats levels

JitsiConference.js, modules/browser/BrowserCapabilities.js, modules/statistics/PerformanceObserverStats.js, modules/statistics/PerformanceObserverStats.spec.js, modules/statistics/statistics.js, modules/util/MathUtil.js, modules/util/MathUtil.spec.js, service/statistics/Events.js
Add a performance stat around long tasks. Chrome supports PerformanceObserver API that lets us
register for long tasks event. Any task that takes longer than 50ms is considered a long task.
=> feat: PerformanceObserverStats initial commit

modules/RTC/TPCUtils.js
When the client starts video muted and the track is later added, make sure we construct the simulcast stream constraints then.
=> fix(video-quality): add missing simulcast stream constraints

JitsiConference.js, JitsiConnection.js, modules/xmpp/xmpp.js
In cases where there is no room like pre-join and lobby screen we still want to be able to debug xmpp messages.
=> ref: Moves xmpp logs to be accessed from connection.

modules/RTC/TraceablePeerConnection.js
When disableSimulcast=true the Lib tries to scale-down the local-video track to match `config.resolution`.
If the local-video track is already slower than config.resolution it results in `scaleResolutionDownBy=0` which ist not a valid scaling value.
---
_CLA already signed, see https://github.com/jitsi/lib-jitsi-meet/pull/1156_
=> Fix: Scale down localVideo which is already smaller than req resulition

modules/xmpp/JingleSessionPC.js, service/xmpp/XMPPEvents.js
This event is not used anywhere and doesn't make sense with unified.
=> ref(XMPPEvents): remove PEERCONNECTION_READY

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
The first commit removes the logic which was setting 'encoding.active' flag without taking current sender video constraints into consideration. This leaves p2p in unified (not currently enabled) possibly in a broken state in some corner cases, but it makes other changes needed now easier to be done.
The second commit fixes an issue where setting 'sendrecv' on the 'recvonly' transceivers for remote video would cause endless renegotiate loop.
=> Refactor around unified media transfer active logic

karma.conf.js, modules/RTC/TraceablePeerConnection.js, modules/qualitycontrol/QualityController.js, modules/qualitycontrol/QualityController.spec.js, package-lock.json, package.json, webpack.config.js
Will stop sending video when `setSenderVideoConstraint` is called with `0`. The bridge is supposed to signal this value when participant's video is not displayed.
This PR depends on the functionality added in https://github.com/jitsi/jitsi-videobridge/pull/1381 but can land independently.
=> Feat: stop sending video

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
Configure the encodings on FF after the track is added in the p2p case.
Do not add/remove video tracks from TPC for unmute/mute case on Safari.
Only add/remove the tracks from the peerconnection so that the camera led turns off on mute
=> Fix unified p2p

JitsiMediaDevices.js, modules/RTC/RTCUtils.js
This error happens in getCurrentlyAvailableMediaDevices. I got this error in my sentry error tracking many times for multiple users. I think this will fix it (reason below).
```console
TypeError: Cannot read property 'find' of undefined
```
in
```javascript
{snip} .a.DESKTOP){const t=y.a.getCurrentlyAvailableMediaDevices().find(t=>t.kind===`${e.getTrack().kind}input`&&t.label===e.getTrack().label);t&&F {snip}
```
I've reverse engineered it and found out that if `this.isDeviceListAvailable()` is not `true` the variable is never set to something else than `undefined`. But the jsdoc description of `getCurrentlyAvailableMediaDevices` says that it will return an empty array which currently seems not to be true:
```javascript
/**
* Returns list of available media devices if its obtained, …
```
=> fix(RTCUtils): Cannot read property 'find' of undefined

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
Make sure the LD stream is enabled even when requested resolution is lower.
This should fix the case when camera is started with 1080p and LD simulcast stream's resolution is 270p but the requested resolution is 180.
Do not negotiate H264 for p2p connections when E2EE is enabled.
=> Fix sender constraints for camera started with resolutions > 720p

JitsiConference.js, modules/statistics/statistics.js, modules/util/MathUtil.js
A new config.js setting `testing->callStatsThreshold` is introduced that determines the % of conferences on which callStats will be enabled. It takes a value between 0 and 100.
=> feat(stats): Add the ability to enable callStats only on a certain % of users

modules/browser/BrowserCapabilities.js
Since we use transferable streams to transfer the streams to the worker
we need to feature detect them as Chrome 86 will launch Insertable Streams
by default without shipping transferable streams yet (status still unclear,
it might still ship too)
See here for the feature detection used:
https://groups.google.com/a/chromium.org/g/blink-dev/c/1LStSgBt6AM/m/hj0odB8pCAAJ
=> e2ee: detect transferable streams

JitsiConference.js
This way we make sure that we don't overshoot the threshold set in config.js
=> fix(callstats): Go back to enabling callstats on % of users rather than % of conferences.

doc/e2ee.md, modules/e2ee/E2EEContext.js, modules/e2ee/Worker.js
following
https://tools.ietf.org/html/draft-omara-sframe-00
but putting the frame metadata into a trailer instead of a header.
We call this JFrame.
Also the key we get from OLM is high entropy so we do not need
to use PBKDF2 but can use HKDF instead. See
https://wiki.developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey#HKDF
=> e2ee: use CTR instead of GCM

doc/API.md
When `kick()` is used for kicking out a user from the conference, the following runtime error is thrown.
```
TypeError: room.kick() is not a function.
```
The method for kicking out a user is mentioned in the docs as `kick()`, but *it should be `kickParticipant()`*.   
This PR fixes that error in the doc/API.md.
=> fixed incorrect kick() with kickParticipant() in doc/API.md

doc/e2ee.md, modules/e2ee/E2EEContext.js, modules/e2ee/E2EEncryption.js, modules/e2ee/OlmAdapter.js, modules/e2ee/Worker.js
similar to what is explained here:
https://tools.ietf.org/html/draft-omara-sframe-00#section-4.3.5.1
but we do it on authentication tag failures since it is not possible
to tell whether decrypt.
=>  e2ee: ratchet the key forward on authentication tag errors

modules/xmpp/xmpp.js
Disable RTX on FF as we are seeing video freezes on FF80 and later - https://bugzilla.mozilla.org/show_bug.cgi?id=1668028
=> fix: Disable RTX on Firefox.

modules/e2ee/Context.js, modules/e2ee/Context.spec.js
Both for just encode function as well as an end-to-end test.
=> e2ee: add unit tests

modules/RTC/ScreenObtainer.js
Both of the cases where user clicks cancel and when screen recording
permissions were not granted at the OS level are almost the same,
except for a small difference in the error.message.
This was only tested on Chrome 85.0.4183.121/Mac OS 10.15.6
=> faet(ScreenObtainer): detect lack of permissions

doc/e2ee.md, modules/e2ee/Context.js
this uses the full four bits in the wire format. The wire format
looses the (currently not implemented) extensibility with variable
length keys.
=> e2ee: sync key ring size and packet format

modules/RTC/RTCUtils.js
Device IDs can change without triggering any event. In order to sync the
device IDs that  we store with the actual device IDs, we need to update
them every time when we call enumerate devices.
=> fix(updateDevices): On enumerateDevices.

modules/RTC/TraceablePeerConnection.js
In Chrome, if 'maxBitratesVideo' options are specified and 'capScreenshareBitrate' is disabled, then simulcast is enabled
for screenshare. Chrome in plan B, does not send screen stream if 'maxBitrate' are set and simulcast is enabled.
=> fix(TPC): maxBitratesVideo break screenshare

JitsiConference.js
Also return early to avoid weird errors if the initialization step fails.
Everything is broken at that stage pretty much.
=> fix(JingleSession) log initialization error

doc/API.md
After using lib-jitsi-meet fairly well, I realized there is no way for us to set a custom property on the local user other than the display name. So, I went on a search and found on the jitsi community that we have `setLocalParticipantProperty` and `PARTICIPANT_PROPERTY_CHANGED` that are not given in the official documentation at [API.md](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/API.md). Knowing that these options are there helped me a lot in writing new features and I think there are others like me who might be using lib-jitsi-meet and don't know about these. So, I decided to add them in the docs.
=> docs for setLocalParticipantProperty, PARTICIPANT_PROPERTY_CHANGED added.

modules/RTC/RTC.js, modules/RTC/RTCUtils.js, modules/RTC/TraceablePeerConnection.js
Add the conference flag back since the bridge is now able to handle the case where more than 1 temporal layers are received even when only 1 SSRC is signaled.
Do not disable encodings when sender constraints are not configured for the conference. Fixes #1333 in applications that use lib-jitsi-meet and do not have layer suspension enabled.
=> Add google conference flag for screensharing

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
In p2p mode, 'scaleResolutionDownBy' is used for downscaling a stream when needed, i.e. when the user receives a receive constraint of 360p because the other participant is in tile view. When desktop share is started, the encoding config has to be scaled back up so that the other participant starts receiving HD resolution for the share as desktop shares are autopinned.
Therefore, encodings have to be enabled/disabled for desktop shares as well. Earlier it was done only for camera tracks.
=> fix(video-quality): Fix p2p desktop share quality.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
On every call to RTCRtpSender.setParameters(), ensure that the resolution configured for the encoding matches that of the value configured on the RTCRtpSender when the source was added to the peerconnection. This should prevent us from overriding the default values if the browser returns erroneous values when RTCRtpSender.getParameters is used for getting the encodings info. 
This fixes the issue on recent versions of Safari where the 'scaleResolutionDownBy' value comes back as 1 for all encodings even though the encoding resolution is different from the stream capture resolution.
Fixes https://github.com/jitsi/jitsi-meet/issues/7953.
Here is a snapshot of the encodings when simulcast is enabled, the scaleResolutionDownBy value should be 4, 2 and 1  for LD, SD and HD streams respectively.
=> fix(TPC): Ensure encodings resolutions match configured values.

modules/xmpp/moderator.js
The plan is to move the lastNLimits logic to bridge. The clients will be able to override(lower) the bridge limits through the bridge channel only. Also, this lets us configure last-n per receiver and not set the last-n value for the whole conference the way Jicofo sets it currently.
=> fix(last-n): Do not let Jicofo initialize last-n for the whole conference.

JitsiConference.js
Only one audio or video track is correctly supported by lib-jitsi-meet. This is an attempt to mitigate an issue reported by the community where the user's audio is played in the conference even though the UI shows the user as muted.
Can be reproduced by executing this script in the command line:
`JitsiMeetJS.createLocalTracks({ devices: ['audio']}).then(track => { APP.conference._room.addTrack(track[0])});`
=> ref(JitsiConference): allow only 1 track per media type

modules/RTC/RTCUtils.js
Hi,
I noticed some weird behavior related to the array received by `DEVICE_LIST_CHANGED` events.
This PR solves the issue of sending/receiving an empty array when dealing with the data in an asynchronous way.
More info on https://community.jitsi.org/t/lib-jitsi-meet-wrong-use-of-splice/86268
=> fix : devicesReceived array should not be modified

modules/xmpp/strophe.ping.js
Due to no timeout value passed the disconnection was not detected.
=> fix: Fixes ping options usage.

JitsiConference.js, JitsiConferenceEventManager.js
There are cases where we start p2p on the first participant received presence, where there are more presences coming. This starts the process of p2p resulting and few iq errors while terminating it quickly after starting it.
On a normal joining as third participant we see around 38 send or received iq messages, in the problem scenario we see 60.
=> fix: Maybe start p2p only when we have received all presences.

modules/RTC/TraceablePeerConnection.js, modules/xmpp/SDP.js
in order to not match a=msid-somethingelse, a=ridiculous and similar
=> sdp: add missing colon to findLines calls

modules/xmpp/SDP.js
which should include the colon in order not to match something like
a=simulcast-is-cool
=> sdp: improve sdp matching for simulcast lines

modules/xmpp/Lobby.js
The jid received is the main jid in internal representation with [tenant]roomname@domain.com and we cannot compare it directly to roomname@conference.tenant.domain.com.
=> fix: Disabling lobby when using tenant.

modules/xmpp/JingleSessionPC.js
After ICE failure and subsequent recovery of the media connection to the bridge using session-terminate, the local connection status needs to updated when ICE connection is established on the new peerconnection. The local connectivity status will be shown as Lost otherwise.
=> fix: Restore local connection status.

modules/xmpp/JingleSessionPC.js
RN doesn't support RTCRtpSender yet. Therefore, media is suspended on RN by changing the media direction in the SDP whenever the client receives an ideal height of 0 for sender constraints on the bridge channel.
=> feat: Implement aggresive layer suspension on RN.

modules/detection/VADAudioAnalyser.js
On Firefox it throws:
DOMException: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
=> fix VADAudioAnalyser: catch error

JitsiConference.js, JitsiConferenceErrors.js, JitsiConferenceEventManager.js, modules/connectivity/IceFailedHandling.js, modules/xmpp/JingleSessionPC.js, service/xmpp/XMPPEvents.js
Force the client to reload when the bridge that is handling the media goes down.
This mitigates issues seen on the bridge because of a client re-joining the call with the same endpointId, BWE issues, etc.
This behavior is configurable through 'enableForcedReload' setting in config.js.
=> fix(ice-restart): Force client reloads when call is migrated.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
The new format will be
```
maxBitratesVideo: {
//          VP8 : {
//              low: 200000,
//              standard: 500000,
//              high: 1500000
//          },
//          VP9: {
//              low: 100000,
//              standard: 300000,
//              high:  1200000
//          }
//    },
```
The old format will also be acceptable and the same values will be applied on client irrespective of the preferred codec type.
=> Add the ability to configure max. bitrates for VP9

JitsiMediaDevices.js
Not upadting the permissions from the Permissions API call on init is
causing the permissions cache to be filled from GUM resolve/reject logic
only when there aren't any permissions updates. This  may
lead to unknown permission status when we can report  the correct
status from the initial permission API request.
=> fix(GUM-permissions): cache permissions on init.

modules/RTC/BridgeChannel.js, modules/RTC/RTC.js, modules/qualitycontrol/ReceiveVideoController.js
Translate the 'LastNChangedEvent', 'SelectedEndpointsChangedEvent' and 'ReceiverVideoConstraint' messages into the new 'ReceiverVideoConstraints' message that invokes the new bandwidth allocation algorithm in the bridge that is described here - https://github.com/jitsi/jitsi-videobridge/blob/master/doc/allocation.md. useNewBandwidthAllocationStrategy=true in config.js will invoke the translation in the client.
=> feat: Use the new bridge signaling format.

JitsiMediaDevicesEvents.js, JitsiMeetJS.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js
Fire PERMISSION_PROMPT_IS_SHOWN when none of the devices have a label
Fire a new SLOW_GET_USER_MEDIA event if the timeout for getUserMedia is exceeded
Update JitsiMeetJS.createLocalTracks to include the options for firing the above events
in the provided options argument. Deprecate the firePermissionPromptIsShownEvent flag in
method's signature
=> fix(gum) update permissions prompt detection

modules/e2ee/Context.js
- After ratchet do not set it as new key for current index. Set it to correct position in crypto ring.
=> fix: e2ee context ratchetting

modules/e2ee/Context.js
When E2EE is disabled we just set the last key to `false`. When decoding we
need to check if the last key is not false, otherwise we might try to decrypt
the unencrypted video frames, thus resulting in breakage.
=> fix(e2ee) fix disabling E2EE

JitsiConference.js, JitsiConferenceEventManager.js, modules/RTC/RTC.js, modules/xmpp/ChatRoom.js, modules/xmpp/strophe.emuc.js, service/statistics/AnalyticsEvents.js, service/xmpp/XMPPEvents.js
This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.
This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630
=> Added mute video moderation feature

modules/RTC/TraceablePeerConnection.js
When a second remote track of the same mediatype is received for an endpoint, remove the existing track before creating the new remote track.
Ideally, when a remote endpoint changes source, like switching devices, it sends a source-remove (for old ssrc) followed by a source-add (for new ssrc) and Jicofo then should forward these two messages to all the other endpoints in the conference in the same order. However, sometimes, these messages arrive at the client in the reverse order resulting in two remote tracks (of same media type) being created and in case of video, a black strip (that of the first track which has ended) appears over the live track obscuring it. Removing the existing track when that happens will fix this issue.
=> fix(TPC): Remove the existing track instead of overwriting.

JitsiConference.js
Do not add the muted audio/video tracks to the peerconnection on join. The tracks will be added when the user unmutes for the first time. This reduces the number of remote sources that will be added when a participant joins a large call where everyone joins muted (startAudioMuted/startVideoMuted setting).
=> fix(conference): Do not signal muted tracks on join.

modules/browser/BrowserCapabilities.js
Chrome iOS uses WebKit engine so it uses the Unified Plan. Fixes #1480.
=> Use unified plan for Chrome iOS

JitsiConference.js, modules/RTC/RTCUtils.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js
Apple added getUserMedia support for WkWebview based browsers like chrome and Firefox on iOS 14.3. These browsers behave as Safari does on iOS. Therefore, extend the Safari checks to these webkit based browsers as well.
=> feat(browser-support): Add support for WKWebview based browsers.

JitsiConferenceEventManager.js, modules/RTC/BridgeChannel.js
The bridge now sends the list of previous speakers in addition to the dominant speaker in the `DominantSpeakerEndpointChangeEvent` message.
=> feat(dominantSpeaker): Add previous speaker list.

JitsiConference.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/util/AsyncQueue.js, modules/xmpp/JingleSessionPC.js
Add try catch when executing the task in modificationQueue. This should prevent the queue for being blocked if the  task throws an exception.
Add more logging around the modificationQueue in order to be able to debug reports for blocked queue.
=> fix(modificationQueue): error handling & logs

JitsiConference.js, modules/qualitycontrol/ReceiveVideoController.js
Add the ability to send the bridge messages for the receiver video constraints in the new format directly. Applications that use lib-jitsi-meet can directly use this new format for implementing different UI layouts.
=> feat(ReceiveVideoController): Add the ability to send constraints in the new format.

JitsiConference.js, modules/RTC/RTC.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
Remove the ssrcs (associated with remote sources) from the remote desc along with the removal of the remote tracks when an endpoint leaves the call. The source-remove signaling message from Jicofo will no longer be needed in this case and can be dropped by Jicofo.
Properly configure degradation preference on RTCRtpSendParameters instead of RTCRtpEncodingParameters. Fixes #1510.
=> Remove ssrcs on leave

modules/xmpp/StropheLastSuccess.js, modules/xmpp/XmppConnection.js, modules/xmpp/xmpp.js
Parse the raw input from xmpp websocket for a failure on auth with jwt and emits the parsed message to consumers.
@saghul @hristoterezov @damencho
=> Send error message on auth failed with invalid jwt

modules/xmpp/ChatRoom.js
We want to push this to the mobile clients, so they will act correctly when we start dropping that part from the presence, as mobile updates take time.
The idea is that in big meetings most of the people will be muted from the beginning and their join presence will miss the muted part. That will limit the size of the presence packages.
=> feat: Consider absence of A/V muted from presence as muted.

JitsiConferenceEventManager.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js, modules/statistics/constants.js, modules/statistics/statistics.js
Capture the audio levels only for the top 5 speakers as RTCRtpReceiver#getSynchronizationSources can be expensive when we have too many audio receivers in the call.
Also, capture the audio levels for track that are unmuted if RTCRtpReceiver#getSynchronizationSources is not supported.
Switch Safari to using getStats since its reporting errorneous values, i.e., 0.000001 as audio level for all remote audio tracks.
=> feat(stats): Get audio levels for the top 5 speakers only.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.js, modules/RTC/BridgeChannel.js, modules/RTC/RTC.js, modules/connectivity/ConnectionQuality.js, service/RTC/RTCEvents.js
Use the new Colibri message "EndpointStats" for broadcasting the local stats. The bridge then will be able to filter the endpoint stats and send them only to the interested parties instead of broadcasting it to all the endpoints in the call.
=> feat(stats): Add a new bridge message "EndpointStats" for stats.

modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/xmpp/JingleSessionPC.js
Make sure the codec order is munged on all the m-lines for unified plan clients. Implement the logic for setting the preferences through RTCRtpTransceiver#setCodecPreferences.
The reason why this wasn't a problem until now is that we don't set any codec other than VP8 as preferred codec for Firefox/Safari. Jicofo in our deployments only offers VP8 and VP9 (more recently), Safari doesn't have support for VP9 and we disabled VP9 on FF because of a known FF bug.
Tested this logic on FF/Safari by modifying Jicofo to offer H.264.
=> fix(codec-selection): Fix codec selection for unified plan browsers.

JitsiConference.js, modules/xmpp/ChatRoom.js
Minimize the size of the initial presence. 
In the future, we can continue optimizing and totally skip the default values instead of setting those, but that needs a bigger refactor. For now it optimizes the initial presence which seems most critical in big conferences.
But overall the other optimization is dropping the namespace which is also some gain to reduce size.
We want to proceed with one cycle of updating environments before merging this, so we can give time to mobile update with the change of having the missing presence tags to be considered as muted (video type missing is already handled and in current mobile clients) as mobile may show some web participants as unmuted while those are actually muted and presence misses the a/v muted tags.
=> Update presence and skip default values

modules/RTC/JitsiLocalTrack.js, modules/RTC/TraceablePeerConnection.js
Remove the effect instead of stopping it so that the original stream is restored on both the local track and on the peerconnection. Fixes issues when a stream with effect applied is replaced on the pc after it is muted, also fixes https://github.com/jitsi/lib-jitsi-meet/issues/1537.
=> fix(RTC): Remove stream effect before disposing the track.

modules/xmpp/JingleSessionPC.js
This will reduce the numbers of transport-info IQs sent by the client.
=> fix(JingleSession): Increase the ICE candidate gathering timeout to 150ms.

modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js
It turns out that if 5 fps is set on the track constraints,
Chrome will capture the original video in 30 fps and only
further down the pipeline will downsample it to 5 fps.
This results in very high CPU usage. Specify max FPS in
getDisplayMedia to fix the problem.
Getting rid of track.applyConstraints should also fix another
issue on Firefox where it reports 0x0 screen size after this call.
=> fix: high CPU on Chrome with low fps screen sharing

modules/RTC/RTCUtils.js, modules/xmpp/JingleSessionPC.js
Disable simulcast for low fps screenshare and enable it for high fps screenshare. testing.capScreenshareBitrate config.js setting has now been deprecated.
=> fix(screenshare): Disable SS simulcast based on fps requested.

modules/RTC/RTCUtils.js
Fixes https://github.com/jitsi/lib-jitsi-meet/issues/1571.
=> fix(RTC): Specify default width of 1280px for video.

modules/qualitycontrol/ReceiveVideoController.js
Use the new receiver constraints unless it is explicitly disabled through config.js.
=> fix(quality-control): Switch to new receiver constraints by default.

modules/RTC/TraceablePeerConnection.js, modules/statistics/RTPStatsCollector.js
Switch to returning a Promise for getStats. Reset frame rate stat to 0 when video is suspended as a result of endpoint falling out of last-n.
=> fix(stats): Return promise for getStats.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
Do not try to configure encodings on the sender until they are available. This fixes an issue on Chrome (running in unified-plan mode) where unmuting the local source throws a 'Read-only field modified in setParameters()' error.
=> fix(TPC): Use addTrack instead of addStream in Unified-plan impl.

modules/RTC/ScreenObtainer.js
On Screenshare with Audio the constraint is 
```js
"audio": {
"optional": {},
"mandatory": {
"chromeMediaSource": "desktop"
}
},
```
Electron complains with `Failed to execute 'getUserMedia' on 'MediaDevices': The object must have a callable @@iterator property.` cause of empty optional object.
=> Fix: Screenshare with Audio broken

modules/sdp/SDP.js, modules/xmpp/JingleSessionPC.js
In certain cases, when RTCPeerconnection#addTrack is used, the browser doesn't produce the streamid in the 'a=msid' line which is being used by Jicofo as a unique identifier for the associated ssrc. Whenever the msid is missing in the local description, generate an ID using the local endpoint id.
=> fix(JingleSession): Add a unique identifier for source on Firefox.

modules/qualitycontrol/ReceiveVideoController.js
If the application is using the new receiver constraints, propagate the height constraint to the p2p session as well.
=> fix(quality-control): Propagate the height constraints to p2p session.

modules/RTC/RTC.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/sdp/SDP.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/strophe.jingle.js
When a msid attribute is missing in the 'a=ssrc' line, use the local endpoint id as an indentifier. Move this generation logic to LocalSdpMunger. Also suppress notifying Jicfo of a ssrc change on Firefox when the change is a result of the media being suspended on the jvb connection.
=> fix(JingleSession): Move the ssrc identifier generation to LocalSdpMunger.

modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js
Get the correct media type when generating the source identifier.
=> fix(TPC): Return default codec if the local sdp is not available.

modules/xmpp/xmpp.js
There is a known issue with Firefox where the BWE gets halved on every renegotiation causing the low upload bitrates from the Firefox clients.
=> fix(caps): Disable TCC on Firefox.

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/sdp/LocalSdpMunger.spec.js, modules/sdp/SampleSdpStrings.js, modules/xmpp/JingleSessionPC.js, package-lock.json, package.json
This fixes the issue where TRACK_REMOVED event is not fired when a remote track is removed from the peerconnection.
Fixes https://github.com/jitsi/lib-jitsi-meet/issues/1612 and https://github.com/jitsi/jitsi-meet/issues/8482.
=> fix(RTC): Set transceiver direction after RTCRtpSender#replaceTrack.

modules/RTC/TPCUtils.js, modules/sdp/LocalSdpMunger.js
Avoid configuring the encodings on chromium immediately after replace track since the encoding params are read-only until the renegotation is done.
=> fix(TPC): Do not configure encodings on chromium immediately after replaceTrack.

JitsiConference.js
When started muted and no tracks are being created and we were muted by focus (av moderation) we need to unmute the channels on the bridge after creating the tracks.
=> fix(moderation): Unmuting after av moderation and no track.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/sdp/SDP.js, modules/sdp/SDPUtil.js, modules/xmpp/JingleSessionPC.js, service/RTC/MediaDirection.js
Introduce an enum for media direction.
For p2p connections, the media direction needs to be adjusted after every source-add/source-remove is processed based on the availability of local sources.
=> Fix media direction p2p

modules/browser/BrowserCapabilities.js, modules/connectivity/ParticipantConnectionStatus.js
Safari does not fire mute/unmute events when the remote end stops/starts sending media.
=> fix(connectivity): Fix video freezes on Safari when ep goes out of last-n

JitsiConference.js, JitsiParticipant.js, modules/xmpp/ChatRoom.js, modules/xmpp/ChatRoom.spec.js
Replaces a participant with the same jwt relevant data into a conference when this is specifically asked on joining the conference.
=> feat(replace-participant): Replace participant with same jwt in the conf

JitsiConference.js, modules/RTC/JitsiTrack.js, modules/RTC/RTC.js
Set the initial video type state to NONE to cover cases when the endpoint joins video muted.
=> fix: Send videoType bridge message for mute/unmute on FF.

modules/RTC/MockClasses.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/sdp/LocalSdpMunger.spec.js, modules/xmpp/JingleSessionPC.js
In unified plan, re-use of m-line (i.e., adding an SSRC, removing it and then adding it back) causes the browser to not render the media on Chrome and Safari. The WebRTC spec is not clear as to how browsers have to behave, this doesn't cause any issues on Firefox. As a workaround, only change the media direction and leave the ssrc in the remote desc. This automatically triggers a 'removetrack' event on the associated MediaStream and the track can be removed from the UI.
Also, add the ability to toggle unified plan on/off for jvb and p2p connections separately.
=> fix(TPC): Do not remove ssrcs from remote desc for p2p.

modules/detection/VADAudioAnalyser.js
The crash occurs every time the audio track is muted/unmuted, if the emitter fails to initialize ("Failed to start VADAudioAnalyser" warning is printed).
@andrei-gavrilescu I'm not sure if it's the right way to fix this. It feels like something more should be taken out of the event chain in case the vad emitter fails to start.
=> fix(VADAudioAnalyser): NPE error evaluating this._vadEmitter.on

modules/xmpp/JingleSessionPC.js
Switch chrome to unified plan by default unless explicitly disabled.
Also, remove the check for ssrc in remote description when adding a ssrc-group from source-add. Jicofo seems to be producing a source-add for a ssrcs that have already been signaled in session-initiate. This happens at random and only in torture tests probably because of a race condition that is hit only through automated tests.
The client throws an exception that the sRD has failed and reloads as a result of this. Leaving in the ssrc-group doesn't seem to cause the browser to throw the exception.
=> Switch chrome to unified plan by default unless explicitly disabled.

modules/RTC/TraceablePeerConnection.js
In unified plan impl, it is not possible to enable/disable simulcast during the call since the same sender is re-used for all local video tracks. Therefore, disable the low resolution simulcast streams for low fps screensharing so that the bridge forwards only the highest resolution stream which is important for low fps screensharing.
=> fix(RTC): In unified-plan mode, disable the low resolution streams for low fps SS.

modules/RTC/CodecSelection.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js
Munge only the m-line that corresponds to the source that the browser will be sending.
Do not select VP9 on Firefox.
Detect support for RTCRtpTransceiver#setCodecPreferences correctly.
=> fix(codec-selection): Fix VP9 codec switching issue in Chrome unified plan.

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
Do not enable unified plan for p2p chrome by default until StartMutedTest is fixed.
Fix media direction for case when there are no local and remote sources, should be set to 'inactive' in that case.
=> fix(JingleSessionPC): Disable unified-plan for p2p chrome.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js
`TpcUtils.ensureCorrectOrderOfSsrcs()` takes into account only the first `ssrs-group`, and it causes missed `ssrs` attributes. It results in an error during `peerconnection.setRemoteDescription()`.
For fixing `ensureCorrectOrderOfSsrcs()`, all `ssrs-group` are traversed and all distinct `ssrs` are preserved with keeping their order.
=> fix: Missed SSRCs in Unified Plan with several "ssrc-group:FID" groups.

modules/xmpp/JingleSessionPC.js
Chrome doesn't create a decoder for ssrc in the remote description when there is no local source and the endpoint is offerer. Initiating a renegotiation with the endpoint as a responder fixes this issue. Add a workaround until Chrome fixes this bug.
Enable unfied plan by default for chrome p2p.
=> Fix start muted p2p

modules/sdp/SDPUtil.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/strophe.jingle.js
Hurts mobile performance. They can still be enabled by setting the level at the
right value (debug / trace).
=> fix(log) lower severity of overly verbose logs

modules/xmpp/JingleSessionPC.js
Hurts mobile performance. They can still be enabled by setting the level at the
right value (debug / trace).
=> fix(log) lower severity of overly verbose logs (2)

JitsiConference.js, modules/RTC/RTC.js, service/RTC/BridgeVideoType.js, service/RTC/VideoType.js
This lets the bridge adjust the bitrate allocation for this source so that layers with higher fps are prioritized over layers with higher resolution.
As a result, endpoints with restricted downlink will receive a high fps low resolution share as opposed to a high resolution low fps screenshare.
=> feat(BridgeChannel): Signal a new videoType for high fps screenshare.

modules/statistics/PrecallTest.js
In response of the comment in #1669
=> fix: respect custom callstats script url for precall test

JitsiConferenceEventManager.js, JitsiConferenceEvents.js
Currently, JSON messages, received through the XMPPEvents.JSON_MESSAGE_RECEIVED internal event, are visible to the API user through the JitsiConferenceEvents.ENDPOINT_MESSAGE_RECEIVED event, but only if the sender of the message has a corresponding JitsiParticipant object; others are ignored with a warning message.
This excludes:
-  messages sent by the local client through `conference.sendMessage`, then automatically broadcast back by the Prosody backend;
- messages that were sent manually by the Prosody backend.
This is a limitation that complicated the design of the polls feature (cf. [this pull request on jitsi-meet](https://github.com/jitsi/jitsi-meet/pull/9166)).
This PR adds a new `JitsiConferenceEvents.NON_PARTICIPANT_MESSAGE_RECEIVED` event, which corresponds to the messages that …
=> feat: Add a new conference event for messages ignored by ENDPOINT_MESSAGE_RECEIVED

modules/connectivity/ConnectionQuality.js
When the user first unmutes their video, the connection quality is shown as poor until the local stats are available.
Calculate the connection quality only after the stats are available, i.e., assume 100% until pcStatsInterval has elapsed.
=> fix(ConnectionQuality): Do not show red/yellow GSM bars on join.

modules/xmpp/AVModeration.js
The prosody toJson returns for empty arrays {} which causes an error initially.
=> fix: Fix av moderation n.filter is not a function.

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
This patch re-enables the detection of ICE connection failures, e.g. if the TURN connection fails in the middle of a call, which is broken since the release of Chrome 76.
=> Workaround for Chrome ice connection failure detection

JitsiConference.js
If audio levels are disabled it's pointless to try and detect problems.
=> fix(JitsiConference) skip AudioOutputProblemDetector on disableAudioLevels

modules/browser/BrowserCapabilities.js, modules/e2ee/E2EEContext.js, modules/e2ee/E2EEncryption.js, modules/e2ee/Worker.js
An alternative to Insertable Streams, currently implemented in Safarii / WebKit.
https://w3c.github.io/webrtc-encoded-transform/
Fixes: https://github.com/jitsi/jitsi-meet/issues/9585
=> feat(e2ee) add support for WebRTC Encoded Transform

JitsiConference.js
Fixes error caused by stop screen sharing call (newTrack is null) and video moderation on (isVideoMutedByFocus is true)
=> fix(replace-track) Add not null check for newTrack

JitsiConference.js, modules/browser/BrowserCapabilities.js
On mobile Safari, if a user joins audio and video muted, the browser doesn't decode the incoming audio. Workaround is to always add the audio track to pc and mute it if needed.
=> fix(browser-support): Add audio track to pc always on mobile Safari.

modules/sdp/LocalSdpMunger.js
... is stopped. If there's any sRD/sLD cycle happening
while the screen sharing stops, the local track
returns muted and it was injecting fake video SSRCs
which results in invalid SSRC description.
At the time when it happens there's error log in jicofo:
"Error adding SSRCs from X"
and the client will get bad-request error in response
to the source-add request.
=> fix(LocalSdpMunger): do not fake video sdp when screen sharing

modules/qualitycontrol/SendVideoController.js
This is needed for screensharing to work as expected on chrome in unified plan.
=> fix(quality) Enable layer suspension by default.

JitsiConference.js
If oldTrack was not previously in the conference this will
lead to a crash in onLocalTrackRemoved where oldTrack doesn't
have `muteHandler` and `audioLevelHandler` listeners defined.
=> ref(JitsiConference): don't crash on wrong oldTrack

JitsiConference.js
This swallows the stack trace.
=> fix(replaceTrack):  Don't wrap Error in Error.

modules/xmpp/xmpp.js
Fixes issue with jibri that are served on different virtual host and jiconop2 does not work for them.
=> fix: Reads shard name and from disco-info if available.

modules/RTC/TraceablePeerConnection.js, modules/sdp/SDP.js
Impose VP9 bitrates only when VP9 is negotiated. If Jicofo doesn't offer VP9 but the client expresses a preference for VP9, VP9 bitrates were being imposed before.
This fixes an issue where the bridge doesn't forward the HD stream from Firefox to other users in the call. The order of the ssrcs produced by the browser is from Highest resolution to lowest whereas the bridge assumes it to be from lowest to highest as is the case with Chrome and Safari.
=> Fix codec renegotiation and reverse the order of the ssrcs being signaled from Firefox to Jicofo.

modules/e2ee/Context.js
For some reason webpack seems to not be transpiling that properly.
Fixes: https://github.com/jitsi/lib-jitsi-meet/issues/1722
=> fix(e2ee) replace nullish coalescing with or

modules/RTC/JitsiLocalTrack.js, modules/xmpp/ChatRoom.js
ChatRoom.setAudioMute and ChatRoom.setVideoMute are not async, so no callbacks nor promises are necessary.
=> ref: sendMuteStatus is not async

JitsiConference.js, modules/xmpp/strophe.emuc.js, modules/xmpp/xmpp.js
If a second JitsiConference instance for the same room is created we were
throwing an error but some listeners were already attached. This commit
makes sure that we throw the error as soon as possible and no listeners
are added.
=> Two JitsiConference instances with the same room name issue

modules/browser/BrowserCapabilities.js
There was an error in the pattern match, everything was included in it. In
addition return a boolean in case we succeed in the UA pattern match, since it's
more correct than returning an array with the match.
=> fix(browser-support) fix detecting iOS browsers correctly

modules/RTC/TraceablePeerConnection.js, modules/sdp/SDP.js, modules/xmpp/xmpp.js
- fix(Jingle): stop reverting the SSRCs from Firefox
- fix(xmpp): disable RTX for Firefox < 93, because it results in random SSRC order
=> Disable RTX for Firefox <= 93

modules/xmpp/strophe.jingle.js
Maybe due to our DOM wrappers, the Symbol.iterator is not implemented, so
iterate over the IQ fields old-school style.
=> fix(loggging) fix exceptions on mobile

JitsiMeetJS.js, modules/flags/FeatureFlags.js, modules/sdp/LocalSdpMunger.js, modules/sdp/LocalSdpMunger.spec.js, modules/sdp/SDP.js, modules/sdp/SDP.spec.js, modules/sdp/SDPDiffer.js, modules/sdp/SDPDiffer.spec.js, modules/sdp/SDPUtil.js, modules/xmpp/strophe.jingle.js
This is the first step in adding support for multiple
streams per endpoint. Each source(stream?) needs to have
an identifier. For now always generate the 0 index name
until the machinery for sending more than 1 stream is put
in place.
=> feat: generates source names

modules/e2ee/E2EEContext.js
When the worker fails to load the logger is calling onerror however jitsi-meet-logger doesn't have a function called onerror, it should be error
=> fix: logger calling wrong function typo

modules/sdp/SDP.js
The issue was caused by incorrect ordering of the mixedmslabel mline.
sdp-interop is expecting that this mline was the first one but in
reality we were placing it last. This was causing the direction of a
user related m line to be sendrecv instead of sendonly. In certain
situation this issue was causing 2 MediaStreamTracks associated with a
single MediaStream/participant.
=> fix(SS): missing.

modules/RTC/JitsiLocalTrack.js, modules/RTC/TraceablePeerConnection.js
This fixes occasional failures of MuteTest.MuteAfterJoinCanShareAndUnmute torture test and also the case on Safari where user stopping the screenshare doesn't stop showing the screensharing indication on the thumbnail.
Its applicable to other browsers as well.
=> fix(TPC) change the tranceiver dir to recvonly when track is removed.

modules/sdp/SDP.js, modules/sdp/SDPUtil.js, modules/sdp/SampleSdpStrings.js
This PR switches to generating sctp-port based SDP.
It also adds support for parsing sctp-port, but can handle
fallback to old-style sctpmap as well.
Fixes: #1778
=> fix(sdp): update data channel to RFC format

modules/browser/BrowserCapabilities.js, modules/xmpp/xmpp.js
RTX in combination with simulcast on Firefox results in bad video quality
therefore we only enable it for version >= 96.
=> fix(xmpp): use RTX with Firefox from 96 on only

modules/sdp/SDP.js
This patch fixes an issue introduced in #1779 by always providing a stream count, because for the XMPP parser the stream count is not optional.
=> Fix sctp streams

modules/e2ee/E2EEContext.js
When loading a web worker inside a blob using importScripts you cannot use a relative path because of CORS issues as it resolves to a blob: path.
Please see: https://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers-loadingscripts
=> fix(e2ee): fix loading web worker when using a relative path inside a blob for the E2EE context

modules/RTC/TraceablePeerConnection.js, modules/xmpp/SignalingLayerImpl.js
This ensures that the source signaling is sent before the mute state is sent in presence. Jicofo relies on mute state from presence to check if the sender limit has been reached.
=> Fix reneg on unmute

modules/RTC/TraceablePeerConnection.js
This fixes an issue where a user is not able to unmute their video if the MediaStreamTrack associated with the camera stream returns a null value for the track height.
=> fix(TPC): Select 1 as the default scale factor for p2p.

modules/xmpp/BreakoutRooms.js
This is necessary when adding new properties to the payload.
=> fix(breakout-rooms) send whole payload on update event

JitsiConference.js, JitsiConferenceEvents.js, modules/xmpp/ChatRoom.js
Jicofo sends a presence when the audio/video sender limit is reached in the conference. The client can then proceed to disable the audio and video mute buttons when this occurs.
=> feat(conference) Implement audio/video mute disable when sender limit is reached

modules/xmpp/AVModeration.js, modules/xmpp/BreakoutRooms.js, modules/xmpp/ChatRoom.js
Both of this features listen for events in the XMPP connection. Thus, if we join
another meeting over the same connection we might still receive some events on
the old event handler.
Stop listening for events from the components as soon as the leave operation is
triggered.
=> fix(avmoderation,breakout-rooms) dispose handlers when leaving

JitsiMeetJS.js, modules/qualitycontrol/ReceiveVideoController.js, modules/qualitycontrol/ReceiveVideoController.spec.js
Update the video receiver constraints to start using the new sources format when the 1sourceNameSignaling` feature flag is enabled.
Related PR: https://github.com/jitsi/jitsi-meet/pull/10527
=> feat: Adjust setReceiverConstraints to use new format

modules/xmpp/ChatRoom.js
We set the region using a custom extension https://github.com/jitsi/jitsi-xmpp-extensions/blob/master/src/main/java/org/jitsi/xmpp/extensions/jitsimeet/RegionPacketExtension.java in ChatRoom.initPresenceMap, and we use that in jicofo.
=> fix: Drop unused region info from presence.

modules/RTC/TraceablePeerConnection.js
The issue currently affects browsers based on Chromium 96.0.4664.110 including Brave, Chrome, Edge & Opera and Google Chrome 97.0.4692.56
=> fix(tpc) disable ulpfec on chrome 97

modules/RTC/TraceablePeerConnection.js
So, I've been doing more testing.
It seems that the BrowserDetection lib returns `undefined` on calling browser.isVersionGreaterThan('95') for Edge. There is also a problem with Opera - workaround not working - but I have not dug deeper there.
Internally the Bowser dependency identifies Edge and Opera by their real names, however Jitsi identifies Edge as `chrome`, and for Opera - my theory is - , the version scheme has differences.
These mismatches lead to problems on `this._bowser.satisfies` at `_checkCondition` function (@jitsi/js-utils).
Workaround is making the statement much more simple and more broad.
=> fix(tpc) extend ulpfec workaround to all versions

modules/xmpp/JingleSessionPC.js, package-lock.json, package.json
By rejecting the m-lines on source removal (setting the port to 0 on the associated m-line), m-lines can be recycled for new sources instead of appending new ones.
=> ref(JingleSession) Recycle m-lines by rejecting them on source removal.

modules/xmpp/JingleHelperFunctions.js
Since the order of the ssrcs in the json-encoded message is not guaranteed to be in the correct SIM/FID order, log all the ssrcs.
=> fix(logging) Log all the ssrcs present in the source signaling.

modules/RTC/TraceablePeerConnection.js
PR #1850 might cause problems if a client doesn't have support for getSenders() yet, like our mobile client. So this PR checks first if getSenders() is supported.
=> fix(RTC) skip DtlsTransport init if getSenders is missing

modules/RTC/TraceablePeerConnection.js
When using getSenders() in another PR I learned that it is not available on all of our clients yet. This PR adds safety checks to prevent existing code from making the same mistake.
=> fix(RTC) added safety checks before getSenders() calls

modules/xmpp/xmpp.js
Add the _onPrivateMessage handler when breakout_rooms is found in disco info.
I think this is a bug.  If only breakout_rooms rooms is enabled then, the _onPrivateMessage handler never gets called for breakout room messages.
=> fix: Add private message handler for breakout_rooms

modules/xmpp/JingleSessionPC.js, types/auto/modules/xmpp/JingleSessionPC.d.ts
When a user leaves, the ssrcs associated with the ep are removed from the remote description and a renegotiation is forced. The browser then fires 'removetrack' event on the associated MediaStream when sRD is called with ssrcs removed. Therefore, there is no need to explicitly delete the tracks at the TPC level. This also prevents the 'Removed track not found for stream' events from showing up in the browser console log.
=> fix(JingleSessionPC) Do not force track removal at pc level on user leave.

JitsiConference.js, modules/xmpp/Lobby.js
Better moderation capabilities in locked down rooms: challenge/response in lobby [#9714](https://github.com/jitsi/jitsi-meet/issues/9714)
Messaging methods in lobby room
getLocalId to get the local room id from jid
setMessageListener to listen for messages in lobby room
Reviewed-by: Fecri Kaan Ulubey f.kaan93@gmail.com
=> feat(lobby): challenge-response messaging

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/flags/FeatureFlags.js, modules/sdp/LocalSdpMunger.js, modules/sdp/RtxModifier.js, modules/sdp/SDP.js, modules/xmpp/JingleSessionPC.js, types/auto/modules/RTC/JitsiLocalTrack.d.ts, types/auto/modules/RTC/TPCUtils.d.ts, types/auto/modules/flags/FeatureFlags.d.ts, types/auto/modules/sdp/LocalSdpMunger.d.ts, types/auto/modules/sdp/RtxModifier.d.ts, types/auto/modules/sdp/SDP.d.ts, types/auto/modules/xmpp/JingleSessionPC.d.ts
This feature is behind 'sendMultipleVideoStreams' config.js flag and is currently supported only on clients running in Unified plan mode.
=> feat(multi-stream-support) Add the support for multiple local video streams.

modules/RTC/TraceablePeerConnection.js
=> fix(TPC) add muted tracks if p2p is disabled (fix #1851)

modules/qualitycontrol/SendVideoController.js, types/auto/modules/qualitycontrol/SendVideoController.d.ts
When multi-stream-support is enabled, configure the encodings on all the local video sources.
=> fix(quality-control) Configure encodings for all sources on media session creation.

modules/RTC/BridgeChannel.js, modules/qualitycontrol/SendVideoController.js
The colibri class name for the source name sender constraints changed from SenderVideoConstraintsV2 to SenderSourceConstraints.
The new format is {colibriClass: 'SenderSourceConstraints', sourceName: 'b6746083-v0', maxHeight: 180}
=> fix(qualitycontrol) SenderVideoConstraintsV2 changed to SenderSourceConstraints

TypeScript.md
This is purely a proposal at this stage and I'd be very happy for others to contribute.
The aim is to promote consistency across the conversion process.
=> plan for the TypeScript conversion process

modules/xmpp/JingleSessionPC.js
This patch removes aggressive layer suspension on RN. The way it was
implemented it would start sending media to the JVB even while in P2P.
I tried to look for a way around it, but I could not find a "is media
active in this Jingle session PC?" flag, so I chose the shortest path to
the fix and yanked the (mis)feature altogether. This will start to work
once we have transceivers.
=> fix(JingleSessionPC) fix "echo" on mobile

JitsiConference.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, JitsiMeetJS.js, JitsiTrackEvents.js, JitsiTrackEvents.spec.ts, modules/RTC/BridgeChannel.js, modules/RTC/JitsiRemoteTrack.js, modules/RTC/RTC.js, modules/connectivity/TrackStreamingStatus.ts, service/RTC/RTCEvents.js, service/RTC/RTCEvents.spec.ts, service/statistics/AnalyticsEvents.js, service/statistics/AnalyticsEvents.spec.ts, types/auto/JitsiConference.d.ts, types/auto/JitsiConferenceEvents.d.ts, types/auto/JitsiTrackEvents.d.ts, types/auto/modules/RTC/JitsiRemoteTrack.d.ts, types/auto/modules/RTC/RTC.d.ts, types/auto/modules/connectivity/TrackStreamingStatus.d.ts, types/auto/service/RTC/RTCEvents.d.ts, types/auto/service/statistics/AnalyticsEvents.d.ts, types/hand-crafted/JitsiConference.d.ts, types/hand-crafted/JitsiConferenceEvents.d.ts, types/hand-crafted/modules/RTC/JitsiRemoteTrack.d.ts, types/hand-crafted/modules/RTC/JitsiTrack.d.ts, types/hand-crafted/modules/RTC/RTC.d.ts, types/hand-crafted/modules/util/Listenable.d.ts
This change allow us handle the streaming status of each individual track when the feature flag is enabled. The emitted streaming status is mostly used for the connection indicator in the UI. 
Related jitsi-meet PR: https://github.com/jitsi/jitsi-meet/pull/10934 
Todo/Follow up item:
- Look into moving some of the `TrackStreamingStatus#onForwardedSourcesChanged` logic out into `RTC#_onForwardedSourcesChanged`. The reason being is that since TrackStreamingStatus is only initialized when a track is rendered, there is a corner case where we are not capturing the timestamp of when it entered forwarded sources.
- Add specs, this can be part of another PR.
=> feat(multi-stream-support) Add track streaming status

modules/xmpp/JingleSessionPC.js
It's possible we get sender constraint messages while operations to
change the direction in the JVB session are in progress so we currently
have no predictable way to properly suspend video without races.
Since this will be solved when we move to transceivers, this is a
compromise we are making.
=> fix(rn,JingleSessionPC) remove aggressive layer suspension in RN

modules/xmpp/JingleSessionPC.js
Recycling the m-line by rejecting it and then re-using is causing issues where sometimes the track addition fails. When a new ssrc is added to an m-line that was rejected and port is changed back to the default port, sometimes the remote sdp returned by browser wouldn't contain the newly added ssrcs and the track addition fails as a result.
Error: No SSRC lines found in remote SDP for remote stream[msid=854882f8-audio-1,type=audio]
at Ca._remoteTrackAdded (https://web-cdn.jitsi.net/meetjitsi_5885.2601/libs/lib-jitsi-meet.min.js?v=5885.2601:2:439103)
at Ca._usesUnifiedPlan.onTrack (https://web-cdn.jitsi.net/meetjitsi_5885.2601/libs/lib-jitsi-meet.min.js?v=5885.2601:2:432207)
at RTCPeerConnection.r (https://web-cdn.jitsi.net/meetjitsi_5885.2601/libs/lib-jitsi-meet.min.js?v=5885.2601:2:680736 …
=> fix(JingleSessionPC) Do not recycle m-lines when sources leave and join.

modules/xmpp/JingleSessionPC.js
In P2P and unified mode, Chrome does not render the media if an SSRC is removed and the same one is added back (happens when the sender is camera muted->starts SS->stops SS->turns camera on). That is why SSRC was not being removed. However, mobile endpoints that are running in plan-b generate a new SSRC when the client switches between camera and screenshare. This will cause issues on a p2p receiver that is running in unified mode. Fixes https://github.com/jitsi/jitsi-meet/issues/11010.
=> fix(JingleSessionPC) Remove the ssrc lines in remote desc sdp on source removal.

modules/RTC/TraceablePeerConnection.js
Chrome doesn't render media when the SSRC is added back to the m-line after removing it because of source-remove->source-add from peer. Avoid renegotiations so that these source removes and adds are not sent to the peer after the track is replaced.
=> fix(TPC) Do not force renegotiations for p2p.

webpack-shared-config.js
In theory it is good practice to use path.join in webpack config files rather than doing string concatenation - it also happens to make this line cross-environment compatible
=> use path.join in webpack-shared.config

webpack-shared-config.js
There is no need to treat js-utils differently, since it's now declared
as a module in package.json
Ref: https://github.com/jitsi/lib-jitsi-meet/pull/1957
=> chore(build) remove unneeded code

JitsiConference.js, modules/e2eping/e2eping.js, types/auto/modules/e2eping/e2eping.d.ts
- Do not send analytics periodically.
- Stop sending e2eping after 5 responses.
- Only send e2eping in one direction in a pair of endpoints.
- Fix syntax, lint errors.
- squash: Cleanup logs, stop pings if we don't get responses.
- Use a timeout instead of interval.
- feat: Space out e2e pings based on conference size.
=> End-to-end ping updates

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/xmpp/JingleSessionPC.js, types/auto/modules/xmpp/JingleSessionPC.d.ts
fix(TPC) Update the local SSRC cache when a track is replace with another.
Fixes an issue where the local stats are not emitted in Unified plan after a track replace.
fix(multi-stream) Add video tracks sequentially.
If there are more than one video track at pc creation time, add them sequentially to avoid renegotiation loop.
fix(TPC) Send presence before signaling for SS tracks.
This is needed for the track to be identified as a desktop track on the remote peer when the JitsiRemoteTrack is created.
Fixes https://github.com/jitsi/lib-jitsi-meet/issues/1649.
fix(multi-stream) Do not emit ParticipantConnectionStatus updates when source-name signaling is enabled.
=> Fix connection stats

modules/sdp/LocalSdpMunger.js, modules/sdp/LocalSdpMunger.spec.js, modules/xmpp/JingleSessionPC.js, package-lock.json, package.json, types/auto/modules/sdp/LocalSdpMunger.d.ts
fix(SDP) Always modify the streamId part of msid when source-name signaling enabled.
Do this even if the browser provides a non '-' string for streamId since we rely on this to generate the source name.
fix(multi-stream) Update the <ssrc, source-name> map for p2p as well.
Update sdp-interop@latest
=> Fix msid munging

JitsiConference.js, modules/sdp/LocalSdpMunger.spec.js
Disable p2p between endpoints that are not running in the same SDP mode. The source-add/source-remove handlers assume the mids to follow the same pattern on both self and peer but the mids generated in plan-b mode are different from unified plan mode. Fixes https://github.com/jitsi/jitsi-meet/issues/11100.
=> fix(conference) Disable p2p between eps running in different SDP modes.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
fix(multi-stream) add new m-line when remote adds a second video source in p2p.
A new m-line needs to be added in the remote description when a new secondary video source is signaled by the peer.
fix(TPC) Suppress lower layers only for screenshare tracks.
With multi-stream support enabled, an extra check for videoType for local track is needed to dtermine if the lower layers need to be suppressed.
fix(TPC) Mark the direction inactive on inactive media connection.
If a new secondary video source is added on the jvb connection while p2p is active, make sure the direction is set to inactive on the jvb connection, so that no media is being sent out on the jvb connection.
=> Fix p2p multistream

modules/RTC/TraceablePeerConnection.js, modules/xmpp/SignalingLayerImpl.js
When source-name signaling is enabled, get correct peermedia info when the peer sends presence in the legacy format. This fixes an issue where Jigasi users cannot be heard by endpoints that have source-name signaling enabled.
=> fix(presence) Parse peer presence in legacy format correctly.

modules/xmpp/ChatRoom.js
This changes the chat room presence to only include videoType value on video tracks.
=> fix(presence) Only apply default videoType on video tracks

JitsiConference.js
Additionally I was wondering if it is still a problem to have a P2P connections between Chrome, Firefox and Safari?
=> fix: p2p reject reason

modules/RTC/RTC.js, types/auto/modules/RTC/RTC.d.ts
This fixes an issue where the receiver constraints and video type messages are sent on the bridge channel only the first time the ws conn gets re-established.
=> fix(BridgeChannel): re-send constraints and videoType message after every re-connect

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/qualitycontrol/ReceiveVideoController.js, modules/qualitycontrol/SendVideoController.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/JingleSessionPC.spec.js, modules/xmpp/MediaSessionEvents.spec.ts, modules/xmpp/MediaSessionEvents.ts, types/auto/modules/qualitycontrol/ReceiveVideoController.d.ts, types/auto/modules/qualitycontrol/SendVideoController.d.ts, types/auto/modules/xmpp/JingleSessionPC.d.ts, types/auto/modules/xmpp/MediaSessionEvents.d.ts
When the user changes the preferred video quality settings from the UI, update the frame height values in content-modify for p2p connection when source-name signaling is enabled.
=> fix(video-quality) Update frame heights in content-modify for p2p.

modules/RTC/TPCUtils.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/JingleSessionPC.spec.js
When a media session is re-created with multiple video sources in the conference as result of peer leaving and joining the call, send out the session-accept with first video source and then add the secondary source and signal it. Otherwise, ice candidates can reach the peer before the seesion-accept because of timing and not be processed (since a remote sdp won't be set) and result in a broken connection. This is needed only for the responder case. In the initiator case, all the tracks are added to the pc and then a session-initiate is sent to the peer. This doesn't seem to trigger the renegotiate loop.
=> fix(multi-stream) Send the initial session-accept and then add the secondary video tracks when a session is re-created

JitsiMediaDevices.js, modules/RTC/RTCUtils.js
With https://bugs.webkit.org/show_bug.cgi?id=179363 being fixed, we should now be able to switch between devices in call.
=> fix(browser-support) Enable device selection in mobile Safari.

modules/RTC/TraceablePeerConnection.js, types/auto/modules/RTC/TraceablePeerConnection.d.ts
Firefox doesn't generate a `a=ssrc-group: SIM` line in its local SDP for every local video source. When multiple video sources are added to the peerconnection, a SIM group for every 3 FID groups need to be injected so that they can signaled to Jicofo.
=> fix(multi-stream) Inject multiple SIM groups on Firefox when multiple sources are added.

modules/connectivity/TrackStreamingStatus.ts
So that we don't have to maintain `jitsiTrack` in the scope where listeners are defined. 
This change is a dependency for https://github.com/jitsi/jitsi-meet/pull/11377
=> JitsiTrackEvents.TRACK_STREAMING_STATUS_CHANGED expose jitsiTrack as listener parameter

service/RTC/CodecMimeType.js
With that, it's possible to set AV1 as preferred codec for p2p and try it on Chrome.
=> feat: add AV1 mime type

modules/browser/BrowserCapabilities.js, service/RTC/CodecMimeType.spec.ts
fix(RTC) Add AV1 to CodecMimeType unit test
=> Fallback to plan-b on Electron clients that have chromium ver < 96

JitsiConference.js
Removing and adding a track back to the conference doesn't generate new source signaling all the time so presence needs to be updated every single time.
Fixes https://community.jitsi.org/t/screen-share-doesnt-work-a-second-time-on-p2p/114024 and possibly https://github.com/jitsi/lib-jitsi-meet/issues/1997.
=> fix(presence) Send a presence update on every track replace operation.

modules/statistics/RTPStatsCollector.js
pair with https://github.com/jitsi/jitsi-meet/pull/11475
This fixes missing stats for screen share tiles in jitsi-meet when source name signaling is on.
=> fix missing stats for screen share tiles by using source name as key

JitsiMediaDevices.js
Fixes https://github.com/jitsi/jitsi-meet/issues/2835.
Since https://bugzilla.mozilla.org/show_bug.cgi?id=1238038 has been merged and the latest Firefox Nightly has been build (see https://hg.mozilla.org/mozilla-central/rev/61d8c578d367ea82c64fa5f55c8a4af54fe84c21, build ID `20220419093010`), Firefox now supports the selection of multiple audio inputs.
Therefore, `isMultipleAudioInputSupported` should return true for Firefox versions 101 and later.
I tested this in Firefox Nightly 101.0a1 (2022-04-19) on macOS 12.3.1 and confirmed that the microphone selection (as described in the linked issue) is working properly.
=> Support multiple audio inputs in Firefox 101

modules/RTC/JitsiTrack.js, types/auto/modules/RTC/JitsiRemoteTrack.d.ts, types/auto/modules/RTC/JitsiTrack.d.ts
RN clients throw a function undefined error otherwise.
=> fix(RTC): Add function declaration to JitsiTrack.

JitsiConference.js
In most cases it's not a real issue and it's still part of the logs,
throwing an unhandled exception at the global handler just prints an
ugly trackeback in the JS console which looks much worse than it really
is.
=> fix(JitsiConference) log a warning instead of an error is p2p fails

JitsiConference.js
BUG: mute camera before join to room
current: mic is muted too (on the other side)
expect: mic isn't muted
=> fix(presense) don't lose prev presenceChanged value

modules/e2ee/Context.js, types/auto/modules/e2ee/Context.d.ts
the editor will no longer complain about superfluous await when calling
related to #2026
=> ref(e2ee) mark _decryptFrame function with correct jsdoc

modules/RTC/ScreenObtainer.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, types/auto/modules/RTC/TraceablePeerConnection.d.ts
fix(ScreenObtainer) Apply resolution constraints only for low fps SS.
The hack for making Chrome capture the highest resolution possible for desktop track breaks high fps screen capture.
fix(multi-stream) Fix VP9 bitrates in the multi-stream mode.
Set the bitrates on the video m-lines based on the associated track type. In multi-stream mode, there will be two separate m-lines for camera and desktop tracks. Also fallback to SDP munging for setting codec preferences on Chromium.
=> Screensharing fixes.

modules/xmpp/xmpp.js
They are always required and the signaled features are ignored.
=> Remove the rtcpmux and bundle features.

JitsiConference.js, modules/RTC/JitsiLocalTrack.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, types/auto/JitsiConference.d.ts, types/auto/modules/RTC/TraceablePeerConnection.d.ts, types/auto/modules/xmpp/JingleSessionPC.d.ts
Since the track is only temporarily removed and added back, it can be treated like mute & unmute operation. Fixes https://github.com/jitsi/lib-jitsi-meet/issues/2048. Remove a TODO thats no longer needed, track replace operation don't force renegotiations anymore.
=> fix(RTC) Use mute/unmute track operation for effects.

modules/red/red.js, modules/red/red.spec.js
which can be used together with WebRTC Insertable Streams to encode
a variable amount of audio redundancy
=> modules: add RFC 2198 audio redundancy encoder

modules/xmpp/JingleSessionPC.js, types/auto/modules/red/red.d.ts, types/auto/modules/xmpp/JingleSessionPC.d.ts
ref(JingleSessionPC): Remove unncessary reneg cycles for p2p.
When an answer is received from the p2p peer, only set remote description instead of calling the full renegotiation cycle. Also, always initiate a sRD->cA->sLD cycle when adding remote sources irrespective of whether the local endpoint is an initiator or responder for the p2p connection. This lets us remove the hacks added for Chromium (unified-plan) bugs related to video not rendering in p2p cases.
feat(red) Add missing type def for RFC2198Encoder.
=> Fix renegotiations for p2p

modules/RTC/TraceablePeerConnection.js, types/auto/modules/RTC/TraceablePeerConnection.d.ts
This fixes an issue where the bitrates for screenshare were much higher than before for VP9 causing the JVB to suspend SS streams more often.
=> fix(TPC) Set maxbitrates via b=AS line on the remote SDP as well.

modules/RTC/JitsiRemoteTrack.js
> Possibly fixes a bug where SS appears black when the'unmute' and forwarded sources event for the track are received before a large-video update is scheduled.
=> fix(connectivity): Fire trackStreaming status update  on init.

modules/RTC/JitsiLocalTrack.js
It is useful in our custom application to know the track reference which got stopped at the listener level.
I've seen examples like this in other places of the project such as: 6b629a194a0d8bc357325b599c3ee57166d81d42
Please take a look.
=> ref(JitsiTrackEvents.LOCAL_TRACK_STOPPED) expose jitsiLocalTrack as listener parameter

modules/qualitycontrol/SendVideoController.spec.js, modules/xmpp/JingleSessionPC.js, types/auto/modules/xmpp/JingleSessionPC.d.ts
Hi,
this PR removes all references to `enableLayerSuspension`.
The use of this flag was removed in https://github.com/jitsi/lib-jitsi-meet/commit/b749b0e4e7ea1a826066768f9d5a367f8c8fdb21
=> chore(enableLayerSuspension) remove all enableLayerSuspension references

modules/proxyconnection/ProxyConnectionService.js, modules/sdp/SDP.spec.js
Looks like these have slipped away. Most likely due to the header being slightly different `/* global $ */` vs `/* globals $ */`
=> fix(build) add missed jquery slim imports

modules/proxyconnection/CustomSignalingLayer.js, modules/proxyconnection/ProxyConnectionPC.js, modules/xmpp/SignalingLayerImpl.js, service/RTC/SignalingLayer.js, types/auto/modules/proxyconnection/CustomSignalingLayer.d.ts, types/auto/modules/xmpp/SignalingLayerImpl.d.ts, types/auto/service/RTC/SignalingLayer.d.ts
The existing SignalingLayerImpl is too intertwined with ChatRoom, and it has become too hard to use for ProxyConnectionPC.
Thus I ventured into creating a custom implementation that has the absolute bare minimum for that connection to work. WDYT @jallamsetty1 ?
While I was there I noticed the interface was outdated since the new functionality for multi-stream requires some implementation of certain methods, so I added them there.
Generally speaking, I'm not happy at all with this, and if we get to work on Spot I'd love to try and replace this with something that doesn't need to involve LJM internals so much. Oh well.
=> Fix ProxyConnectionPC, use a custom signaling layer

modules/statistics/AvgRTPStatsReporter.js
This fixes an error that gets logged when no media is being sent/received by the endpoint.
Logger.js:154 2022-09-12T14:40:53.476Z [modules/statistics/AvgRTPStatsReporter.js] <xl.addNext>:  bandwidth_upload - invalid value for idx: 0
=> fix(stats): Skip bandwidth calc if there is no uplink/downlink bitrate.

tsconfig.json, types/auto/index.d.ts
It's only used for the UMD bundle.
=> fix(ts) skip generating type definitions for index.js

modules/RTC/TPCUtils.js
Firefox lists stopped transceivers when getTranceivers is called, ignore these when picking a trancceiver for a screenshare track. Fixes an issue when starting screenshare fails if there are stopped tranceivers in the peerconnection (i.e., if some remote users with sources have left the call).
=> fix(TPC): Ignore stopped transceivers on FF during new track addition.

JitsiConference.js
This fixes an issue where mute camera operation doesn't stop sending camera stream even though locally it appears to the user that they are muted. This happens when multiple camera streams are added to peerconnection because of how toggle of the video button is implemented. This limitation will be removed when the application is fixed.
=> fix(multi-stream) Block addition of multiple video streams of the same videoType

modules/RTC/TraceablePeerConnection.js
Added setting Opus DTX in munged config for reduction in the audio traffic, when a participant is silent then the audio packet won’t be transmitted.
=> ref(stereo-flags-munging): add enableOpusDtx to mungedConfig

modules/RTC/JitsiLocalTrack.js
When a track has an effect, `setEffect` is finished after `stopStream` which leave the original track not stopped.
=> fix(RTC) fix stop track with effect (#2127)

modules/flags/FeatureFlags.js
This brings back a change from a previous pull I've submitted:
https://github.com/jitsi/lib-jitsi-meet/pull/2126/files#diff-e7edcd8944deb07d06306a33c3e6b0c56b24b84c777fb98cb44ad5348117e4a4R14
So JSDoc can be more complete and actually mark all options as optional.
=> ref(FeatureFlags) fix JSDoc

modules/RTC/ScreenObtainer.js
Allow users to seamlessly switch which tab they are sharing without having to stop the current share and select a new tab again. This is supported on Chrome 107 onwards.
A new button "Share this tab instead" will be shown when the user switches to a tab that is not being shared.
=> feat(ScreenObtainer) Allow seamless switching of tab capture.

JitsiConference.js, modules/qualitycontrol/ReceiveVideoController.spec.js, modules/sdp/SDP.spec.js, modules/sdp/SDPDiffer.spec.js, modules/xmpp/JingleSessionPC.spec.js, modules/xmpp/SignalingLayerImpl.spec.js
Cleans up otherwise unused participantConnectionStatus and sourceNameSignaling things.
=> ref: remove references to legacy endpoint based signaling switch

JitsiConference.js
Workarounds around issue #2037 to have other participants receive the mute event and therefore avoid frozen camera bug.
There may be a better way to fix this, so I leave to the experts to review and figure out what is causing the `sourceInfo` to not be sent on track removal without this trick (or workaround at application level).
The good news is this is far less invasive then my previous workaround in the original issue. My two cents.
Kind regards and thanks in advance.
=> fix(JitsiConference) send mute sourceInfo before removing an unmuted track

webpack-shared-config.js
It's now in JitsiMeetJS.ts rather than .js.
=> Set the ljm commit hash in the correct file.

modules/RTC/TraceablePeerConnection.js
Revert this change as this is causing a dummy track to be created when the media resumes on jvb connection after the p2p peer has left the call.
=> fix(TPC) Do not create track when presence is missing.

modules/xmpp/moderator.js
- Remove callstats conference property.
- Remove RTX conference property (removed from backend).
- Remove audioPacketDelay conference property (removed from backend).
=> Remove deprecated conference properties

modules/statistics/SpeakerStatsCollector.js
Because Lua does not have an array object, {} can be set for faceLandmarks if there the participant has speaker time and no facelandmarks in prodosy. https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_speakerstats_component.lua#L254
=> fix(speaker-stats): set faceLandmarks on update only if it is has data

modules/xmpp/moderator.js
<conference xmlns="http://jitsi.org/protocol/focus" vnode="v1" ready="true" room="roomtest@conference.focus.exmaple.com" focusjid="focus@auth.meet.jitsi">
<property name="authentication" value="false"/>
<property name="sipGatewayEnabled" value="true"/>
</conference>
=> feat: Moves vnode handle from  conferenceIQ error to success response.

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/flags/FeatureFlags.js, modules/litemode/LiteModeContext.js
(Rather than moving streams to inactive in SDP.)
=> Use insertable streams to drop all media when in lite mode.

modules/RTC/BridgeChannel.js
Multiple WebSockets could lead to client being unable to send any bridge messages due to lost `this._channel` reference.
Scenario:
1. `WebSocket #1` (`WS1`) is closed somehow by server -> start backoff retrying.
3. Spawn `WS2` in 1 sec -> `WS2` connecting -> store `WS2` in `this._channel`.
4. Spawn `WS3` in 2 sec -> `WS3` connecting -> store `WS3` in `this._channel`.
5. `WS2` connects -> stop retrying. But we have `WS3` in `this._channel`.
6. `WS3` connects moments after `WS2` -> at same moment `WS2` is closed by server (same url with `WS3`) -> `WS2` `onclose` handler resets `this._channel` to `null` and should start retries again, but `WS3` `onopen` handler stops them.
7. `WS3` survives and receives messages, but `this._channel` is `null` -> `isOpen` returns `false` -> `_send` throws …
=> fix(BridgeChannel): prevent multiple websockets on retries

JitsiConference.js, modules/RTC/CodecSelection.js, modules/sdp/SDPUtil.js, modules/xmpp/JingleSessionPC.js
1. Checks peer's preferred codec in p2p case. Mobile and web have different preferred codecs.
2. Log an error message when the preferred codec is not offered by JVB.
3. Clean up code related to deprecated config.js settings 'preferH264' and 'disableH264'.
4. Refactor the codec selection logic so that correct codec is picked.
=> fix(codec-selection): Codec selection fixes.

package-lock.json, package.json
I am adding this as a dependency to a project managed by Yarn v2, which is a bit more persnickety regarding dependency syntax. It can't infer how to resolve the package.
```diff
-https://git@github.com
+git+https://github.com
```
This change should be functionally identical to the current behavior, but now it plays nicely with Yarn v1, v2, and npm.
=> Use conventional syntax for depending on git repos as deps

JitsiConference.js, modules/xmpp/ChatRoom.js, modules/xmpp/moderator.js
- ref: Inline onMucMemberLeft (has nothing to do with "moderator" and is broken).
- fix: Use isFocus instead of just reading the resource.
- ref: Inline onParticipantLeft.
- ref: Add _ to private function names.
- ref: Remove redundant function.
- ref: Initialize focusComponent once.
- ref: Remove two copies of "options".
- ref: Simplify the focusJid flow.
- ref: Rename focusCompoonent to targetJid.
- fix: Only retry on "invalid sessin" errors
- ref: Remove use of visitorFocus.
- ref: Remove graceful shutdown handling (never used in backend).
- feat: Support conference request over HTTP.
- ref: eslint cleanup.
- fix: Add max timeout 2 minutes.
- squash: Fixes conference request handling.
=> Conference request over HTTP

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/proxyconnection/CustomSignalingLayer.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SignalingLayerImpl.js, service/RTC/SignalingLayer.js, types/hand-crafted/modules/xmpp/SignalingLayerImpl.d.ts
Update the SSRC owners in the following cases:
1. When a remote endpoint leaves the call.
2. When a source-remove is received.
3. When a source is remapped (with ssrc-rewriting enabled). 
Create the remote track even if presence is not yet received. The ssrc owner check prevents the client from creating a dummy track when the call switches over from p2p to jvb after the last remote endpoint leaves the call.
=> fix(SignalingLayer) Update SSRC owners on leave.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, JitsiParticipant.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SignalingLayerImpl.js, modules/xmpp/SignalingLayerImpl.spec.js, service/RTC/SignalingEvents.spec.ts, service/RTC/SignalingEvents.ts
In this feature:
- There will be a fixed set of remote tracks and therefore a fixed set of SSRCs.
- The bridge will re-map those SSRCs to a remote sender based on what is being requested and then the owner (source) of a remote track will change.
- The bridge does the remapping based on the receiver constraints received from the client.
- However, the receiver constraints currently are derived from the tracks in redux but with ssrc-rewriting, the tracks won't be created unless it is signaled. So it is a chicken and egg problem. Therefore, we will be constructing the receiver constraints based on the remote presence since all the source information is already signaled in presence.
There is jitsi-meet PR which does the receiver constraints part - …
=> Feat ssrc rewriting

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
This makes the screenshare bitrate configurable if using VP9. Happy to make changes.
Not sure if `localStreamEncodingsConfig` needs to change as well
=> fix(TPC): make screen share bitrate configurable

modules/sdp/SDP.js
According to the RFC's extmap attributes are allowed at the media and the session level. This makes us look for them at the session level as well in case something starts doing that one day.
=> fix(SDP): search for extmap at session level

modules/RTC/BridgeChannel.js, modules/RTC/RTC.js
Currently, the client doesn't attempt to re-establish bridge WS when the connection is closed by the remote end with a code 1001. We have noticed that Cloudflare terminates the WS with the same error code when it recycles its proxies. When that happens, client ends up not having a bridge channel which can result quality issues. Client now tries to re-establish connection when there are remote endpoints in the call.
=> fix(BridgeChannel): Attempt conn retries when there are remote endpoints.

JitsiConference.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, types/hand-crafted/modules/RTC/TPCUtils.d.ts, types/hand-crafted/modules/RTC/TraceablePeerConnection.d.ts, types/hand-crafted/modules/xmpp/JingleSessionPC.d.ts
Resume or suspend the media on the jvb peerconnection by changing the RTCRtpEncodingParamters.active state instead of changing the direction on the transceiver. This avoids the needs to start a O/A renegotiation cycle for these operations. The media direction will be changed only for p2p lastn=0 case since video needs to be disabled on both the sender and the peer for p2p lastn=0 case.
=> fix(TPC) Disable media instead of changing dir for p2p->jvb switch.

modules/RTC/CodecSelection.js, modules/RTC/TraceablePeerConnection.js
This should avoid unnecessary renegotiations if disabledCodec setting is present in config.js and should improve time to receive media when joining big calls.
=> fix(codec-selection) Check if disabled is already removed from sdp.

modules/RTC/ScreenObtainer.js
This allows the client app to decide the maximum resolution that needs to be captured using electron.
We have found machines that try desktop capture at 4k to be sluggish, and would like to limit it to 720p.
Follows the same constraints configuration format as Camera capture, with fallback to previous functionality if no constraints configured.
=> fix(ScreenObtainer): make electron desktop resolution constraints configurable

JitsiConference.js, modules/RTC/CodecSelection.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
This fixes an issue where p2p clients (with different codec preferences) fail to decode video because the negotiated codecs are removed from the supported codecs list after the media session is established. The codec preferences will be applied when the first offer/answer is created.
=> fix(codec-selection) Apply codec preferences to initial offer/answer.

JitsiConference.js
When the call switches over to JVB after a remote p2p peer leaves, the remote tracks (of the peer that just left) are removed from the conference after the SSRCs are removed from SDP and since it necessitates a renegotiation, the task is pushed to the modification queue. Since the switch to jvb connection happens immediately, the remote jvb remote tracks are present after the switch and they get added to the conference again. Add the check for the remote participant before adding the tracks. This fixes an issue where the remote tracks are present in redux even after the participant leaves.
=> fix(JitsiConference) Check if participants exist before adding the tracks back.

.npmrc, modules/xmpp/Caps.js, modules/xmpp/sha1.js, package-lock.json, package.json, webpack-shared-config.js
Update notes:
- The base64-sha1 code got stripped out, so we bundle it now
- There are 2 optional dependencies which we want to ignore to avoid extra bundle size: xmldom and ws (the former is used by RN but we provide it in the app and the latter is only used by Node environments)
=> chore(deps) strophe.js@1.6.0

modules/xmpp/ChatRoom.js, modules/xmpp/strophe.emuc.js
Moderator now merges conference config over connection config. We need it in case we want to keep the connection but use other settings for the conference (visitors mode).
=> feat: Listens for visitor IQs.

modules/RTC/ScreenObtainer.js
Request higher capture resolutions when desktopSharingFrameRate is not defined in config.js.
=> fix(ScreenObtainer) Request high resolutions by default.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
Ignore sender constraints if the client is already sending video of the requested resolution. For desktop tracks, max resolution will be the height of the window being captured irrespective of the height being requested by the peer. Therfore, check if the configured resolution is equal to the track height for all requested heights > 0. Fixes an issue where the track addition fails because of setParameters failing on the video track. This is only seen the torture tests because this is very timing specific.
=> fix(TPC) Avoid applying constraints on desktop tracks if not needed.

JitsiConference.js, modules/RTC/TraceablePeerConnection.js, modules/statistics/RTPStatsCollector.js, modules/xmpp/JingleSessionPC.js
Set track owners to null when remote participant leaves.
Update mute state after source is re-mapped.
Also add all the orphan jvb tracks to the conference when the call switches over from p2p to jvb.
=> Fix ssrc rewriting

JitsiConference.js, modules/browser/BrowserCapabilities.js, modules/detection/NoAudioSignalDetection.js, modules/statistics/RTPStatsCollector.js, types/hand-crafted/modules/statistics/RTPStatsCollector.d.ts
Track based stats have been removed recently and RTCRtpReceiver:getSynchronizationSources has been available in the browsers for a while now.
=> fix(statistics) Use RTCRtpReceiver:getSynchronizationSources for audioLevels always

modules/RTC/CodecSelection.js
Fixes an issue on mobile where the videos of users joining after the mobile endpoint are not being rendered.
=> fix(codec-selection) Calc preferred codec after media session is established

modules/xmpp/XmppConnection.js, modules/xmpp/xmpp.js
With visitors we rarely see not able to send messages or presence because not connected error. Seems the status of the connection is wrong when quickly disconnecting and connecting again.
=> feat: Adds debug log around connected.

modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js
'Track' based stats were dropped in Chrome 112, therefore send resolution and fps for the simulcast case needs to be calculated based on the 'outbound-rtp' streams that are currently active.
=> fix(stats) Obtain resolution/fps from 'outbound-rtp' stats.

JitsiConference.js
Fixes an issue where media gets sent on jvb connection even when the connection is suspended.
=> fix(conference) Make sure media on jvb connection stays suspended.

modules/util/AsyncQueue.js, modules/xmpp/JingleSessionPC.js
Pull initial offer/answer tasks out of the modification queue and execute them right away. Only track and codec related operations that necessitate a renegotiation cycle need to be pushed to the modification queue. The queue execution is paused until the session is established. This avoids track operations being executed before the session is established. This fixes an issue seen in p2p connections where sources of the initiator are not signaled to the remote since the tracks are added while the initiator is waiting for a session-accept from the peer.
=> fix(JingleSession) start modification queue after session is established

JitsiConference.js, JitsiConferenceEventManager.js
Fixes a corner case where the local tracks are not added to the jvb pc if the session-initiate from Jicofo is received after the policy is set. This doesn't reproduce manually and happens only in torture on certain deployments because its timing specific.
=> fix(JitsiConference) Do not apply the startMutedPolicy locally on the moderator.

modules/RTC/TraceablePeerConnection.js, modules/xmpp/SignalingLayerImpl.js
As implemented in other parts of the code, do not set videoType for audio sources.
Related to #1979
=> fix(SignalingLayer,TPC) do not set videoType for audio sources

modules/RTC/TraceablePeerConnection.js
Fixes an issue with Spot screensharing since Spot uses a fake conference to create a connection for screensharing and codecSettings are undefined.
=> fix(TPC) Ignore codecSelection when codec settings are missing.

JitsiMeetJS.ts, modules/browser/BrowserCapabilities.js
The constructor is too early and we miss it in rtcstats.
=> fix(BrowserCapabilities) log browser name and version on init

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
Adjusted wrapping method to have RTCRtpSender setting parameters in sequential manner in order to solve race condition when transaction id can be reset at the end of videoSender setParameters and cause exception if another update was already in fly and before its check for transaction id presence.
The issue "Failed to execute 'setParameters' on 'RTCRtpSender': Failed to set parameters since getParameters() has never been called" happened because the actual setting params were not called sequentially, the function was executed and promise was chained what broke the logic - [code_link](https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/TraceablePeerConnection.js#L2654)
Similar change was made in past - [github_link](https://github.com/jitsi/lib-jitsi-meet/pull/2228)
Also after …
=> fix(RTCRtpSender) Race condition on resetting transaction id.

JitsiMeetJS.ts, modules/RTC/ScreenObtainer.js, modules/RTC/TPCUtils.js, modules/xmpp/JingleSessionPC.js, types/hand-crafted/JitsiMeetJS.d.ts
- fix(JingleSession) Reconfigure the stream encodings after p2p->jvb switch.
Fixes blurry screenshare in some cases. There is a higher probability of the higher layers getting suspended when all the stream encodings are enabled for low fps SS. Make sure only the highest spatial layer is sent for low fps SS after p2p->jvb switch. Make sure all the stream encodings are enabled for high fps SS after p2p->jvb switch.
- fix(ScreenObtainer): Apply contentHint on captured desktop track correctly.
contentHint needs to be set to 'motion' for high fps SS and 'detail' otherwise. Fixes https://github.com/jitsi/lib-jitsi-meet/issues/2298.
=> Fix screenshare issues

modules/RTC/CodecSelection.js
Move VP9 to the end of the list when the VP9 encode is not desirable on certain endpoints, even when no codec preference is specified.
=> fix(codec-selection) Move VP9 to the end of the list when not supported.

modules/xmpp/JingleSessionPC.js
supportsCodecPreferences is a function, and must be called. Am I right?
Thanks.
PS: needs testing as AFAIK _mungeCodecOrder was never getting called.
=> fix(JingleSession) actually call browser.supportsCodecPreferences

modules/RTC/JitsiRemoteTrack.js
Workaround for Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1099280 which results in client switching to showing avatar instead of static content after 10 secs.
=> fix(screenshare): Ignore mute events on remote desktop tracks.

modules/statistics/statistics.js, modules/watchRTC/WatchRTC.ts, modules/watchRTC/functions.ts, modules/watchRTC/interfaces.ts, package-lock.json, package.json, webpack-shared-config.js
Following PR contains changes required to add watchRTC as a module within lib jitsi meet
This involves adding
- watchRTC SDK package (npm i @testrtc/watchrtc-sdk).
- watchRTC SDK is initialized within Statistics.init to proxy WebRTC functions such as GUM and RTCPeerConnection.
- watchRTC SDK then starts collecting required stats when the conference begins. Here we check if the user has not configured room name or user/peer name, if not, then use relevant data available from Jitsi.
- watchRTC SDK does not require to function for react native. 
- checks implemented to run watchRTC SDK when
-- watchRTC is enabled
-- rtcstats must be disabled
-- analytics should be enabled
-- third party requests are not disabled
=> watchRTC as a feature for Jitsi meet

modules/RTC/CodecSelection.js, modules/RTC/CodecSelection.spec.js
E2EE is not supported by the application when VP9 is the selected codec. Therefore, switch to using VP8 for video encode/decode.
=> fix(CodecSelection) Switch codec to VP8 when E2EE is enabled.

modules/RTC/TraceablePeerConnection.js
Just moving them to the end of the list guarantees that they are not picked for encoding.
=> fix(codec-selection): Do not strip codecs that are not in the preferred list.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
1. For renegotiations triggered by the application, it is ok to execute sRD->cA-sLD cycle on the p2p initiator instead of executing cO->sLD->sRD cycle. Chrome sometimes creates a third m-line for p2p when createOffer is called which is unexpected and therefore it breaks the client's renegotiation cycle. This has been done in other places already, i.e., when remote sources are signaled, etc. so making it uniform across all renegotiations.
2. fix(JingleSession) Modify encoding to stop/start outgoing media on p2p.
This is much faster than changing direction on the transceiver and doesn't need a renegotiation for the suspending/resuming media. Also fixes an issue with audio-only mode in p2p where media doesn't resume when audio-only mode is disabled if it was enabled while the jvb connection …
=> ref(JingleSession) Fixes media handling and renegotiations for p2p.

modules/RTC/CodecSelection.js
Addresses https://github.com/jitsi/jitsi-meet/issues/10657
=> fix(codecs): Enable VP9 encode on FF/Safari for p2p.

modules/sdp/RtxModifier.js
Fixes setLocalDescription failing in the case where simulcast is disabled since the answer produced by the browser (after a local source is added) does not have the msid line.
=> fix(SDP): Add msid to generated RTX SSRC only when present on primary SSRC.

modules/RTC/CodecSelection.js
When VP9 is at the top of the codec list in the remote offer, Firefox omits it in the answer but decides to use VP9 for encoding media. Therefore the remote peer gets an answer with no VP9 in the list and when it updates its local description (with no VP9) after a renegotiation, it stops rendering the VP9 video received from Firefox.
=> fix(codec-selection): Disabled VP9 for p2p on Firefox.

modules/proxyconnection/ProxyConnectionPC.js, modules/xmpp/JingleSessionPC.js
=> fix(JingleSessionPC,ProxyConnectionPC) handle empty local tracks

modules/proxyconnection/CustomSignalingLayer.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/SignalingLayerImpl.js, service/RTC/SignalingLayer.js
Additional benefits are:
- ssrc -> source name will be updated on ssrc remap message from
the bridge.
- the map will be correctly cleaned when member leave (this logic was
not working well for _sourceName map)
- Looks cleaner and simpler.
=> fix(signaling): Merge ssrcOwners and _sourceName.

JitsiParticipant.js, types/hand-crafted/JitsiParticipant.d.ts
Our application needs access to the `_identity` JWT claims for each participant. It's already stored on `participant._identity`, this PR just exposes it with a new getter:
```ts
jitsiParticipant.getIdentity()
// => { user: Object }
```
References:
- [JWT context structure](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#token-identifiers-structure-optional)
- [Prior art](https://github.com/jitsi/lib-jitsi-meet/pull/1393) (PR appears dead)
=> Expose JWT identity claims through public API

modules/xmpp/JingleSessionPC.js
Instead of using the videoType from source map signaled by the bridge which can be incorrect if the bridge doesn't receive the presence before it sends out the source map. It uses the default 'camera' as video type if presence is not received from the senders. Possibly fixes a bug where a screenshare source is displayed in the wrong tile after the SSRC is re-mapped.
=> fix(JingleSession) Use the video type from presence.

modules/RTC/CodecSelection.js
No other codecs are supported currently.
=> fix(E2EE): Switch to VP8 when E2EE is enabled.

modules/RTCStats/RTCStats.ts, modules/RTCStats/interfaces.ts
There are use cases where `RTCStats.init` is called without the argument property `initConfig.analytics.rtcstatsEnabled` being `true` - it is because by default it is false.
In those cases, calling `connection.initJitsiConference("conference", confOptions);` result in this error below:
RTCStats is sending a somewhat misleading console error message (as if the user deliberately called `RTCStats.start` without initializing `RTCStats.init`), whereas the browser technically did call `RTCStats.init` before `RTCStats.start` - only `initConfig.analytics.rtcstatsEnabled` was `false` by default.
This pull request handles cases where RTCStats is initialized without being enabled.
Thank you for reviewing my pull request.
=> feat(RTCStats) Suppress unnecessary error message when rtcstatsEnabled === false

modules/util/AsyncQueue.js, modules/xmpp/JingleSessionPC.js, types/hand-crafted/modules/util/AsyncQueue.d.ts
This ensures that promises relying on the task callback will settle.
=> fix(JingleSessionPC): call task callbacks upon clearing (#2370)

modules/RTC/ScreenObtainer.js
We have implemented these changes on our application, to allow for additional control of the screen obtainer on the browser.
It may not apply to Jitsi, however I thought I would propose these changes for more control over the library.
=> feat(ScreenObtainer): add more control over screen obtainer

modules/RTC/TPCUtils.js
Fixes an issue where screenshare from Firefox appears blurry on other endpoints in the call.
=> fix(SS): Reverse the encoding order for Firefox desktop streams.

JitsiConference.js
There is no reason to wait for for the event to be emitted.
Also fixes uncaught promise error when jitsi-meet leaves the conference when the kicked event is received and then with the old code we will do a second leave which results in the uncaught promise error.
Related to https://github.com/jitsi/jitsi-meet/pull/14022 since the leave would happen in parallel with the feedback dialog and will be executed earlier.
=> fix(kicked): leave the conference immediately

modules/RTC/TPCUtils.js
Currently, it is being done only for the first video source.
=> Insert simulcast recv line for m-lines associated with all local sources on Firefox

modules/xmpp/JingleSessionPC.js
Fixes an issue when the track owner is not updated after a p2p->jvb switch right after leaving breakout room.
=> fix(ssrc-rewriting) Update the track owner correctly.

modules/RTC/CodecSelection.js
When RTCRtpReceiver.getCapabilities() is not supported by browser or if it returns an empty list. Fixes an issue where call doesn't get established in Firefox ESR 102. Fixes https://github.com/jitsi/jitsi-meet/issues/13839.
=> fix(codec-selection): Select VP8 as default codec.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
This fixes an issue when encodings for video streams are configured incorrectly after every codec switch
=> fix(video-quality): Set scaleResolutionDownBy value for every codec switch

modules/xmpp/ChatRoom.js, modules/xmpp/Lobby.js
When a self presence is received ( from mute or something else) during
leave operation, after presence unavailable is sent and before the final
presence unavaliable is received, we were interpreting it as muc joined
since the joined flag was immediately set to false.
=> fix: Double MUC_JOINED event.

modules/xmpp/xmpp.js
Firefox ESR 115 stops sending REMBs to the bridge under certain network conditions making the bridge suspend all video streams sent to the Firefox eps. It is still unclear why Firefox stops sending REMBs so enabling TCC support as workaround since TCC no longer seems to have issues with uplink BWE (uplink getting halved on every renegotiation) like in the older versions.
=> fix(video-quality) Enable TCC support for Firefox 115 and later.

JitsiMeetJS.spec.ts, JitsiMeetJS.ts, JitsiTrackErrors.spec.ts, JitsiTrackErrors.ts, modules/RTC/JitsiLocalTrack.js, types/hand-crafted/JitsiMeetJS.d.ts
We have this manually patched into our copy of lib-jitsi-meet, but thought it might be worth sharing.
This change allows applications that use lib-jitsi-meet to manually create JitiLocalTracks from some track metadata and mediastream, similar to what the library does internally, but exposing it.
We use it to create a track for our Canvas, that we then add to the conference, similar to below:
```
const canvasStream = myCanvas.captureStream(desktopShareFPS);
const newTracks = JitsiMeetJS.createLocalTracksFromMediaStreams([
{
stream: canvasStream,
sourceId: 'my:canvas',
sourceType: 'canvas',
track: canvasStream.getVideoTracks()[0],
videoType: 'desktop'
}
]);
```
This would possibly fix https://github.com/jitsi/lib-jitsi-meet/pull/1593
=> feat(RTC): add support for creating non-standard tracks

modules/util/AsyncQueue.js
Following my PR for #2370, I ran into `TypeError`s in my console where the task callback was called without being defined. The error is caught and logged so it's not critical, but it pollutes the console.
=> fix(AsyncQueue): call the callback only if it's a function (#2370)

modules/RTC/TraceablePeerConnection.js
There is a lot of additional noise when log level is set to debug, the SDP descriptions should be set to trace (As it seems it was originally intended, based on the name of the variable)
=> fix(RTC): reduce debug log noise

JitsiConference.js, modules/RTC/CodecSelection.js
Fixes an issue with audio after p2p->jvb switch when the media active state is set to false because of a setVideoCodecs call after a remote user joins the call.
=> fix(codec-selection): put Av1 support behind a flag.

package.json
The generated dts file is slightly broken, and breaks upstream projects:
```
> jitsi-meet@0.0.0 tsc:native
> tsc --noEmit --project tsconfig.native.json
node_modules/lib-jitsi-meet/types/index.d.ts:3120:20 - error TS1005: '(' expected.
3120         constructor: typeof JitsiTrackError;
~
node_modules/lib-jitsi-meet/types/index.d.ts:13832:20 - error TS1005: '(' expected.
13832         constructor: typeof JitsiConference;
~
```
=> fix(ts) don't declare types support yet

modules/xmpp/xmpp.js
last Index must be set as 0 for each time because of when _parse ConnectionFailed Message triggered twice message will be undefined.
[For more information](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex)
Example:
```js
const regex1 = new RegExp('foo', 'g');
const str1 = 'table football, foosball';
console.log('result 1: ', regex1.test(str1));
console.log('index: ', regex1.lastIndex);
console.log('result 2: ', regex1.test(str1));
console.log('index: ', regex1.lastIndex);
console.log('result 3: ', regex1.test(str1)); 
console.log('index: ', regex1.lastIndex);
```
output:
```
> "result 1: " true
> "index: " 9
> "result 2: " true
> "index: " 19
> "result 3: " false
> "index: " 0
```
=> fix: parse connectinon failed message error

JitsiConference.js
When visitors are joining or leaving (from 0 to 1 or just going to 0) we need to stop/start p2p.
=> fix: Fixes p2p and visitors.

JitsiConference.js
If the local track was not added to the conference because the participant was muted on join by focus, add it the conference instead of adding it to the media session when the user unmutes. Fixes a failing torture test case.
=> fix(JitsiConference): Check if track belongs to the conference before addition/removal.

JitsiConference.js
When tracks are not included in the initial offer/answer, remove them from the conference. Otherwise, the tracks in conference will be out of sync with those in the media sessions.
=> fix(conference): Remove the tracks that were filtered out.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js
This check is not needed anymore since we now set the correct scaleResolutionDownBy value everytime the encodings are configured. Fixes a regression on Safari where it can end up sending low resolution to a p2p peer in some cases. Also, add more unit tests for p2p desktop share cases.
=> fix(video-quality): Remove the encoding check for webkit.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, modules/connectivity/ConnectionQuality.js, modules/sdp/SdpSimulcast.ts, service/RTC/StandardVideoSettings.ts, types/hand-crafted/modules/RTC/TPCUtils.d.ts
When the client is configured to capture camera sources at 1080p or higher, adjust the bitrates and the encodings scale factor accordingly.
=> fix(video-quality): Adjust encodings bitrates/scalefactor for high capture resolutions

modules/RTC/MockClasses.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
When a local video track is muted, getSettings() on MediaStreamTrack doesn't return capture height. Fixes random torture test failures on beta.
=> fix(TPCUtils): Use track resolution instead of height.

modules/RTC/TPCUtils.js, modules/browser/BrowserCapabilities.js
Set the min. required version for Firefox to 91 so that the last 3 ESR versions are supported.
=> fix(browser-support): Impl a min. version check for Firefox.

modules/RTC/JitsiLocalTrack.js, modules/RTC/RTC.js, modules/RTC/RTCUtils.js, modules/RTC/TraceablePeerConnection.js
If MediaStreamTrack.getSettings() doesn't return the height of the track, use the constraints passed to gUM for calculating the height. Fixes an issue for Firefox/Linux which could result in media not displayed.
=> fix(JitsiLocalTRack): Calc resolution correctly.

modules/xmpp/ChatRoom.js
Will not retry immediately but will slow down request between 1 and 3 seconds.
Adds the reason string to the event we fire.
=> feat: Back off retries joining on not allowed error.

modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, service/RTC/StandardVideoSettings.ts
Check the first payload type of the m-line in remote description to get the codec used for encoding the local video source.
=> fix(video-quality): Bump up the default bitrates for 1080p and 4k.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js
When both the camera and screenshare tracks are present. Add unit tests.
=> fix(video-quality): Fix resolution of simulcast streams.

modules/RTC/JitsiLocalTrack.js, modules/RTC/MockClasses.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js
The browser returns height as 0 at track creation time. Fixes an issue where Safari's screenshare shows as black.
=> fix(RTC): Fix capture resolution for Safari desktop tracks.

modules/RTC/TraceablePeerConnection.js
Set the scalabilityMode to undefined for VP8 after a VP9->VP8 switch even though the browser returns L1T2 in the RTCRtpSender.getParameters() call. Fixes an issue where the bridge stops forwarding video for some participants after vp8->vp9 switch.
=> fix(TPC): Reset the scalabilityMode for VP8.

modules/RTC/RTC.js, modules/RTC/RTCUtils.js, modules/RTC/TraceablePeerConnection.js, types/hand-crafted/modules/RTC/RTC.d.ts, types/hand-crafted/modules/RTC/RTCUtils.d.ts
Closes #2458 
Move isUserStreamById into RTCUtils and remove not used isUserStream RTC method.
Require cycle: lib/lib-jitsi-meet/modules/RTC/RTC.js -> lib/lib-jitsi-meet/modules/RTC/TraceablePeerConnection.js -> lib/lib-jitsi-meet/modules/RTC/RTC.js
=> Fixes #2458 Circular dependency issue

modules/flags/FeatureFlags.js, modules/xmpp/SignalingLayerImpl.spec.js
Enable ssrc-rewriting by default, it can still be overwritten via config.js
=> feat(ssrc-rewriting): Enable it by default.

JitsiConference.js, JitsiConferenceEvents.ts, modules/connectivity/IceFailedHandling.js, modules/connectivity/IceFailedHandling.spec.js
This makes sure that any track operations that are executed after the terminate is sent and before the new session is established get synced up on the new session.
Also reset the JVB stats. Fixes https://github.com/jitsi/jitsi-meet/issues/14326.
=> fix(JitsiConference): Clear jingleSession after session restart.

modules/RTC/TraceablePeerConnection.js
We do not want non Chromium browsers to negotiate DD ext headers when VP8/VP9 is the selected codec. Fixes poor video quality issue for Safari when Av1 is offered by Jicofo.
=> fix(TPC): Run the DD ext header check on all browsers.

JitsiConference.js
The tracks should get removed if the startAudioMuted/startVideoMuted flags are set for the conference. Fixes the failing startMuted testcase.
=> fix(tracks): Do not filter the tracks for p2p.

modules/sdp/LocalSdpMunger.js
Chrome 122 does not generate a 'msid' attribute in the local SDP when a local source is added after the user joins muted. The SSRC doesn't get signaled to remote p2p peer when this happens. Also, when the direction of the transceiver changes from 'sendonly' to 'sendrecv', Chrome is generating a new set of SSRCs resulting the client sending out a source-remove followed by source-add. Fixes various p2p related bugs that have surfaced in p2p calls where both the endpoints are running Chromium 122.
=> fix(SDP): Generate msid attr for source when browser doesn't produce one.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js
1. fix(TPCUtils): Chain both RTCRtpSender getParameters and setParameters call properly.
Firefox 123 started throwing an error when the transaction ids for getParameters and setParameters don't match. This can result in Firefox not establishing a p2p connection with a remote peer when it is the offerer.
2. fix(TPC): Do not run the DD Header Ext check on Firefox as it doesn't support it currently.
=> Fix firefox issues

JitsiConference.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, modules/RTC/CodecSelection.js
Include visitor codecs published by Jicofo while calculating the intersection set for the conference.
=> fix(codec-selection): Include visitor codecs.

package.json, webpack-shared-config.js
this moves the determination of the git commit to webpack-shared-config LIB_JITSI_MEET_COMMIT_HASH is still kept for backward compatibility
fix(build) in case git fails use development
=> feat(build) remove export from build script

JitsiConference.js, modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
Also fixes the issue with video freezing after video mute and unmute when the user joins the call with `config.startSilent=true`.
=> fix(TPC): reconfigure the encodings to suspend/resume media after jvb<->p2p switch.

JitsiMeetJS.ts
Also drop deprecated settings.
=> fix(JitsiMeetJS) cleanup createLocalTracks docs

modules/flags/FeatureFlags.js
We are going to work on making the tracks API backwards compatible and
re-enable it in the near future.
=> fix(flags) don't enable SSRC rewriting by default

JitsiConnectionEvents.spec.ts, JitsiConnectionEvents.ts, modules/xmpp/xmpp.js
Used for shard and region values coming from the backend.
=> feat: Introduces connection event for custom properties.

modules/statistics/LocalStatsCollector.js, modules/statistics/statistics.js
Creating the AudioContext at import time means a warning line is printed in the JS console even before the user has a chance of initializing the library, which is weird.
There is no harm in initializing it in init since it's the first thing the user needs to do in order to use the library.
=> fix(statistics) initialize LocalStatsCollector on Statistics.init

modules/RTC/TraceablePeerConnection.js
This is needed when p2p conn establishes before jvb and no sender constraints have been received before media on jvb conn is suspended.
=> fix(TPC): Use a default maxHeight for configuring encodings.

modules/RTC/RTCUtils.js
webrtc-adapter transforms "deviceId": "foo" to "deviceId": { ideal: "foo"}.
This makes the camera non-selectable if the resolution constraints are not met.
Setting the constraint to exact will sidestep that adapter behavior, and express stronger intent.
=> fix(rtc) use exact deviceId constraints

modules/xmpp/ChatRoom.js
The interval will be between 1.5 and 7.1 seconds.
=> fix: Bumps retry interval for http conference requests.

modules/xmpp/ChatRoom.js, modules/xmpp/moderator.js
This changes the behavior of retires when Room creation restricted error is received, we will always send the conference request to jicofo when retrying.
Also, after error for password protected rooms and providing password, a conference request was not send which can result jicofo left the room and error is received.
=> fix: Sends conference requests on retries of errors.

modules/proxyconnection/ProxyConnectionPC.js
When addCancellableListener was introduced we missed to stub it here.
=> fix(ProxyConnectionPC) fix after API change in Listenable

JitsiConference.js, modules/RTC/CodecSelection.js
Depends on https://github.com/jitsi/jicofo/pull/1150
=> fix(codec-selection): Enable AV1 by default

modules/xmpp/ResumeTask.js
=> Avoid adding multiple NETWORK_INFO_EVENT events causing memory leak.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiTrackEvents.spec.ts, JitsiTrackEvents.ts, modules/RTC/JitsiRemoteTrack.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js
When an existing SSRC for a remote track gets re-mapped from one source to another, fire a TRACK_REMOVED event followed by TRACK_ADDED event instead of TRACK_OWNER_CHANGED event. This should simplify the application logic for track handling when SSRC rewriting is enabled.
=> ref(ssrc-rewriting): Fire track removed/added instead of owner changed.

modules/RTC/TraceablePeerConnection.js
Fixes an issues where microphone change for Safari fails.
=> fix(TPC): Do not reconfigure the encodings for Safari audio.

JitsiConferenceEventManager.js, modules/xmpp/JingleSessionPC.js
When the bridge WS is re-established, JVB sends the full map of audio and video sources. Without the check, the library will end up firing TRACK_REMOVED and TRACK_ADDED for all the exiting tracks. Also, process audio and video source maps only on JVB sessions.
=> fix(ssrc-rewriting): Check for track owner/sourceName before calling TRACK_OWNER_SET.

types/hand-crafted/modules/RTC/JitsiRemoteTrack.d.ts, types/hand-crafted/modules/RTC/JitsiTrack.d.ts
There's a field `jitsiTrack.conference` that keeps a reference to the track's owning conference. It does not have a corresponding TypeScript definition. This PR adds a type definition.
- `JitsiLocalTrack.conference`: `null` if it hasn't been added to a conference yet
- `JitsiRemoteTrack.conference`: non-nullable, always associated with a conference
(We're using this in our application.)
=> Expose `track.conference` field in types

modules/xmpp/JingleSessionPC.js
Fixes missing audio issue when the bridge resends the full audio map even before the track for the SSRCs signaled before are created. This is possible when the RTP packets race with the thread that completed the websocket connection.
=> fix(ssrc-rewriting): Check if track exists before updating owner/sourceName.

modules/xmpp/ResumeTask.js
In RN, an uncaught exception causes the app to crash in release builds. We sidestep that on the native side, but RN SDK users usually don't, so be gracefull.
Fixes: https://github.com/jitsi/jitsi-meet/issues/14728
Fixes: https://github.com/jitsi/jitsi-meet/issues/14399
=> fix(xmpp) catch errors in XMPP session resumption

JitsiMediaDevicesEvents.spec.ts, JitsiMediaDevicesEvents.ts, JitsiMeetJS.ts, types/hand-crafted/JitsiMediaDevicesEvents.d.ts
It's better handled by the application layer anyway.
=> feat(createLocalTracks) drop unused slow gUM event

JitsiMeetJS.ts
They have been deprecated and printing a warning for at least 7 years.
=> feat(JitsiMeetJS) drop deprecated APIs

JitsiMediaDevices.js, JitsiMeetJS.ts
It's very odd to start receiving events and logs about device changes when lib-jitsi-meet has not been initialized yet.
Delay initialization until JitsiMeetJS.init has been called, which is the very first thing users need to call anyway.
=> feat(JitsiMediaDevices) don't initialize in the constructor

modules/RTC/TPCUtils.spec.js, service/RTC/StandardVideoSettings.ts
The browser is downsampling the resolution since the current default bitrates for H.264 are very conservative.
=> fix(video-quality): Bump up the default bitrates for H.264.

modules/RTC/RTC.js
Claiming there is no support for it is misleading, the user might have called the function before the channel was initialized.
=> fix(RTC) improve bridge channel not being available error

modules/RTC/JitsiLocalTrack.js
We are already handling Safari, which provides an empty constraints object. Handle any type of broken constraints object which doesn't have at least a `width` and `height` properties. This is the case of Firefox when "fingerprint resistence" is enabled.
Fixes: https://github.com/jitsi/jitsi-meet/issues/14609
=> fix(JitsiLocalTrack) handle broken constraints more gracefully

modules/RTC/JitsiLocalTrack.js, modules/RTC/JitsiTrack.js, modules/RTC/TraceablePeerConnection.js
This helps us in identifying the video codec associated with a local video track for codec selection torture tests.
=> fix(JitsiLocalTrack) Keep a reference to SSRC.

modules/RTC/TraceablePeerConnection.js
Fixes low resolution video from Spot running older electron versions when the codec changes from VP9->VP8->VP9.
=> fix(video-quality) Reset scale factor and bitrates for VP9 K-SVC.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, modules/RTC/CodecSelection.js, modules/RTC/CodecSelection.spec.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/statistics/RTPStatsCollector.js, modules/statistics/statistics.js, modules/xmpp/JingleSessionPC.js, service/statistics/Events.spec.ts, service/statistics/Events.ts
https://github.com/w3ctag/design-reviews/issues/836. This allows the client to seamlessly switch between the codecs without having to trigger a renegotiation. This feature is behind the flag testing.enableCodecSelectionAPI in config.js
This is marked WIP since we need a JVB change for this feature to work as expected for all codecs. When the DD header extension headers are negotiated, Chrome includes the layer information for VP8 in the DD extension headers but the bridge currently reads this from the VP8 packet headers. Since renegotiation cycle is not triggered when this feature is enabled, client doesn't have a way of removing the DDs from being sent by Chrome when we switch to VP8. - this has been fixed in https://github.com/jitsi/jitsi-videobridge/pull/2136
=> feat(codec-selection): Use the new codec selection API

modules/xmpp/JingleSessionPC.js
We need the initial invite/answer to have the codecs in the correct order so codec selection API for selecting codecs is not useful in this case.
=> fix(codecs) Continue to munge SDP for p2p codec.

modules/RTC/RTCUtils.js
This prevents the browser from starting the camera at 60 fps wherever supported as this could drastically affect the cpu load and result in poor experience.
=> fix(RTCUtils) Apply default frameRate constraints.

JitsiConferenceEventManager.js, modules/xmpp/ChatRoom.js
- messageId needs to be added to be able to attach reactions to specific messages
- participantId indicates that it is the participant's id rather than the message's id
=> fix(chat-features): Add messageId and change id to participantId

JitsiConference.js, modules/RTC/MockClasses.js, modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, modules/connectivity/ConnectionQuality.js, modules/qualitycontrol/CodecSelection.js, modules/qualitycontrol/CodecSelection.spec.js, modules/qualitycontrol/MockClasses.ts, modules/qualitycontrol/QualityController.spec.js, modules/qualitycontrol/QualityController.ts, modules/qualitycontrol/ReceiveVideoController.js, modules/sdp/SdpSimulcast.ts, service/RTC/StandardVideoQualitySettings.ts
Impl a recovery mechanism for the lastN to be increased if the cpu limitation goes away and doesn't return after increasing lastN. Also, additionally improve the calculation of the expected resolution taking simulcast stream resolutions into account.
=> ref(QualityController) Add recovery mechanism and adjust the resolution check.

modules/xmpp/JingleSessionPC.js
When WebRTC ICE gathering policy is set to gather once instead of continually, the controlling agent goes to completed instead of connected (no more candidates to check). This doesn't happen in Chrome or other browsers, but is reproducible with node.js wrapper around WebRTC which runs with the default settings.
This is causing a bug where the initiator side of a P2P connection does not fully switch to P2P mode and keeps on sending data on both P2P and JVB connections.
=> fix(ICE): treat completed as connected

modules/qualitycontrol/ReceiveVideoController.js
When lastN is first set to some truty value and then 0, it wouldn't be set because we relied on a "truthyness" check.
Check if the value is undefined so it can be set to 0.
=> fix(ReceiveVideoController) fix setting lastN to 0

JitsiConference.js
There is no hardm in calling it twice since we protect against it.
=> fix(JitsiConference) handle repeaded calls to leave gracefully

modules/xmpp/ResumeTask.js
It will avoid having an extra "Canceling connection resume task" log line every time we schedule a timer.
=> fix(ResumeTask) reset resume timeout after running timer

modules/xmpp/xmpp.js
When using bosh and xmpp conference-request (no jiconop on server-side) we can drop av moderation and speaker-stats messages.
=> fix(xmpp): Fixes skipping messages when disco-info is processed late.

modules/RTC/RTC.js, modules/qualitycontrol/QualityController.ts
Checking for send resolution vs expected resolution was unnecessarily limiting lastN and receive resolution when local camera has issues and stops sending video. Also, do not send redundant receiver constraints on the bridge channel.
=> fix(quality-control) Check only for cpu limitation

modules/xmpp/RoomMetadata.ts
Leaves up to the backend to process or not process them.
=> fix(metadata): Allows non moderators to send values.

modules/RTC/TraceablePeerConnection.js
This was needed in older versions since the browser didn't apply maxBitrates from RTCRtpEncoderParameters on the encoder. In the newer versions this seems to be no longer the case. Also, when the codec selection API is used, we no longer renegotiate locally so if we switched codec from AV1->VP9-VP9, the AV1 bitrate setting in the SDP will still be effective resulting in a lower send resolution because of b/w limitation.
=> fix(quality) Do not set b:AS line in SDP for SVC codecs when codec selection API is used.

JitsiTranscriptionStatus.spec.ts, JitsiTranscriptionStatus.ts, types/hand-crafted/JitsiTranscriptionStatus.d.ts
The backend really sends upper case values:
https://github.com/jitsi/jitsi-xmpp-extensions/blob/3816e5a154160056290c2a2fbff1ab63cbac95e0/src/main/java/org/jitsi/xmpp/extensions/jitsimeet/TranscriptionStatusExtension.java#L82
=> fix(JitsiTranscriptionStatus): the status values are upper case

JitsiMeetJS.ts
We were setting the logging level in JitsiMeetJS.init which potentially would have overriden all external calls for setting the log level before the JitsiMeetJS.init is called. In fact this was happening for jitsi-meet.
=> fix(logging): Set default logging level as early as possible.

modules/browser/BrowserCapabilities.js
Calling this API on Firefox is causing freezes when the local endpoint is the answerer. https://bugzilla.mozilla.org/show_bug.cgi?id=1917800
=> fix(TPC) Do not call setCodecPreferences on Firefox.

JitsiConference.js, JitsiConferenceEventManager.js, modules/connectivity/IceFailedHandling.js, modules/connectivity/IceFailedHandling.spec.js, modules/proxyconnection/ProxyConnectionPC.js, modules/xmpp/ChatRoom.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/strophe.jingle.js, service/statistics/AnalyticsEvents.spec.ts, service/statistics/AnalyticsEvents.ts, service/xmpp/XMPPEvents.spec.ts, service/xmpp/XMPPEvents.ts, types/hand-crafted/JitsiConference.d.ts, types/hand-crafted/modules/xmpp/ChatRoom.d.ts, types/hand-crafted/modules/xmpp/JingleSessionPC.d.ts, types/hand-crafted/service/statistics/AnalyticsEvents.d.ts, types/hand-crafted/service/xmpp/XMPPEvents.d.ts
Reinvite method in Jicofo is set to restart-jingle (terminate and recreate the whole jingle session) instead of sending 'transport-replace'. The replaceTransport option has never worked because of a bug in Chrome related to TCC sequence numbering after the DTLS transport layer is reset to start a new DTLS handshake with fresh transport on the bride.
=> fix(JingleSession) Remove ice restart option and functionality.

JitsiConferenceEventManager.js, JitsiParticipant.js, modules/xmpp/ChatRoom.js
=> fix(ChatRoom) refactor handling of participant properties

modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleHelperFunctions.js, modules/xmpp/JingleSessionPC.js
If 'source-add' for a remote video source is received before presence for that source, videoType will default to 'camera' and the client wouldn't be able to create the virtual participant tile for rendering the desktop track.
=> fix(TPC) Use videoType from 'source-add' for remote track creation.

modules/RTC/TPCUtils.js, modules/RTC/TPCUtils.spec.js, modules/RTC/TraceablePeerConnection.js, modules/sdp/LocalSdpMunger.js, modules/sdp/SdpSimulcast.ts, modules/xmpp/JingleSessionPC.js, types/hand-crafted/modules/RTC/TPCUtils.d.ts
Move all utility functions to TPCUtils that include
1. munging the SDP.
2. getting current codecs
3. getting expected transceiver direction.
4. getting expected settings for video encodings.
Move all functions that call RTCPeerConnection APIs directly back to TPC.
=> ref(TPC) Move all the utility functions to TPCUtils.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/statistics/RTPStatsCollector.js
Regression was introduced in https://github.com/jitsi/lib-jitsi-meet/commit/07f037e12ed7ced3ba5b1bc6be1cb58dff61789d. Also process encodeTime stats when H.264 is selected
=> fix(TPC) Fix H.264 simulcast.

modules/browser/BrowserCapabilities.js
Some so called "security" browser extensions override WebRTC APIs so even if the UA string suggests the browser is supported, it won't work.
Coincidentally, this should also mark Safari in Lockdown Mode as unsupported, since the WebRTC APIs are not available in that case.
=> fix(browser) detect WebRTC APIs and mark browser unsupported if not

JitsiMeetJS.ts, modules/RTC/RTC.js, modules/RTC/RTCUtils.js, types/hand-crafted/JitsiMeetJS.d.ts, types/hand-crafted/modules/RTC/RTC.d.ts, types/hand-crafted/modules/RTC/RTCUtils.d.ts
It was never accurate since browsers have changed their behavior over time and can be implemented in the application more reliably.
=> feat(RTC) drop PERMISSION_PROMPT_IS_SHOWN event

JitsiTrackError.js, modules/RTC/ScreenObtainer.js, modules/proxyconnection/ProxyConnectionPC.js, modules/proxyconnection/ProxyConnectionService.js
Don't show the misleading "user cancelled" error, there are corner cases in which a different error can be manifested.
=> fix(gDM) handle NotReadableError

modules/xmpp/JingleSessionPC.js
Avoids having any actual remote audio tracks, which can mess with the mobile audio session.
=> fix(JPC) skip processing remote audio sources when startSilent

modules/RTC/ScreenObtainer.js
This PR allows Electron to use getDisplayMedia, its hidden behind a flag `electronUseGetDisplayMedia`.
If there's a better place for the flag, or naming convention, do let me know.
Later on I assume you will be deprecating the old method, and it'll be a flag to use the old method, before removing it entirely?
Closes #2597
=> Allow Electron to use getDisplayMedia

modules/sdp/LocalSdpMunger.js, modules/sdp/LocalSdpMunger.spec.js
Without the trackID in a=ssrc lines in SDP, older versions of Chrome (108) reject the remote description resulting in endpoint getting kicked out of the conference.
=> fix(SDP) Include the trackId in the signaled msid for the source.

modules/xmpp/xmpp.js
Jigasi / Jitsi (desktop) seems to encode apostrophes like (&apos or &#39) for instance.
This is notably visible in the subtitles.
Normalize it so it's plain UTF-8.
=> fix(xmpp) unescape HTML entities in JSON messages

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/qualitycontrol/CodecSelection.spec.js, modules/qualitycontrol/QualityController.spec.js, modules/qualitycontrol/QualityController.ts, modules/xmpp/JingleSessionPC.js
Calculate codec intersection set only once per second even when there is a burst of joins/leaves. Also, check for current codec before chaining a codec change operation when codec selection API is used.
=> fix(codec) Debounce the call that calc codec intersection set.

JitsiConference.js
This should be supported by the backend. This limitation was added here only because of track synchronization issues between JM and LJM. The support is added behind testing.allowMultipleTracks config.js setting. Fixes https://github.com/jitsi/lib-jitsi-meet/issues/2205
=> feat(JitsiConference) Allow adding multiple tracks to the conference.

modules/RTC/ScreenObtainer.js
If the enclosing Jitsi Meet app declares gDM in Electron is supported, ignore the `electronUseGetDisplayMedia` config flag and use the gDM flow. This facilitates having backwards compatibility since the Electron app won't know if the deployment it's about to join has the gDM flow support or not.
=> feat(ScreenObtainer) add fallback option for Electron

JitsiTrackError.js, JitsiTrackErrors.spec.ts, JitsiTrackErrors.ts, modules/RTC/ScreenObtainer.js
Detect if gDM support has been enabled and fallback to the previous gUM flow otherwise.
=> fix(ScreenObtainer) fix using gDM with old Electron clients

modules/sdp/SDP.js
Reconstruct the msid to include both streamId and trackId if its missing from the source signaling. Fixes issue on Chromium < 117 where the remote offer gets rejected and the client gets kicked out of the call.
=> fix(SDP) Inject trackID if missing from signaled source info.

modules/RTC/ScreenObtainer.js
Wrong check for unsupported getDisplayMedia when starting screen sharing will cause the app to never fallback to getUserMedia flow. This breaks screen sharing for all old electron clients that do not support getDisplayMedia.
=> fix(electron): Check for unsuported gDM

modules/RTC/TPCUtils.js
Aparently we call this for all tracks including for the audio tracks and it is failing with JS error. This leads to "participant unable to unmute".
=> fix(TPCUtils): handle missing codec in  isRunningInSimulcastMode.

modules/qualitycontrol/CodecSelection.js, modules/qualitycontrol/QualityController.ts, modules/xmpp/JingleSessionPC.js
This is done in code for desktop clients. Mobile clients will continue to encode VP8 by default
=> feat: Set AV1 as the preferred video codec.

modules/connectivity/ConnectionQuality.js
Do not overwrite the packet loss value when video muted. RTCP termination for audio was implemented a while back. This hack is no longer needed.
=> fix(connectivity) Do not overwrite the packet loss value when video muted.

modules/RTC/MockClasses.ts
- Add Getters and Setters: Implement getters and setters for the properties in the MockPeerConnection and MockRTC classes.
- Update createPeerConnection Method: Ensure it accepts parameters for id, usesUnifiedPlan, and simulcast.
=> Migrated `modules/rtc/MockClasses`

modules/settings/Settings.js
Note the format changes, is that important?
=> fix(Settings) use a proper UUID rather than hand-rolling it

JitsiConference.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, modules/RTC/TraceablePeerConnection.js, modules/connectivity/ConnectionQuality.js, modules/xmpp/JingleSessionPC.js, modules/xmpp/MediaSessionEvents.spec.ts, modules/xmpp/MediaSessionEvents.ts
Trigger ramp up on codec and session changes.
This should prevent connection quality GSM bars turning red for video codec changes and when the call switches between jvb and p2p connection.
=> fix(connection-quality) Trigger ramp up on codec and session changes.

modules/settings/Settings.ts
=> Migrating `modules/settings/Settings`

JitsiConnection.js, JitsiMeetJS.ts, modules/RTCStats/DefaulLogStorage.ts, modules/RTCStats/RTCStats.ts, modules/RTCStats/interfaces.ts, modules/statistics/statistics.js
Push rtcstats initialization when JitsiConnection is created.
This will allow us to capture logs occurring before the JitsiConference has actually connected.
Depends on https://github.com/jitsi/jitsi-meet/pull/15838
=> feat(rtcstats): early rtcstats initialization

modules/xmpp/ChatRoom.js
Having it before can result in iframeAPI receiving this event for unknown user as the local user id is sent after that with videoconferenceJoined which is based on MUC_JOINED.
=> fix(xmpp): Moves event local user role changed after muc joined.

modules/RTC/RTCUtils.js, modules/RTC/ScreenObtainer.js
This is only permitted when testing.testMode=true in config.js
=> feat(ScreenObtainer) Allow SS resolution to be re-configured.

modules/e2ee/Context.js, modules/e2ee/Context.spec.js, modules/e2ee/E2EEContext.js, modules/e2ee/KeyHandler.js, modules/e2ee/ManagedKeyHandler.js, modules/e2ee/Worker.js
After enabling E2EE for the first time, keep the media transform inplace, but make it a no-op.
This simplifies the flow a little since it doesn't require a media session restart.
Way back when, there were performance concerns when having a transform, which is what prompted us to implement the restar mechanism, but a lot has changed since and both audio and video frames don't need to jump threads these days. We are still not enabling an empty transform at all times out of precaution.
=> fix(e2ee) avoid restarting media sessions more than once

JitsiConnection.ts, modules/RTCStats/RTCStats.ts, modules/RTCStats/interfaces.ts, modules/statistics/statistics.js
LJM no longer proxies RTCPeerConnection so we can move the rtcstats initialization process in a more convenient place.
Also it seems that the recent migration to .ts of the JitsiConnection module removed the       `RTCStats.startWithConnection(this)` call, disabling rtcstats, re added that.
=> feat(rtcstats): move rtcstats init

JitsiConference.js, modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/browser/BrowserCapabilities.js, modules/qualitycontrol/CodecSelection.js, service/RTC/StandardVideoQualitySettings.ts
Disables AV1 and VP9 for FF due to scalability not working. Also in order to make VP8 scalability to work, DD extension headers had to be disabled.
=> fix(FF): scalability.

modules/RTC/TPCUtils.js, modules/RTC/TraceablePeerConnection.js, modules/qualitycontrol/CodecSelection.js
The bridge is now able to use DD headers for VP8 and VP9 as well so there is no need to remove it from remote desc when the call switches from AV1 to VP8/VP9.
=> fix(codec) Always use DD when its supported by Jicofo and browser.

modules/RTC/ScreenObtainer.js
It appears that when the gDM flow is used we do not set properly the sourceId of the shared stream.  When the user has multiple screens we use the sourceId to identify the display that is currently shared. Therefore in electron we can't identify the display that is used and we fail.
=> fix(remoteControl): Failure to start

JitsiConference.js, JitsiConferenceEventManager.js, modules/RTC/TraceablePeerConnection.js, modules/xmpp/JingleSessionPC.js, service/RTC/RTCEvents.spec.ts, service/RTC/RTCEvents.ts, service/xmpp/XMPPEvents.spec.ts, service/xmpp/XMPPEvents.ts, types/hand-crafted/service/RTC/RTCEvents.d.ts, types/hand-crafted/service/xmpp/XMPPEvents.d.ts
Once the session has been established, reneg errors are not fatal. Any reneg failure resulting in failure to add local devices will be notified to the end user anyways.
Also, reload the client when Jicofo rejects the session-accept from a client so that it doesn't stay in the conference with no media.
=> fix(Conference) Do not kick endpoint out on renegotiation errors.

JitsiConference.js, JitsiConferenceEventManager.js, JitsiConferenceEvents.spec.ts, JitsiConferenceEvents.ts, modules/RTC/JitsiLocalTrack.js, modules/xmpp/RoomMetadata.ts, modules/xmpp/strophe.jingle.js, modules/xmpp/xmpp.js, service/xmpp/XMPPEvents.spec.ts, service/xmpp/XMPPEvents.ts, types/hand-crafted/JitsiConference.d.ts, types/hand-crafted/JitsiConferenceEvents.d.ts, types/hand-crafted/service/xmpp/XMPPEvents.d.ts
If the user changes mute state after joining the call and before the other participats join the call, make sure those state changes are honored.
=> fix(conference) Fix different bugs with startMuted policy.

modules/xmpp/ChatRoom.js
Reason: metadata is now sent in presence on join, no need to read it from both places
=> feat(metadata): Drops reading from room data form.

modules/RTC/TraceablePeerConnection.js
When a remote user does a ICE restart and a source-remove followed by source-add is received for its sources, mute event on new remote track may not be fired if the old track hasn't been disposed yet.
=> fix(TPC) Fire mute event on the correct track.

modules/videosipgw/JitsiVideoSIPGWSession.ts
Fixes #2637 
- Changed type of listener from function to EventListener 
`Argument of type 'Function' is not assignable to parameter of type 'EventListener'.
Type 'Function' provides no match for the signature '(...args: any[]): void'.ts(`
=> Migrate `modules\videosipgw\JitsiVideoSIPGWSession.ts`

modules/RTC/JitsiRemoteTrack.js, modules/RTC/TraceablePeerConnection.js, modules/statistics/AvgRTPStatsReporter.ts
Regression caused by https://github.com/jitsi/lib-jitsi-meet/commit/b6142c7078637b8c24d0a7e2039c2e1dec96e230. Ideally, JitsiRemoteTrack should be overriding 'getSsrc'.
=> fix(JitsiTrack) Return correct SSRC, fixes missing remote stats.

JitsiConference.ts, JitsiMediaDevices.ts, JitsiMeetJS.ts, modules/util/Listenable.ts, package-lock.json, package.json, tsconfig.json
- Avoid "default" named constants due to our use of default exports
- Fix JitsiMediaDevices docs not showing up
- Export Listenable since many objects inherit from it
- Hide Listenable members in descendant classes
- Tweak visibility of JitsiMediaDevices members
Some samples about the "default" variables:
Before:
After:
=> fix(typedoc) improve generated TypeDoc documentation

package-lock.json, package.json, tsconfig.json
In JitsiMeetJS for example, we expose a lot of this which we are not listing as entrypoints so TypeDoc is not documenting them.
It will now.
We shall now go through the exported symbols gradually and annotate the properties we think should be internal / private.
=> feat(typedoc) document all related types even if not explciitly exported

JitsiConference.spec.ts, JitsiConference.ts, JitsiConferenceEventManager.ts, modules/xmpp/ChatRoom.spec.ts, modules/xmpp/ChatRoom.ts
Added optional replyToId parameter in JitsiConference.ts sendMessage method.
Updated ChatRoom.ts to parse incoming reply messages and extract replyToId.
Emitted replyToId in events via JitsiConferenceEventManager.ts.
Maintains backward compatibility for non-reply messages.
Minimal and focused changes; no unrelated formatting or file changes.
=> feat: add XEP-0461 message reply support
