jitsi/lib-jitsi-meet

- JitsiConference.js
- JitsiConferenceEvents.js
- doc/API.md
- modules/statistics/RTPStatsCollector.js
- modules/statistics/statistics.js
- service/statistics/Events.js
* process peer connection stats in RTPStatsCollector
* propagate CONNECTION_STATS conference event
> use statistics module to process peer connection statistics

- modules/xmpp/moderator.js
'this' is the Window, 'self' is the Moderator
> Partially fix authenticated conference

- JitsiConference.js
- modules/RTC/ScreenObtainer.js
Return promise in JitsiConference in addTrack and removeTrack methods.
> Return promise in addTrack and removeTrack

- JitsiConference.js
This fixes issue
1) add video stream 1
2) mute video stream 1
3) remove video stream 1
4) add video stream 2 (not muted)
5) other users still think that we're muted
> update "is muted" state in presence when adding new track

- modules/RTC/RTCUIHelper.js
add helper for torture tests to extract stream id from the video element
> add helper to extract stream id from the video element

- modules/RTC/RTC.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/TraceablePeerConnection.js
This PR should fix the torture tests, some issues with remote participants without video elements, video mute issues, etc. It also optimizes the number of initially sent jingle packets.
> Fixes the sources in session-accept jingle packets. Fixes issue with not replacing unmuted SSRCs in the SDP.

- modules/RTC/RTCBrowserType.js
- modules/RTC/RTCUtils.js
- modules/RTC/ScreenObtainer.js
* detect NW.js app by user-agent
* use injected function for desktop sharing
> integration with NW.js

- JitsiConference.js
- JitsiConferenceErrors.js
- doc/API.md
- modules/xmpp/ChatRoom.js
- service/xmpp/XMPPEvents.js
Implements CONFERENCE_MAX_USERS conference error to be fired when the room already reached the maximum users limit.
> Adds CONFERENCE_MAX_USERS conference error.

- JitsiConference.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSession.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.jingle.js
- service/xmpp/XMPPEvents.js
This PR removes scenarios and methods which are not used in jitsi-meet.
Does not accept session-initiate from non-focus users.
Cleanups error handling logic.
> Strophe cleanup

- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SDP.js
- modules/xmpp/SDPUtil.js
Commit 7cf5191 gives a comprehensive explanation (in the form of a source code comment) of the need for this PR. While the modifications should work with current revisions of Videobridge, the fix they represent will be activated by a Videobridge running https://github.com/jitsi/jitsi-videobridge/pull/191.
> Fix early DTLS

- modules/xmpp/ChatRoom.js
- modules/xmpp/SDP.js
- modules/xmpp/moderator.js
Reduces the (TIME) from "strophe CONNECTED" to "muc joined" by explicitly flushing Strophe's connection.
Additionally, attempts to improve the performance of the JavaScript source code.
> Reduce MUC joined time

- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.jingle.js
This PR will restart the conference on new JVB by handling 'transport-replace' Jingle IQ which contains transport for the channels allocated on a new bridge.
> Ice restart

- JitsiConference.js
- JitsiMeetJS.js
- doc/API.md
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
Adds global error handler function and option to auto enable it. Reports unhandled exceptions catched by error handler through callstats.
> Global error handler and reporting those errors.

- modules/statistics/CallStats.js
Fixes the function name was signallingError now it is signalingError (single l).
> Fixes callstats wrtcFuncNames signalingError.

- doc/API.md
- modules/RTC/RTCUtils.js
This PR makes it possible to set a maximum frame rate constraint when requesting a video stream.
> Add maxFps option for requesting video

- JitsiConference.js
- JitsiConferenceEvents.js
- JitsiConnectionEvents.js
- JitsiTrackErrors.js
- modules/RTC/RTCUtils.js
- modules/settings/Settings.js
- modules/xmpp/SDPUtil.js
- modules/xmpp/strophe.jingle.js
- modules/xmpp/strophe.ping.js
- modules/xmpp/strophe.rayo.js
- modules/xmpp/xmpp.js
This is a collection of commits which fix issues that I've stumbled upon while porting lib-jitsi-meet to React Native. They should not contain anything that is exclusively specific to and/or mentions React Native but are rather issues that may cause problems when executing in a JavaScript environment that's outside of a Web browser.
> Prepare for React Native

- JitsiConference.js
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
- modules/xmpp/JingleSessionPC.js
- service/xmpp/XMPPEvents.js
Removes fabricSetupFailed and adds iceConnectionFailure for callstats.
> Removes fabricSetupFailed.

- JitsiConference.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTC.js
- service/RTC/RTCEvents.js
We don’t need the fake video tracks anymore. We are always receiving tracks even if the track is muted.
> Removes fake video tracks from the code

- modules/RTC/RTCBrowserType.js
- modules/RTC/RTCUtils.js
- modules/statistics/RTPStatsCollector.js
- modules/xmpp/TraceablePeerConnection.js
Emil requested the merging of the react-native branch into master.
> Add initial support for React Native

- JitsiConference.js
- modules/RTC/RTCUtils.js
- modules/statistics/statistics.js
- modules/xmpp/moderator.js
- modules/xmpp/strophe.jingle.js
- modules/xmpp/xmpp.js
Adds config options required for lip-sync tests
> Lipsync tests

- JitsiConference.js
- connection_optimization/external_connect.js
- modules/statistics/statistics.js
- modules/version/ComponentsVersions.js
Logs versions of components and library version. Logs shard and region if available.
> Sends additional logs to callstats.

- package.json
Bumps the sdp-simulcast version to 0.1.7 that fixes issues related to SSRC
management.
> Bumps sdp-simulcast version.

- JitsiConference.js
- JitsiMediaDevices.js
- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
- service/RTC/RTCEvents.js
Also fixes callstats initialization, changes a deprecated fabric event. Fixes logging recorder states.
> Logs active devices to callstats (updated).

- JitsiMediaDevices.js
Needs an additional check for available devices after merging https://github.com/jitsi/lib-jitsi-meet/pull/139.
> Adds additional check, avoids undefined error.

- JitsiConference.js
Fire CONFERENCE_LEFT event after conference is left
> Fire CONFERENCE_LEFT event after conference is left

- JitsiConference.js
- modules/RTC/DataChannels.js
- modules/RTC/RTC.js
- modules/xmpp/JingleSessionPC.js
- package.json
- service/xmpp/XMPPEvents.js
Logs ICE ufrags to callstats. Exposes the "application log" callstats functionality.
> Adds more logs and clean up.

- JitsiMeetJS.js
- modules/util/AuthUtil.js
- modules/xmpp/xmpp.js
Required for https://github.com/jitsi/jitsi-meet/pull/728
> Jwt login service 2

- modules/xmpp/recording.js
Required for https://github.com/jitsi/jitsi-meet/pull/719
> Add RETRYING Jibri status

- modules/xmpp/moderator.js
Part of https://github.com/jitsi/jicofo/pull/103
> Shared document using room name config

- JitsiConference.js
- JitsiConferenceEventManager.js
- JitsiConferenceEvents.js
- doc/API.md
- modules/RTC/DataChannels.js
- modules/RTC/RTC.js
- service/RTC/RTCEvents.js
Reverts jitsi/lib-jitsi-meet#181
> Revert "Implements interfaces for data channel communication"

- modules/xmpp/ChatRoom.js
Handles the case where we can receive the presence with the video type before we have received and created the remote track.
> Handles videoType from last received presence.

- JitsiConference.js
- JitsiConferenceEventManager.js
- JitsiConnection.js
- modules/statistics/AnalyticsAdapter.js
- modules/statistics/statistics.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/moderator.js
- modules/xmpp/strophe.emuc.js
- modules/xmpp/xmpp.js
- service/xmpp/XMPPEvents.js
And adds additional analytics events for some connection errors.
> Removes reloads

- JitsiConference.js
- JitsiConferenceEventManager.js
- JitsiMeetJS.js
- modules/transcription/audioRecorder.js
- modules/transcription/recordingResult.js
- modules/transcription/transcriber.js
- modules/transcription/transcriberHolder.js
- modules/transcription/transcriptionServices/AbstractTranscriptionService.js
- modules/transcription/transcriptionServices/SphinxTranscriptionService.js
- modules/transcription/word.js
Adds a transcription module 
The transcription module currently used a Sphinx server to send the audio to:
https://github.com/jitsi/Sphinx4-HTTP-server
This code requires the URL of the server to be set in config.js of Jitsi Meet as 
`sphinxURL: "<URL here>"`
> Transcriptions

- .gitignore
- JitsiConferenceEventManager.js
- JitsiConferenceEvents.js
- modules/xmpp/ChatRoom.js
- service/xmpp/XMPPEvents.js
Ready for review.
/cc @hristoterezov
> Update lock icon on config change

- modules/statistics/AnalyticsAdapter.js
Passing the browser name as parameter.
> Removes browser suffix adding to all action names.

- modules/RTC/RTCUtils.js
Fixes resolving this when passing function after enabling es6.
> Fixes desktop sharing.

- modules/RTC/JitsiLocalTrack.js
It turned out that the code for adding the local tracks when session-initiate is received (https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L816) is executed somewhere in the middle of the code for mute (here https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/JitsiLocalTrack.js#L216 before executing the then clause). The result is that we are not detecting that the video track is muted and we are adding the stream to the PeerConnection. After that we are stoping the stream and the state of this track is totally messed up.
This was caused by the fact that stopping of the stream and removing it from JitsiLocalTrack object was in the then clause. Now it is executed before the context is switched to the session initiate code.
I think I reviewed all other …
> fix(start_muted): Fixes start muted feature

- modules/RTC/JitsiLocalTrack.js
- Adds logging to callstats and analytics
- Waiting for 3s after muted event before reporting camera problem. If unmute event is received in this period of time the problem won't be reported.
> Improve camera/mic issue detection

- modules/RTC/JitsiLocalTrack.js
- modules/RTC/adapter.screenshare.js
This PR fixes some of the issues related to the Temasys plugin support. But not all of them are fixed yet. Requires https://github.com/jitsi/jitsi-meet-torture/pull/51
> Fix temasys plugin support

- JitsiConference.js
- modules/xmpp/ChatRoom.js
Fixes required for the page reload overlay PR in jitsi-meet
> Page reload overlay

- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SDP.js
'ssltcp' type of ICE candidates is TCP as well
> Remove 'ssltcp' candidates when 'webrtcIceTcpDisable' = true

- JitsiConference.js
- modules/xmpp/JingleSession.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/JingleSessionState.js
- modules/xmpp/strophe.jingle.js
Minor cleanup around Jingle session state handling + a change that will make SSRC updates being sent regardless of the current ICE state.
> Jingle and SSRC updates

- modules/connectivity/ConnectionQuality.js
This is only temporary, since we suspect that the calculation for the
receive direction is incorrect.
> fix: Use only packet loss for the send direction.

- JitsiConferenceEventManager.js
- JitsiConferenceEvents.js
- JitsiMeetJS.js
- doc/API.md
- modules/statistics/statistics.js
- service/statistics/Events.js
Required for https://github.com/jitsi/jitsi-meet/pull/1158
> Log collector

- JitsiConnectionErrors.js
- modules/xmpp/strophe.util.js
- modules/xmpp/xmpp.js
- package.json
New error type allows to identify when the connection failed, because of server errors.
> Add SERVER_ERROR to JitsiConnectionErrors

- modules/RTC/RTCUtils.js
PC constrain via configuration.
> feat: Allows to disable the suspend video

- modules/RTC/RTCBrowserType.js
- modules/connectivity/ConnectionQuality.js
RTCBrowserType.supportsSimulcast(). Add TODOs.
> fix: Use the same logic as sdp-simulcast in

- modules/xmpp/moderator.js
The option got axed, there is nothing to handle now.
> cleanup: remove code handling simulcast mode

- JitsiConferenceEventManager.js
- JitsiMediaDevices.js
- JitsiMeetJS.js
- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiTrack.js
- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
- modules/connectivity/ParticipantConnectionStatus.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSession.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.jingle.js
- service/RTC/MediaType.js
Converts MediaType, JingleSession and JingleSessionPC to ES6 syntax.
> Convert to es6

- .eslintrc.js
- JitsiConference.js
- doc/example/example.js
- modules/RTC/RTCUtils.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/xmpp.js
https://github.com/jitsi/lib-jitsi-meet/pull/395
> Add ESLint rules

- modules/RTC/TraceablePeerConnection.js
Temasys plugin does not allow to bind PeerConnection's methods.
> fix(TPC): 'bind' is undefined

- JitsiConferenceEventManager.js
- doc/API.md
Ignores start audio/video muted requests received by jicofo.
> Introduces new config ignoreStartMuted

- JitsiConference.js
Do not pass whole JingleSessionPC, but only the tracks to be added/removed.
> ref(JitsiConference): modify add/remove tracks

- JitsiConference.js
- modules/xmpp/JingleSessionPC.js
Get rid of 'delayedIceCandidates' buffer.
> Delayed ice candidates

- modules/RTC/TraceablePeerConnection.js
Renames '_applyLocalSSRCMap' and improves description to remove
confusion with SSRC manipulation.
> ref(JingleSessionPC): rename + improve docs

- modules/RTC/RTC.js
If it's set before the data channel is open, save it and send it as soon as the
data channel is open.
> lastn: allow setting the last N value early

- modules/RTC/JitsiLocalTrack.js
If the platform supports it, it calls MediaStreamTrack._switchCamera in order to
switch the camera facing mode at a low level. It's currently only implemented
for React Native.
> feat(JitsiLocalTrack): add _switchCamera function

- .eslintignore
- JitsiConference.js
- JitsiConferenceEventManager.js
- modules/RTC/TraceablePeerConnection.js
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
The goal here is to have both JVB and P2P connection reported to CallStats.
Please check each commit msg for more info.
> Report P2P to  CallStats

- JitsiConference.js
- modules/xmpp/JingleSessionPC.js
> Fixes for P2P analytics

- JitsiConference.js
- modules/xmpp/JingleSessionPC.js
See commits msgs for more info
> Fixes crash

- modules/connectivity/ParticipantConnectionStatus.js
Splits the participant connection status detection logic into two
separate flows one for P2P and one for JVB.
Fixes problem where user outside of last N would be reported as INACTIVE
when in P2P mode.
Added some improvements to the detection logic by adding more priority
for the video tracks frozen detection (if supported) over the last N.
When the browser supports this detection and it's playing video we
should not check the last N, because it's less reliable.
> fix(ParticipantConnectionStatus): p2p and lastN

- modules/RTC/TraceablePeerConnection.js
Ensures that the simulcast ssrc-group appears after any other
ssrc-groups in the SDP so that simulcast is properly activated.
> fix: Ensures simulcast is activated in the browser.

- JitsiConferenceEventManager.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTC.js
- modules/RTC/TraceablePeerConnection.js
- modules/statistics/RTPStatsCollector.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SignalingLayerImpl.js
- service/RTC/SignalingLayer.js
Converts all the places where SSRCs where stored as string to use numbers.
> Store SSRCs as numbers

- modules/RTC/RTC.js
Do the same which was done for the selected endpoint. That is if an endpoint is pinned, before data channels are available then the value should be cached and sent as soon as they are opened.
> Cache and send pinned endpoint

- modules/RTC/TraceablePeerConnection.js
> Remove overridden assignment in TraceablePeerConnection.js (fixes #471)

- JitsiConference.js
- modules/P2PDominantSpeakerDetection.js
- modules/TalkMutedDetection.js
Makes speaker stats to work in p2p mode.
> P2P dominant speaker

- doc/API.md
How to get the id Participate local.
> Get local user ID

- JitsiConference.js
- modules/RTC/DataChannels.js
- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/JingleSession.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.jingle.js
Extract fixes from https://github.com/jitsi/lib-jitsi-meet/pull/460 discovered while working on P2P for react-native. These commits are not directly related to p2p+react-native and can be useful in other cases.
> Misc session fixes

- modules/RTC/RTCBrowserType.js
- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SDPDiffer.js
Requires https://github.com/oney/react-native-webrtc/pull/261 and new release
> P2P react native (work in progress)

- JitsiConference.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/xmpp.js
Also add a preferH264 option for P2P.
> feat(p2p): refactor p2p configuration options

- modules/statistics/AvgRTPStatsReporter.js
- modules/statistics/RTPStatsCollector.js
This commit changes the way the average stats are being reported to the
analytics backend. Instead of prefixes for the different scenarios
("p2p_", "jvb121_" and no prefix for multi-party calls) we now have
properties that allow to distinguish which scenario an event pertains
to. The query language of the analytics backend can be used to build
appropriate queries that group by those properties.
Additionally, we now report whether the average stats event concerns a
relayed call (a call that's routed via a TURN server) or not.
> ref: Refactors average statistics reporting.

- JitsiConference.js
requires https://github.com/jitsi/jitsi-meet/pull/1750 and https://github.com/jitsi/jitsi-meet-torture/pull/89
> Fix when P2P disabled in config

- modules/RTC/JitsiLocalTrack.js
- modules/RTC/RTCUtils.js
- modules/RTC/ScreenObtainer.js
Compatibility for the latest remote control version.
> Remote control

- doc/tokens.md
> documentation updates to reflect changes to the token modules in jitsi-meet

- modules/RTC/RTCBrowserType.js
- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SDP.js
depends on https://github.com/jitsi/jitsi/pull/372
https://github.com/jitsi/jicofo/pull/206
> Unified plan simulcast signaling

- JitsiTrackError.js
- JitsiTrackErrors.js
- modules/RTC/ScreenObtainer.js
required for https://github.com/jitsi/jitsi-meet/pull/1775
> Start screen sharing

- JitsiMeetJS.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTCUtils.js
Required for https://github.com/jitsi/jitsi-meet/pull/1819
> Start with audio/video muted

- modules/RTC/RTCUtils.js
'echoCancellation' should be disabled by 'disableAEC'
'disableAP' should disable all options
> fix: audio processing options

- modules/xmpp/ChatRoom.js
In case there was a status message and later that message is removed from the presence, fire an event so the UI can also clear it.
> Fire status message update when there is no status message.

- modules/RTC/ScreenObtainer.js
- modules/xmpp/recording.js
- package.json
- webpack.config.js
https://github.com/jitsi/jitsi-meet/pull/1972
> Webpack with scope hoisting

- JitsiConferenceEventManager.js
- modules/RTC/JitsiLocalTrack.js
This PR should fix the issue with the false "Unable to access your microphone" error dialogs.
> fix(JitsiLocalTrack): Microphone not working detection.

- .flowconfig
- package.json
Required for https://github.com/jitsi/jitsi-meet/pull/2105
> Upgrade flow to 0.53.0

- JitsiConference.js
- JitsiConferenceEventManager.js
- JitsiConferenceEvents.js
- modules/videosipgw/JitsiVideoSIPGWSession.js
- modules/videosipgw/VideoSIPGW.js
- modules/videosipgw/VideoSIPGWConstants.js
- service/xmpp/XMPPEvents.js
Fixes events delivering, and adds a new event to JitsiConferenceEvents.
Adds new errors returned.
> VideoSIPGW updates

- modules/statistics/CallStats.js
In case backend was initialized before creating our Callstats instance, we skip calling the callstats method addNewFabric.
> Fixes an issue where we skip calling callstats addNewFabric.

- JitsiConnectionErrors.js
- doc/API.md
Also, updatee the documentation section on connection errors.
> feat(JitsiConnectionErrors): remove unused constant

- modules/RTC/RTCBrowserType.js
This is not ready to be merged yet as it's untested.
> feat: Enables simulcast on the mobile app.

- doc/tokens.md
Added descriptions for user identifying information in JWT tokens
Added better descriptions of prosody configuration settings when accepting JWT tokens
> Better documentation for incoming JWT token schema

- modules/xmpp/xmpp.js
Otherwise, if we never connected, we won't know.
> feat(xmpp): emit connection error when we give up

- JitsiConference.js
- JitsiConferenceEventManager.js
- JitsiConferenceEvents.js
- JitsiConnection.js
- JitsiMeetJS.js
- JitsiTrackEvents.js
- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTCUtils.js
- modules/statistics/AnalyticsAdapter.js
- modules/statistics/AvgRTPStatsReporter.js
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.emuc.js
- modules/xmpp/strophe.jingle.js
- service/statistics/AnalyticsEvents.js
Please don't merge this yet (pending an associated PR in jitsi-meet).
> Analytics refactoring

- JitsiConnection.js
- JitsiConnectionEvents.js
- modules/xmpp/strophe.ping.js
- modules/xmpp/xmpp.js
- package-lock.json
- package.json
- service/statistics/AnalyticsEvents.js
Adds suspend and shard_changed details.
> Adds new parameter details for the connection failed event.

- modules/RTC/RTCUtils.js
- modules/RTC/RTCUtils.spec.js
- modules/browser/BrowserCapabilities.js
Even though I walk through the valley of the shadow of death
I will fear no evil... Reduce indenting and repeated calls to
getting desktop streams by creating a promise chain.
> ref(gum): try to reduce complexity of obtainAudioAndVideoPermissions

- modules/RTC/ScreenObtainer.js
- package-lock.json
- package.json
depends on https://github.com/jitsi/js-utils/pull/4
> ref(SS_FF): Revert desktopSharingFirefoxMaxVersionExtRequired conversion

- JitsiConference.js
- JitsiConferenceEvents.js
- modules/statistics/RTPStatsCollector.js
Required for:
https://github.com/jitsi/jitsi-meet-torture/pull/167
> Hybrid tests

- JitsiConference.js
Passes correct option for custom script to callstats load function.
> Fixes custom script param

- .flowconfig
- package-lock.json
- package.json
https://github.com/jitsi/jitsi-meet/pull/3016
> Upgrade NPM dependencies/packages: react-native 0.55

- modules/browser/BrowserCapabilities.js
PRs for the backend work (Android / iOS) https://github.com/jitsi/react-native-webrtc/pull/17
> feat(RTC): enable remote mute/unmute event support for React Native

- doc/example/example.js
`localTracks[i].stop();`
As localTracks doesn't have stop function , coz of this line getting error and user was not able to left the room or unload 
So changed it to :
`localTracks[i].dispose();`
> Line no 194 : localTracks[i].stop(); to dispose();

- modules/RTC/BandwidthLimiter.js
- modules/RTC/BridgeChannel.js
- modules/RTC/RTC.js
- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/JingleSessionPC.js
- service/RTC/RTCEvents.js
Handle a updates from the bridge about whether or not the endpoint is selected by anyone else, so that it may suspend its higher layers if they are not in use.
Once this is ready, let me merge it so I can clean up the commit messages.
> Layer suspension

- modules/xmpp/JingleSessionPC.js
the docs denote this behavior, but it appears to have been removed at
some point
> return a promise from JingleSessionPC#replaceTrack

- modules/RTC/RTCUtils.js
- modules/browser/BrowserCapabilities.js
- Don't use it on supported browsers
- Make sure no stray timers are left
> feat(RTC): refactor logic for polling for device changes

- modules/RTC/RTCUtils.js
Chrome fires devicechange twice. This causes the DEVICE_LIST_CHANGED
event to fire twice. The listener in jitsi-meet has async logic
to handle the event, including creation of new tracks. So it
can happen that two devicechange events fire, the jitsi-meet
listener fires twice, creates duplicate tracks, and uses both
tracks. Diffing the device list for an actual change is a workaround
against extra devicechange events.
Note: this does not solve the issue in jitsi-meet of it not
handling quick successive DEVICE_LIST_CHANGED events.
> fix(device-list): workaround for devicechange being fired twice

- modules/RTC/TraceablePeerConnection.js
Until M69 Chrome used to consistently emit "onstreamadded" when
audio/video stream is added for the first time and then emit track
events only if the stream is modified afterwards (video track replaced).
However it looks like now it can first emit "onstreamadded" and then
additional "ontrackadded" for the MediaStreamTrack that was already
included in the MediaStream signalled by the "onstremadded" event. I
have not managed to figure out what is causing this and the only
difference in the SDP is the fact that the remote peer (JVB) includes
IPv6 candidates. Anyway it doesn't hurt to have such a safeguard.
> fix(TPC): ignore "ontrackadded" for existing track

- modules/RTC/RTC.js
- modules/browser/BrowserCapabilities.js
It's supported in Chrome >= 65.
> feat(RTC): use sdpSemantics to stay on Plan B for now

- JitsiConference.js
- JitsiConferenceEventManager.js
- modules/statistics/SpeakerStats.js
- modules/statistics/SpeakerStats.spec.js
- modules/statistics/SpeakerStatsCollector.js
- modules/statistics/statistics.js
- modules/xmpp/Caps.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/strophe.ping.js
- modules/xmpp/xmpp.js
- service/xmpp/XMPPEvents.js
When the main domain advertises component with type 'speakerstats' every participant will send message to the component with the name of the room where this happen.
> Adds server-side speaker stats handling.

- JitsiConferenceEventManager.js
- modules/RTC/BridgeChannel.js
- modules/xmpp/JingleSessionPC.js
- service/xmpp/XMPPEvents.js
Depends on https://github.com/jitsi/jitsi-videobridge/pull/723
> Fix conference migration

- modules/RTC/RTCUtils.js
This feature is intended for spot. Spot can have an
HDMI -> usb adapter hooked up to it. In that case,
attempting to screenshare should use that adapter
as a screensharing source.
> feat(screenshare): use camera as a screenshare source

- JitsiConference.js
- modules/connectivity/IceFailedNotification.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/xmpp.js
Works with https://github.com/jitsi/jicofo/pull/340
> Ice failed notification

- modules/DTMF/JitsiDTMFManager.js
> The missing module.exports for JitsiDTMFManager was added

- modules/xmpp/ChatRoom.js
- modules/xmpp/moderator.js
Adds a flag which can be used to disable talking to Jicofo. It's intended to be used only in jitsi-meet-spot which joins a special room.
> feat(ChatRoom): add 'disableFocus' option

- modules/RTC/RTCUtils.js
A camera source can be used as a screenshare source.
Normally for screenshare resolution is not capped and
the same will be true for the fake screenshare source.
> fix(screenshare): do not limit resolution for fake screenshare

- JitsiTrackError.js
- JitsiTrackErrors.js
- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiTrack.js
- modules/RTC/RTC.js
- service/statistics/AnalyticsEvents.js
Depends on https://github.com/jitsi/jitsi-meet/pull/4323
> Refactoring no data from source logic

- modules/xmpp/Caps.js
[fix this issue](https://github.com/jitsi/lib-jitsi-meet/issues/924)
> fix(caps): fix generateSha

- JitsiMeetJS.js
- modules/RTC/JitsiLocalTrack.js
- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
> Add video background blur

- modules/RTC/RTCUtils.js
If it's good enough for Google Meet it's good enough for us :-)
> ref(RTC): set googScreencastMinBitrate to 100

- JitsiConference.js
Removing the moderator role check in P2P start to apply the "all moderators" logic everytime.
This fix avoid Duplicated P2P “session-initiate” when the 2 pears start the P2P call
and allow P2P call without moderator.
> Remove isModerator logic from P2P call start 

- modules/xmpp/xmpp.js
Move time since last success error detail to the _getConnectionFailedReasonDetails method and use it on all connection failed events.
> ref(xmpp): move time since last success to the helper method

- modules/RTC/JitsiRemoteTrack.js
- modules/connectivity/ParticipantConnectionStatus.js
This PR refactors 592f72a63c3fd57fc9473a16fa4deaeeeb4f7928. It adds
the video type in the event and it also does a better job at managing
and properly cleaning up the state map.
> Refactors the "connection status duration" analytics event.

- package-lock.json
- package.json
This update fixes an issue with screen-sharing (described in detail here https://github.com/jitsi/sdp-simulcast/commit/987d153c04242888fa4a39f775b6b417afbb1e0f).
> Updates @jitsi/sdp-simulcast.

- JitsiConferenceEventManager.js
- modules/recording/JibriSession.js
- modules/recording/RecordingManager.js
- modules/recording/recordingXMLUtils.js
Depends on https://github.com/jitsi/jicofo/pull/393
> Extracts the jid that start/stopped a jibri session.

- package-lock.json
- package.json
Depends on https://github.com/jitsi/jitsi-meet-logger/pull/6
> Log timestamp

- doc/API.md
- add documentation for setEffect as per customer request.
https://github.com/jitsi/lib-jitsi-meet/issues/464
> doc: add documentation for setEffect method on JitsiTrack

- JitsiConferenceEventManager.js
- modules/xmpp/strophe.jingle.js
- modules/xmpp/xmpp.js
...it make it easier to process the logs in automated way.
> fix: use consistent log format for TIME prints

- modules/util/Listenable.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/XmppConnection.js
- modules/xmpp/strophe.emuc.js
- modules/xmpp/strophe.jingle.js
- modules/xmpp/strophe.ping.js
- modules/xmpp/strophe.rayo.js
- modules/xmpp/strophe.util.js
- modules/xmpp/xmpp.js
- package-lock.json
- package.json
Please check on each commit msg for more details.
I'm going to fill any missing JS docs in the XmppConnection once the changes are approved.
> XMPP resume

- package-lock.json
- package.json
...connection dropped with an error.
> deps: update strophejs-plugin-stream-management to fix crash on BOSH

- README.md
describing linting, unit tests and precommit hooks
(yes, i'm a boring :older_man:)
> readme: improve developer documentation

- JitsiConference.js
This is not the complete fix, but a stopgap.
> hips: fix handling senders / receivers when in P2P mode

- modules/e2ee/E2EEContext.js
no longer required as of Chrome 84.0.4108.0 and has been merged into M83 as well.
> e2ee: remove encodedFrameType workaround

- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
Make sure we don't have a=simulcast lines on the sendonly m-lines in the remote description
> fix(firefox): Fix simulcast on FF ESR

- doc/e2ee.md
fixing some minor issues and updating the description of the behaviour
when there are decoding errors
> e2ee: update docs

- doc/e2ee.md
- modules/e2ee/E2EEContext.js
- modules/e2ee/Worker.js
Moveѕ e2ee operations to a worker that is included as text/blob for now
to simplify deployment.
> e2ee: move to a worker

- modules/settings/Settings.js
- package-lock.json
- package.json
Depends on https://github.com/jitsi/js-utils/pull/31
> fix(localStorage): Use JitsiLocalStorage.

- modules/e2ee/E2EEContext.js
> Updated E2EEContext Documentation

- modules/xmpp/SDP.js
and make the code use arrow functions with named parameters in .each()/.map.
> sdp: remove some jquery usage

- JitsiConference.js
- modules/e2ee/E2EEContext.js
- modules/e2ee/Worker.js
currently unused, will allow moving to per-participant keys
> e2ee: use per-participant crypto contexts

- modules/xmpp/strophe.jingle.js
Improve traffic loadbalancing when using multiple turnservers
https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/pc/ice_server_parsing.cc#299
> Shuffle ICEServers for loadbalancing

- modules/e2ee/Worker.js
as suggested during the community call recently
> e2ee: make it easier to change the AES key length

- modules/xmpp/SDP.js
> sdp: check dtls namespace

- modules/statistics/LocalStatsCollector.js
- modules/statistics/RTPStatsCollector.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/SDP.js
This has become obsolete thanks to ES6 arrow functions
> chore: remove usage of `self`

- modules/RTC/TraceablePeerConnection.js
In preparation for turning on RTX on Firefox: add only the primary ssrcs to the SIM group if FID groups are present.
Also get rid of comments that are not relevant anymore, we now make sure that the ssrcs are in the correct order of quality (high to low) on Firefox.
> fix(simulcast): Add only the primary ssrcs to SIM group on FF

- modules/browser/BrowserCapabilities.js
- modules/e2ee/E2EEContext.js
- modules/e2ee/Worker.js
which landed in
https://bugs.chromium.org/p/chromium/issues/detail?id=1069295#c4
> e2ee: update for latest spec changes in Chrome M84

- JitsiConference.js
- modules/xmpp/ChatRoom.js
There were few unnecessary calls of removeFromPresence which I removed and updated the doc of addToPresence which mentions that is already doing the removeFromPresence part.
> fix: Skips sending an extra presence on join.

- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
Remove unused code in removeTrack, we always use replaceTrack in unified plan.
> fix(safari): fixes an exception that is caused by adding a null stream to pc

- package-lock.json
- package.json
https://github.com/jitsi/sdp-interop/commit/7a63ac1bfae8f1440bc2b043162186a208cbedda
> chore(deps): Update sdp-interop

- modules/xmpp/SDP.spec.js
to test the mapping of fmtp lines which are not key=value pairs
> test: add telephone-event fmtp line to test case

- modules/RTC/JitsiTrack.js
When screensharing is stopped on FF from the sharing indicator (available in FF nightly), we are currently not detecting it.
Firefox fires a track 'ended' event as opposed to Chrome which fires a mediastream 'inactive' event as well.
> fix(media): Add 'ended' event handler on MediaStreamTrack for FF

- modules/xmpp/SDP.js
not used elsewhere. Also the common term for this is munging
these days.
> sdp: remove mangle() function

- modules/xmpp/SDP.js
mostly removing the 'tmp' variable. Renaming 'media' to 'sdp'
in some places.
> sdp: refactor things a bit more and give names to things

- JitsiConference.js
- modules/RTC/RTC.js
- modules/xmpp/xmpp.js
This is useful for testing insertable streams related issues.
> e2ee: add flag to disable the E2EE support 

- README.md
i use node version 10 and npm version 5.6.0，The following dislocation occurred
```
ERROR in ./node_modules/_js-utils@0.0.0@js-utils/avatar/index.js 15:52
Module parse failed: Unexpected token (15:52)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
I don't know why TS syntax is JS file？
[update rename index.js to index.ts](https://github.com/jitsi/js-utils/pull/36)
i install node 8.11.3 version The error disappeared
I think it is necessary to add a node version to the novice
> Update README.md Resolve installation failure

- modules/RTC/TraceablePeerConnection.js
It's not yet supported, so assume success.
> tpc: fix setSenderVideoConstraint on mobile

- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
- modules/qualitycontrol/QualityController.js
- modules/xmpp/JingleSessionPC.js
config.js videoQuality settings
======================
```
videoQuality: {
maxBitratesVideo: {
low: 200000,
standard: 500000,
high: 1500000
}
}
```
> feat: Apply max bitrates on video sender

- modules/RTC/TraceablePeerConnection.js
When the video sender constraint changes in the p2p case when the remote user switches between stage/tile view,
get a downsampled video of the original 720p stream instead of requesting the camera for a new stream with the lower resolution.
Fixes https://github.com/jitsi/jitsi-meet/issues/7267
> fix(video-quality): Get downsampled video for p2p case

- modules/xmpp/MockClasses.js
- modules/xmpp/ResumeTask.js
- modules/xmpp/ResumeTask.spec.js
- modules/xmpp/XmppConnection.js
- modules/xmpp/strophe.ping.js
- modules/xmpp/xmpp.js
Few optimizations around XMPP WebSocket connection recovery. After this PR the XMPP WebSockets can be enabled on mobile.
> XMPP WebSocket optimizations

- modules/e2ee/E2EEContext.js
see https://bugs.chromium.org/p/chromium/issues/detail?id=1119653
We'll probably do similar renaming in the future.
> e2ee: update for latest chrome changes

- modules/e2ee/Worker.js
refactor the signature checking to make it clear when we need to ratchet.
This is similar to
https://tools.ietf.org/html/draft-omara-sframe-00#section-4.3.5.1
but we verify the hash before attempting to decrypt.
> e2ee: refactor to make it clear when to ratchet

- JitsiMeetJS.js
- doc/API.md
- modules/settings/Settings.js
- package-lock.json
- package.json
Depends on https://github.com/jitsi/js-utils/pull/40
> feat(external-storage): Support.

- modules/e2ee/Worker.js
this needs to be called with an Uint8Array, not an ArrayBuffer
> e2ee: fix authentication tag check

- modules/e2ee/E2EEncryption.js
- modules/e2ee/Worker.js
- modules/e2ee/crypto-utils.js
- modules/e2ee/utils.js
in particular this allows sharing the ratcheting between the E2EEncryption
module and the Worker.
> e2ee: refactor and clean up

- modules/RTC/ScreenObtainer.js
relates to https://github.com/jitsi/lib-jitsi-meet/issues/1055#issuecomment-621227217
@jallamsetty1
> feat(RTC): force cursor of ScreenObtainer to be always captured

- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
On Safari, MediaStream.onremovetrack is not fired when a remote desciption with a removed MSID is applied. As a result, new remote tracks for the same endpoint are not created causing issues where the video is not updated on Safari.
This is a Safari bug which can also be seen on http://w3c-test.org/webrtc/RTCTrackEvent-fire.html, where the test "Applying a remote description with removed msid should trigger firing a removetrack event on the corresponding stream" fails.
Also, make sure local tracks on TPC are updated when devices are changed while the user is in muted state. Though there is no MediaStream attached to the JitsiLocalTrack when the device is muted, we need to update the tracks on TPC so that they can be unmuted.
> fix(safari): Remove old remote tracks when a new track is received for an endpoint

- modules/RTC/JitsiTrack.js
When using getSynchornizationSources on the audio receiver to gather audio levels for remote tracks, browser reports last known audio levels even when the remote user is audio muted, we need to reset the value to zero here so that the audio levels are cleared.
> fix(audio-levels): Reset audio level to 0 when remote user is muted.

- doc/API.md
- modules/xmpp/strophe.jingle.js
- modules/xmpp/xmpp.js
Always attempt to discover the configured STUN/TURN servers.
> feat(xmpp) drop the useStunTurn option

- modules/e2ee/Context.spec.js
and make them a bit more concise. No functional changes
> e2ee: clean up tests

- modules/e2ee/Context.js
> e2ee: rename constants to upper-case

- README.md
- doc/API.md
> Add missing options to docs and improve naming

- doc/e2ee.md
- modules/e2ee/Context.js
- modules/e2ee/Context.spec.js
- modules/e2ee/E2EEContext.js
- modules/e2ee/E2EEncryption.js
- modules/e2ee/Worker.js
Signs and verifies frames. For testing purposes this is done on every frame.
This is not the long-term goal and there needs to be a better strategy.
> (feat) e2ee: sign and verify frames

- JitsiMediaDevices.js
- modules/RTC/RTCUtils.js
- modules/browser/BrowserCapabilities.js
> Bump minimum supported Chromium version to 72.

- modules/RTC/TPCUtils.js
Fixes https://github.com/jitsi/jitsi-meet/issues/8094.
> fix(TPC): do not update encodings for simulcast desktop tracks.

- modules/RTC/RTC.js
- modules/xmpp/JingleSessionPC.js
Helps turn relay specific testing.
> feat: Add option to force pc to use turn relay candidates.

- modules/xmpp/strophe.ping.js
Now stores the time of the raw input when ping is received. Before this change we were storing the Date.now and comparing to _getTimeSinceLastServerResponse and we needed small adjustment of values as it may lead to no pings sent.
> fix: Updates ping logic around detecting xmpp activity.

- modules/RTC/TPCUtils.js
Explicitly check if all the encodings report the same scaleResolutionDownBy value before trying to ensure they match the expected values. This makes Chrome VP9 work again.
Chrome VP9 was broken since we were trying to set a scaleResolutionDownBy of '4' on the first encoding which works for VP8 but VP9 SVC works differently, the browser dynamically adjusts the RTP stream associated with the first ssrc based on the encodings configuration so the first encoding should never be scaled down.
> fix: Implement the encodings workaround only on Safari.

- doc/API.md
I see we have an option to use replace track in conference level which its missing in this API. thanks
> Add replace track to doc

- modules/xmpp/XmppConnection.js
We were discussing this with @aaronkvanmeerten offline to minimize the time detecting split brains.
> feat: Changes ws default keepalive interval.

- modules/xmpp/xmpp.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1668028 is fixed now.
Fixes https://github.com/jitsi/lib-jitsi-meet/issues/1446
> fix(RTX): Re-enable RTX on Firefox.

- doc/API.md
A little addition to the API docs that is missing and can be useful to some
> Added useTurnUdp option to API documentation

- modules/xmpp/strophe.jingle.js
This uses the commit from https://github.com/jitsi/lib-jitsi-meet/pull/1458 and fixes the problems to make the commit mergeable :)
> feat: Support the urn:xmpp:extdisco:2 namespace specified by XEP-0215

- modules/RTC/RTCUtils.js
RTCUtils.enumerateDevices was being called earlier than the RTCUtils.init which assigned that function
> fix(RTC) fix device selection not being available

- package-lock.json
- package.json
Fix Safari RTCSessionDescription.sdp readonly
Based on https://bugs.chromium.org/p/chromium/issues/detail?id=1186456&
> Update webrtc-adapter v7.7.1 (fix Safari)

- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
Stop using the legacy pc constraints that are no longer wired up to WebRTC.
> ref(RTC): remove legacy pc constraints.

- JitsiConference.js
- modules/xmpp/ChatRoom.js
This PR provide a way to enter reason to kick participant.
> Add reason to kick participant function

- modules/RTC/CodecSelection.js
RTCRtpReceiver.getCapabilities could be undefined on some platforms
> Test RTCRtpReceiver.getCapabilities before using

- modules/xmpp/ChatRoom.js
It was removed by https://github.com/jitsi/lib-jitsi-meet/pull/1512.
> fix: Adds back removed method used by jibri.

- modules/RTC/TraceablePeerConnection.js
- modules/connectivity/ConnectionQuality.js
Calculate the target bps based on the video quality settings and the codec configured on the peerconnection.
> fix(connection-quality): Calculate target bps based on videoQuality settings.

- modules/RTC/TraceablePeerConnection.js
- modules/statistics/RTPStatsCollector.js
Get rid of the browser specific keys and use the standard spec-compliant fields for stats.
Get the resolution/fps for remote streams from 'inbound-rtp' stats. Use the 'track' stats for the local resolution/fps since these take the active simulcast streams into account.
> fix(stats): Use promise-based getStats on all browsers.

- modules/xmpp/strophe.jingle.js
- modules/xmpp/xmpp.js
Drops the custom type breaking xmpp protocol.
> fix: Drops the sys message handler after used or connected.

- modules/qualitycontrol/ReceiveVideoController.js
Fixes the case where the old format height constraint is sent on join for a jvb media session.
> fix(quality-control): Send the new constraint on join.

- modules/xmpp/xmpp.js
> Fix: sysMessageHandler not deleted

- package-lock.json
- package.json
Older chrome versions like M72 do not support Promise.allSettled.
> Add dependency for promise.allSettled.

- modules/RTC/RTC.js
- modules/qualitycontrol/ReceiveVideoController.js
Do not send old format constraints if no constraints are set before the channel is initialized.
> fix(quality-control): fix constraints sent on channel initialization.

- modules/xmpp/JingleSessionPC.js
Fixes https://github.com/jitsi/docker-jitsi-meet/issues/1048
> fix(RTC): Disable simulcast for SS when using H.264.

- modules/RTC/RTC.js
- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
- modules/browser/BrowserCapabilities.js
- modules/sdp/LocalSdpMunger.spec.js
- modules/xmpp/JingleSessionPC.js
This can be controlled through the config.js  option 'enableUnifiedOnChrome'.
The 'signalingstatechange' event for 'stable' is fired after the 'iceconnectionstatechange' event for 'completed' is fired on chrome in Unified plan. This prevents the client from switching the media connection to the p2p connection once the ice connection for p2p gets established.
> Enable unified plan support for chromium based browsers.

- modules/RTC/TraceablePeerConnection.js
https://github.com/jitsi/lib-jitsi-meet/issues/1624
> fix(Sdp): Fix maxaveragebitrate typo

- JitsiConference.js
- modules/xmpp/JingleSessionPC.js
Disable cross browser p2p using unified plan until all the issues are fixed.
> fix(JingleSessionPC): Disable unified-plan for p2p.

- modules/RTC/TraceablePeerConnection.js
Browsers do not generate a 'msid' attribute for ssrcs in unified plan mode, use mediaType as a key for the TrackSSRCInfo map.
> fix(TPC): fix local resolution/fps stats.

- modules/RTC/TraceablePeerConnection.js
Use 'msid' for plan-b clients and 'cname' for unified-plan clients.
> fix(TPC): Filter ssrcs differently while extracting the SSRC map from SDP.

- modules/RTC/RTCUtils.js
When the resolution option was being used, all the other constraints like frameRate and facing mode were being overwritten.
> fix(RTC): Do not overwrite other constraints when resolution option is used.

- JitsiConference.js
- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
- modules/RTC/ScreenObtainer.js
- modules/RTC/TraceablePeerConnection.js
Provide a method for changing the capture fps for desktop tracks during the call. These changes to the lib are needed for making it configurable from the UI.
> feat(RTC): Add the ability to change desktop share fps.

- modules/browser/BrowserCapabilities.js
This causes the audio to not work.
> fix(VAD): Do not enable VAD on Chrome on iOS.

- modules/RTC/TraceablePeerConnection.js
Munge 3 ssrcs in the SDP for chrome in unified plan always for the simulcast case.
> fix(TPC): Fix the screenshare issue when user starts video muted on chrome

- modules/RTC/RTC.js
- modules/browser/BrowserCapabilities.js
- modules/e2ee/E2EEContext.js
- modules/e2ee/Worker.js
- modules/e2ee/utils.js
remove legacy APIs which are not even supported anymore
> e2ee: remove legacy apis

- modules/RTC/TraceablePeerConnection.js
- modules/proxyconnection/ProxyConnectionPC.js
See each individual commit message for details.
> Fix Spot wireless screen sharing feature

- doc/tokens.md
- modules/RTC/RTC.js
I just merged several PRs into one and resolved conflict between them and master to make the merge into master much easier.
Included PRs:
- https://github.com/jitsi/lib-jitsi-meet/pull/1019
- https://github.com/jitsi/lib-jitsi-meet/pull/1060
- https://github.com/jitsi/lib-jitsi-meet/pull/1461
- https://github.com/jitsi/lib-jitsi-meet/pull/1502
- https://github.com/jitsi/lib-jitsi-meet/pull/1662
> Combined fixes

- JitsiConference.js
- modules/statistics/CallStats.js
- modules/statistics/statistics.js
> feat: enable config callstats configParams

- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTC.js
- modules/RTC/TraceablePeerConnection.js
- modules/proxyconnection/ProxyConnectionPC.js
- modules/proxyconnection/ProxyConnectionService.js
- modules/xmpp/JingleSession.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/strophe.jingle.js
Please look at the individual commits for more information.
> Rename iceConfig to pcConfig and other logging enhancements

- modules/xmpp/JingleSessionPC.js
This fixes https://github.com/jitsi/lib-jitsi-meet/issues/1759.
> fix(layer-suspension) Do not ignore maxHeight=0 sender constraint.

- modules/RTC/JitsiLocalTrack.js
Add timestamp to all tracks, and display surface to screen sharing tracks
> fix(tracks) Add metadata to jitsi tracks

- JitsiConference.js
- modules/RTC/BridgeChannel.js
- modules/RTC/RTC.js
Sends the source name to video type mapping to the jvb in a new bridge channel message.
> feat: SourceVideoTypeMessage message

- JitsiConference.js
- JitsiConferenceEvents.js
- modules/connectivity/ConnectionQuality.js
- modules/statistics/SpeakerStats.js
- modules/statistics/SpeakerStatsCollector.js
- modules/statistics/statistics.js
- modules/xmpp/xmpp.js
Receives facial expressions and their duration via xmpp or data channel then it stores them in speaker stats
> feat: add facial-expressions in speaker stats

- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/SignalingLayerImpl.js
- service/RTC/SignalingLayer.js
DRAFT pull request.  Changes have yet to be reviewed, validated and tested.
> Save track source name to JitsiRemoteTrack

- modules/RTC/JitsiLocalTrack.js
Broken with previous commit 579a49.
> fix: Fixes call to _setTrackMuteStatus.

- modules/xmpp/ChatRoom.js
This needs a backend update. https://github.com/jitsi/jitsi-meet/pull/10673
> fix: Reads lobby jid from correct location in the error.

- modules/RTC/TraceablePeerConnection.js
sLD is called immediately after createOffer/createAnswer, therefore the desc provided by createOffer/createAnswer can be directly passed to sLD without the need for converting it to unified plan format. This also fixes a warning seen on the browser console that says 'The description does not look like plan-b'.
> ref(TPC) Remove an unnecessary toUnified sdp conversion.

- modules/RTC/TraceablePeerConnection.js
This fixes a regression introduced by the previous commit.
> fix(TPC): Implode the simulcast group only after toUnifiedPlan conversion.

- modules/RTC/TraceablePeerConnection.js
This PR adds monitoring and logging of the DTLS transport object.
> feat(RTC): added DTLS transport monitoring

- modules/proxyconnection/ProxyConnectionPC.js
Regression introduced in
https://github.com/jitsi/lib-jitsi-meet/commit/5c9b90511120ae42660176afc0715f8c8886ef68
> fix(ProxyConnection) set signaling layer

- JitsiParticipant.js
- modules/xmpp/ChatRoom.js
- types/auto/JitsiParticipant.d.ts
- types/auto/modules/xmpp/ChatRoom.d.ts
When hiddenFromRecorder is enable in config we check the presence for the flag (the jwt identity part).
> feat: Adds a property to JitsiParticipant is hidden from recorder.

- package-lock.json
- package.json
They create installation problems on systems without an SSH key.
Ref: https://github.com/npm/cli/issues/2610#issuecomment-914610832
> chore(deps) make sure no SSH URLs get generated in package-lock.json

- modules/RTC/RTCUtils.js
> fix(rtc) reject getUserMedia with JitsiTrackError

- modules/RTC/JitsiRemoteTrack.js
- modules/connectivity/IceFailedHandling.js
Fixes issue #1476 - Alternative to PR #1487
> Fixes exceptions which occur after leaving the conference

- modules/RTC/TPCUtils.js
This fixes an issue where replaceTrack fails when a muted track is being replaced with another track in Unified plan.
> fix(TPCUtils): Check for the track mute state before looking up the tranceiver

- modules/RTC/TraceablePeerConnection.js
- modules/xmpp/SignalingLayerImpl.js
- modules/xmpp/SignalingLayerImpl.spec.js
- service/RTC/SignalingEvents.spec.ts
- service/RTC/SignalingEvents.ts
- types/auto/modules/RTC/TraceablePeerConnection.d.ts
- types/auto/service/RTC/SignalingEvents.d.ts
Handle presence updates for multiple sources per remote endpoint.
> fix(multi-stream) Handle source-name based presence updates.

- JitsiConference.js
When a screenshare track is removed in the legacy mode, presence needs to be sent with the muted state and videoType so the remote gets updated.
> fix(presence): send presence update when a local track is removed.

- JitsiConferenceEventManager.js
Discovered it during investigation of
https://github.com/jitsi/jicofo/issues/905
> fix: Cleanups chat room on destroy.

- modules/RTC/TraceablePeerConnection.js
- modules/flags/FeatureFlags.js
- types/auto/modules/RTC/TraceablePeerConnection.d.ts
- types/auto/modules/flags/FeatureFlags.d.ts
Enables lite mode which disables any media decoding.
> feat: Adds a flag runInLiteMode useful for testing.

- modules/xmpp/xmpp.js
> feat: Handles release number coming from backend.

- modules/RTC/JitsiTrack.js
- types/auto/modules/RTC/JitsiRemoteTrack.d.ts
- types/auto/modules/RTC/JitsiTrack.d.ts
This reverts commit 7d3f13c9071524dc80b1d52693fe3b49c70d51cf.
This change was not needed.
> Revert "fix(RTC): Add function declaration to JitsiTrack."

- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
- types/auto/modules/RTC/RTCUtils.d.ts
They have been deprecated and their valued can no longer be changed from
the default after M103.
https://groups.google.com/u/0/g/discuss-webrtc/c/2l7jWgreYpw?pli=1
> feat(RTC) drop no longer supported PC media constraints

- modules/xmpp/xmpp.js
https://github.com/jitsi/lib-jitsi-meet/blob/59665767bffcb460bc3c4e1d869de5210fbd6c3d/modules/xmpp/xmpp.js#L462   this is where it would crash before
> fix(deployment-info) Prevent error when setting shard and region

- doc/tokens.md
Specifying the 'signature_algorithm' within the docs on how to customise the algorithm type.
https://github.com/jitsi/jitsi-meet/blob/769f0a845233bc17c835f1dbcaf36e71339f963c/resources/prosody-plugins/token/util.lib.lua#L36
> Added docs on how to define tokens

- types/hand-crafted/modules/RTC/RTCUtils.d.ts
related to 59665767bffcb460bc3c4e1d869de5210fbd6c3d
> fix(types) remove setSuspendVideo declaration

- doc/tokens.md
see https://community.jitsi.org/t/lib-jitsi-meet-jwt-support-with-websockets/79806
> Improve documentation that jwt works on websocket

- modules/xmpp/SignalingLayerImpl.js
This fixes the broken wireless screensharing issue on spot clients.
> fix(SignalingLayer): Skip checking for last presence if the client doesn't join muc.

- modules/e2ee/Context.spec.js
- modules/e2ee/crypto-utils.js
- types/auto/modules/e2ee/crypto-utils.d.ts
> E2EE: Refactor JSDoc and Context test

- JitsiParticipant.js
The identities are coming from the presence and all values there are string.
> fix: Fixes boolean/string comparison.

- modules/RTC/TraceablePeerConnection.js
- modules/sdp/SDPSimulcast.spec.js
It gets resolved during translation.
Fixes: https://github.com/jitsi/lib-jitsi-meet/issues/2055
> fix(ts) don't set file extension for TS files

- modules/qualitycontrol/SendVideoController.js
- types/auto/modules/qualitycontrol/SendVideoController.d.ts
Small thing I noticed that should not be there.
> ref(qualitycontrol) fix doc comment

- modules/connectivity/ParticipantConnectionStatus.js
- modules/sdp/SDP.js
- modules/statistics/AudioOutputProblemDetector.js
- types/auto/modules/connectivity/ParticipantConnectionStatus.d.ts
- types/auto/modules/sdp/SDP.d.ts
- types/auto/modules/statistics/AudioOutputProblemDetector.d.ts
Some cosmetic things I noticed.
> fix: typos and jsdoc

- types/hand-crafted/modules/RTC/RTC.d.ts
related to bb8d901648140caaca405f0f5c36ee3a1eedeede
> ref(ts) update RTCUtils hand-crafted types

- service/xmpp/XMPPEvents.ts
- types/auto/service/xmpp/XMPPEvents.d.ts
Some namings which were changed by the typescript conversion.
> fix(chore) xmpp constants jsdoc

- types/hand-crafted/JitsiMeetJS.d.ts
- types/hand-crafted/JitsiTrackErrors.d.ts
- types/hand-crafted/authenticateAndUpgradeRole.d.ts
- types/hand-crafted/modules/RTC/JitsiTrack.d.ts
- types/hand-crafted/modules/RTC/TraceablePeerConnection.d.ts
- types/hand-crafted/service/statistics/AnalyticsEvents.d.ts
Remove containsTrack method that has been removed by an earlier commit, and apply some types updates.
> fix(types) update hand-crafted types

- service/RTC/SignalingLayer.js
- types/auto/service/RTC/SignalingLayer.d.ts
Related to 6d8060a4c6a09f40c6a582de851f9751eb00a41e
> fix(SignalingLayer) add sourceName argument to getPeerMediaInfo

- modules/proxyconnection/ProxyConnectionPC.js
These have become necessary with the introduction of multi-stream.
> fix(ProxyConnection) add more necessary stubs

- JitsiConference.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/xmpp.js
- types/auto/JitsiConference.d.ts
- types/auto/modules/xmpp/ChatRoom.d.ts
- types/auto/modules/xmpp/xmpp.d.ts
This PR is part of a feature which allows moderators to end the conference for all participants.
> feat(JitsiConference) added end conference

- JitsiConference.js
- karma.conf.js
- modules/sdp/SDP.js
- modules/xmpp/Caps.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/JingleHelperFunctions.js
- modules/xmpp/JingleSessionPC.js
- modules/xmpp/JingleSessionPC.spec.js
- modules/xmpp/moderator.js
- modules/xmpp/strophe.emuc.js
- modules/xmpp/strophe.jingle.js
- modules/xmpp/strophe.rayo.js
- modules/xmpp/xmpp.js
- package-lock.json
- package.json
- webpack-shared-config.js
Avoid needing an external dependency.
> feat(build) embed jquery slim

- JitsiMeetJS.ts
- modules/RTC/RTC.js
- modules/connectivity/NetworkInfo.js
- modules/flags/FeatureFlags.js
- modules/util/AuthUtil.js
This appeases the typescript compiler and there is no need to ignore anymore the error on obtainAudioAndVideoPermissions call.
> fix(ts) update jsdoc to appease typescript

- modules/RTC/JitsiLocalTrack.js
Fixes https://github.com/jitsi/jitsi-meet/issues/12319.
> fix(RTC) Update sourceType on desktop track for web.

- modules/RTC/TraceablePeerConnection.js
- modules/qualitycontrol/SendVideoController.js
- modules/xmpp/JingleSessionPC.js
Please look at individual commits for description.
> Fix codec negotiation and other multi-stream issues

- modules/RTC/TraceablePeerConnection.js
Replaces #1442
See discussion at: https://github.com/jitsi/lib-jitsi-meet/pull/1442/files
> Fix of case when findLine returns false

- modules/statistics/RTPStatsCollector.js
> Fixup codec stats

- modules/RTC/TraceablePeerConnection.js
- modules/statistics/SpeakerStats.js
- modules/xmpp/RoomMetadata.ts
Some things I've noticed that could be better.
> fix(chore) typos and jsdoc

- doc/tokens.md
improve the current `JWT token authentication Prosody plugin` documentation with all information we gathered over the last weeks while implementing token authentication with a shared secret.
> Improve 'JSON Web Token (JWT) authentication Prosody plugin' documentation

- modules/RTC/TraceablePeerConnection.js
If both `disabledCodec` and `preferredCodec` are set, browsers (Chrome) that support VP9 are sending VP8 video streams initially and then VP9 after another user joins. The new user that joins sends VP8 until another user joins, so on and so forth. 
```
config.p2p = { enabled: false }
config.videoQuality.disabledCodec = 'H264'
config.videoQuality.preferredCodec = 'VP9'
```
- Join a conference from 2 different Chrome tabs
- chrome://webrtc-internals/ shows inbound and outbound streams as VP8 for both participants (VP9 is expected)
- Have a 3rd users join the conference from another Chrome tab
- chrome://webrtc-internals/ shows first two participants sending VP9, newly join participant sending VP8
- In `CodecSelection.js` there are 3 events that triggers a change in preferred codec, …
> fix: allow disabling and setting preferred codec

- JitsiConferenceEventManager.js
- JitsiConferenceEvents.spec.ts
- JitsiConferenceEvents.ts
- modules/RTC/BridgeChannel.js
- service/RTC/RTCEvents.spec.ts
- service/RTC/RTCEvents.ts
It's emitted when remotely closed / failed.
> feat(JitsiConference,BridgeChannel) emit event when channel is closed

- JitsiConference.js
- JitsiConferenceEvents.spec.ts
- JitsiConferenceEvents.ts
- modules/connectivity/ConnectionQuality.js
- modules/statistics/SpeakerStats.js
- modules/statistics/SpeakerStatsCollector.js
- modules/xmpp/xmpp.js
Can be tested at: https://gborlea.jitsi.net/
> feat(face-landmarks): add face landmarks timeline

- modules/RTC/BridgeChannel.js
That's a graceful close by the bridge.
> fix(BridgeChannel) skip close notification if the code is 1001

- modules/xmpp/JingleSessionPC.js
Always initiate a sRD->cA->sLD cycle since renegotiation fails in the following scenario. 
In a p2p call when channelLastN=0, the direction on the video tranceiver is set to'inactive'. 
At this point, if the user unmutes, the track is replaced on the video sender. 
If a cO->sLD->sRD is triggered, the browser adds a third m-line which isn't expected and possibly is a bug. All renegotiations triggered after this fail as a result. However, the browser does not add a third m-line in the answer it generates and renegotiation succeeds.
> fix(p2p) Fix an issue where unmute fails on p2p with channelLastN=0.

- modules/RTC/TraceablePeerConnection.js
Made updating video sender parameters in sequential manner in order to solve race condition when transaction id (which is generated during getParameters) can be reset at the end of videoSender setParameters https://chromium.googlesource.com/external/webrtc/+/master/pc/rtp_sender.cc#340 and cause exception if another update was already in fly and before its check for transaction id presence.
The issue is not consistent, but I was able to reproduce it when e.g. in chrome browser for some time you are starting/stopping screen-share with choosing different options like full screen, browser tab or desktop application. 
Also after the change  I run npm run test/lint
> fix(RTCRtpSender) Race condition on resetting transaction id.

- JitsiConferenceEventManager.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/moderator.js
For messages coming from visitors, which are not in the current room we need to supply a display name.
> feat(visitors): Visitors chat.

- package-lock.json
- package.json
https://github.com/jitsi/strophejs-plugin-stream-management/commit/b42f961f141fdf9380d73080c9e6bb23c9c57272
> fix: Fixes reconnects with ws stream management plugin.

- modules/xmpp/moderator.js
Any jibri recording. streaming or sip jibri will join the main room.
> feat: Jibri will ignore redirects for visitors.

- modules/e2ee/ManagedKeyHandler.js
- types/hand-crafted/modules/e2ee/OlmAdapter.d.ts
s/updateCurrentKey/updateCurrentMediaKey/g
> fix(e2ee) call correct function to update key

- modules/xmpp/JingleSessionPC.js
Check for source updates and notify the peer of any new sources after every renegotiation cycle. This fixes issues where source changes are not detected if any other task that requires a renegotiation is scheduled between replaceTrack and a negotiationneeded event.
> fix(JingleSession): Check for source updates after every reneg

- service/RTC/CodecMimeType.js
- service/RTC/CodecMimeType.spec.ts
Removes unused import by previous commit.
> ref(test) remove unused import

- modules/util/AsyncQueue.js
- package-lock.json
- package.json
It's the same as async, but with ESM which is more bundle friendly.
> fix(AsyncQueue) use async-es

- modules/xmpp/JingleSessionPC.js
Fixes an issue when a screenshare doesn't show up on remote endpoints after one of the endpoints in the call does an ICE RESTART using session-terminate while it has 2 video sources.
If there are 2 video sources in the source-remove sent by Jicofo, only the second m-line was getting rejected before.
> fix(JingleSession): Reject all m-lines associated with sources in source-remove

- modules/watchRTC/WatchRTC.ts
with respect to https://github.com/jitsi/lib-jitsi-meet/pull/2311 on LJM and https://github.com/jitsi/jitsi-meet/pull/13527 on JM,
removing error log based on https://github.com/jitsi/jitsi-meet/pull/13527#issuecomment-1644644945
> remove error log for watchrtc

- authenticateAndUpgradeRole.js
This fixes changes from https://github.com/jitsi/lib-jitsi-meet/commit/1b5830f1bdc11a51aa1f475f68ebe12c12722e2f
> fix: Fixes using correct reference in authenticateAndUpgradeRole.

- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiTrack.js
- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
test at https://gabi.jitsi.net
> fix: getting right resolution for mobile web

- modules/xmpp/xmpp.js
> 4 years seems like ample time :-)
> feat(xmpp) remove support for the deprecated options.bosh

- modules/RTC/ScreenObtainer.js
This prevents 0Hz mode from kicking in on Chromium-Windows endpoints. 0Hz supposedly introduces end-to-end latency for desktop tracks.
> fix(ScreenObtainer) Apply min fps after a successful gDM call.

- modules/xmpp/ChatRoom.js
> feat: Retries joining the room on room creation error.

- package-lock.json
- package.json
Apply changes fixing https://github.com/jitsi/rtcstats/issues/32
> chore(deps): bump rtcstats from 9.6.0 to 9.7.0

- JitsiConference.js
Since there is nothing to do, pretend it all went well.
> fix(JitsiConference) don't fail hangup() if room wasn't created yet

- JitsiParticipant.js
- authenticateAndUpgradeRole.js
- modules/RTC/JitsiLocalTrack.js
- modules/connectivity/TrackStreamingStatus.ts
- modules/recording/JibriSession.js
- modules/statistics/AudioOutputProblemDetector.js
- modules/xmpp/Caps.js
- modules/xmpp/XmppConnection.js
- modules/xmpp/strophe.ping.js
Need to modify these types to get lib-jitsi-meet working in a typescript project.
Some of the types were not compatible, removed some references to hand-crafted from one of the files, as the auto types cannot find them.
> fix(types): fix last few types

- modules/connectivity/ConnectionQuality.js
- modules/statistics/RTPStatsCollector.js
Remove unused layers and width properties from kSimulcastFormats. Improve calculatePacketLoss function.  Avoid using string as keys in literal object creation syntax.
> #2387 Micro code improvements.

- modules/xmpp/xmpp.js
It is no longer supported by Jicofo.
> fix(xmpp): Do not advertise lip-sync support.

- modules/util/Listenable.js
- modules/xmpp/ChatRoom.js
- modules/xmpp/Lobby.js
- service/xmpp/XMPPEvents.ts
Waits to check if lobby is already enabled, and if enabled ignore the request.
> feat: Waits for the room dataform to be received before setting lobby.

- JitsiConference.js
> feat(JitsiConference): invalid name.

- modules/RTC/JitsiTrack.js
Fixes https://github.com/jitsi/jitsi-meet/issues/14386
> fix(JitsiTrack): Detect track ended event on Safari.

- modules/RTC/TPCUtils.js
- modules/RTC/TraceablePeerConnection.js
Check if all the relevant fields are correctly configured instead of checking for just the encode resolution on the local video sender.
> ref(TPC): Add extra checks before updating RTCRtpEncodingParameters.

- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/JitsiTrack.js
It will now happen for both local and remote tracks.
> feat(JitsiTrack) always detach the track for any elements when disposing

- package-lock.json
- package.json
It's not imported, so it wasn't being bundled.
> fix(deps) drop unused promise.allsettled dependency

- modules/xmpp/ResumeTask.spec.js
The number of retries is limited to 3 now.
> fix(xmppConnection) Fix unit tests.

- modules/RTC/RTC.js
- modules/qualitycontrol/ReceiveVideoController.js
Fixes a regression for JitsiConference::setReceiverVideoConstraint and JitsiConference::setAssumedBandwidthBps.
> fix(quality) Sends updated receiver constraints.

- modules/sdp/SDP.js
Fixes a regression introduced by https://github.com/jitsi/lib-jitsi-meet/commit/a7476b126c89e1ccce9a2ed6e8e2f656d8dce978 where multiple source-adds are sent from Firefox client resulting in Jicofo force muting the sources.
> fix(JingleSession) Do not signal recvonly SSRCs generated by Firefox.

- .github/workflows/stale.yml
> fix(ci) migrate stalebot to GHA

- modules/connectivity/NetworkInfo.ts
> Migrated `connectivity/NetworkInfo`

- modules/event/Jvb121EventGenerator.ts
> Migrate `event/Jvb121EventGenerator`

- modules/RTC/BridgeChannel.ts
**Migrated the `modules/RTC/BridgeChannel` from js to ts **
> Migrated `modules/RTC/BridgeChannel.ts`

- modules/e2eping/e2eping.ts
> Migrated  `e2eping/e2eping`

- modules/e2eping/e2eping.ts
> fix(e2eping) fix linting error

- JitsiTrackError.ts
> Migrated `./JitsiTrackError`

- globals.d.ts
- modules/litemode/LiteModeContext.ts
Fixes : #2637 
The previous PR #2661 had multiple conflicting changes and unnecessary commits, which made it difficult to track the actual updates. To ensure a clean and structured contribution, I decided to close the previous PR and open this one with a refined approach.
> Migrate `LiteModeContext`

- modules/e2ee/SAS.ts
> Migrating `modules/e2ee/SAS`

- CONTRIBUTING.md
have Taken refernce from the contributing of jitsi-meet and also added forum link in this contributing.md
Fixes: #2704
> Added Contributing

- modules/detection/VADReportingService.ts
> Migrating `modules/detection/VADReportingService`

- modules/detection/VADTalkMutedDetection.ts
> Migrating `modules/detection/VADTalkMutedDetection`

- modules/statistics/SpeakerStats.ts
> Migrated `./modules/statistics/SpeakerStats`

- modules/util/AsyncQueue.ts
> Migrated `./modules/util/AsyncQueue`

- modules/util/EventEmitter.ts
> Migrated `./modules/util/EventEmitter`

- modules/util/MathUtil.ts
> Migrated `./modules/util/Mathutil`

- modules/util/ScriptUtil.ts
> Migrated `./modules/util/ScriptUtil`

- modules/util/StringUtils.ts
> Migrated `./modules/utils/StringUtils`

- modules/util/TestUtils.ts
> Migrated `./modules/utils/TestUtils`

- modules/e2ee/utils.ts
> Migrate `./modules/e2ee/utilis`

- modules/detection/P2PDominantSpeakerDetection.ts
> Migrate `./modules/detection/P2PDominantSpeakerDetection`

- modules/settings/Settings.js
- modules/util/UsernameGenerator.ts
> Migrate `./modules/utils/UsernameGenerator`

- modules/xmpp/JingleHelperFunctions.ts
> Migrating `modules/xmpp/JingleHelperFunctions`

- modules/xmpp/ConnectionPlugin.ts
> Migrating `modules/xmpp/ConnectionPlugin`

- modules/xmpp/AVModeration.ts
> migrated `modules/xmpp/AVModeration`

- modules/xmpp/strophe.rayo.ts
> Migrating `modules/xmpp/strophe.rayo`

- .github/workflows/ci.yml
- .github/workflows/deploy-docs.yml
- .gitignore
- package-lock.json
- package.json
- tsconfig.json
The end goal is to fix our types to make typedoc generated docs as useful as possible.
The generated docs will be published to GH pages on every push.
Sample:
> feat(ts) add typedoc

- modules/xmpp/StropheLastSuccess.ts
> Migrating `modules/xmpp/StropheLastSuccess`

- modules/recording/JibriSession.ts
> Migrating  /modules/recording/JibriSession

- modules/xmpp/strophe.util.ts
> Migrating `modules/xmpp/strophe.util`

- modules/xmpp/strophe.logger.ts
> Migrating `modules/xmpp/strophe.logger`

- modules/xmpp/MockClasses.ts
> Migrate `modules/xmpp/MockClasses`

- JitsiConference.js
- modules/RTC/JitsiLocalTrack.js
- modules/RTC/JitsiRemoteTrack.js
- modules/RTC/RTCUtils.js
- modules/RTC/TraceablePeerConnection.js
- modules/qualitycontrol/QualityController.ts
- modules/statistics/AvgRTPStatsReporter.js
- modules/statistics/RTPStatsCollector.js
- modules/util/MathUtil.ts
- service/RTC/SignalingLayer.ts
- It can throw exceptions
- It doesn't return false on things which are not Number, just on things that are not NaN
Fixes: https://github.com/jitsi/lib-jitsi-meet/issues/2743
> chore(*) fix use of isNaN

- package.json
> fix(pkg) fix typedoc build

- JitsiConferenceEventManager.js
- JitsiConferenceEvents.spec.ts
- JitsiConferenceEvents.ts
- modules/RTC/BridgeChannel.ts
- modules/connectivity/ConnectionQuality.js
- service/RTC/RTCEvents.spec.ts
- service/RTC/RTCEvents.ts
feat(connection-quality) Process BWE stat received on bridge channel.
Bridge will be sending the BWE stat on the bridge channel as a "ConnectionStats" so that the client can display it under connection quality stats.
> feat(connection-quality) Process BWE stat received on bridge channel.

- JitsiConference.js
- JitsiMeetJS.ts
- modules/RTCStats/RTCStats.ts
Technically anyone can use it as long as they provide connection options, but we don't need any of that for JaaS.
> feat(jaas) add simple zero-config mechanism for JaaS users

- JitsiMediaDevices.js
- modules/RTC/RTC.js
- modules/RTC/RTCUtils.js
- modules/RTC/ScreenObtainer.js
- types/hand-crafted/JitsiMediaDevices.d.ts
- types/hand-crafted/JitsiMeetJS.d.ts
- types/hand-crafted/modules/RTC/RTC.d.ts
- types/hand-crafted/modules/RTC/RTCUtils.d.ts
See each individual commit for details.
> Cleanup some init processes

- modules/statistics/SpeakerStats.ts
- modules/statistics/SpeakerStatsCollector.ts
> Migrate `modules\statistics\SpeakerStatsCollector.ts`

- JitsiConferenceEventManager.js
> Updated JitsiConferenceEventManager to ES6 Class

- modules/videosipgw/VideoSIPGW.ts
> migrated `modules\videosipgw\VideoSIPGW.js`

- JitsiConference.js
- JitsiConferenceEventManager.js
> feat: Disable p2p when transcribing is enabled.

- JitsiConference.js
- modules/statistics/statistics.js
> Update `statistics/statistics` to ES6 Class 

- .eslintrc.js
- JitsiConnection.ts
- modules/RTCStats/RTCStats.ts
- modules/browser/BrowserCapabilities.ts
- modules/util/AsyncQueue.ts
- modules/util/Deferred.ts
- modules/videosipgw/JitsiVideoSIPGWSession.ts
- modules/xmpp/MockClasses.ts
- modules/xmpp/ResumeTask.ts
- package-lock.json
- package.json
- tsconfig.json
> feat(lint, ts) Add member-ordering rule for TS

- modules/qualitycontrol/ReceiveVideoController.ts
> Migrate `modules\qualitycontrol\ReceiveVideoController.ts`

- modules/detection/VADAudioAnalyser.ts
> Migrate `modules\detection\VADAudioAnalyser.ts`

- JitsiConference.ts
- modules/RTC/BridgeChannel.ts
- modules/RTC/RTC.js
- modules/qualitycontrol/QualityController.ts
- modules/qualitycontrol/ReceiveAudioController.ts
- service/RTC/ReceiverAudioSubscription.ts
JVB support for this was added here - https://github.com/jitsi/jitsi-videobridge/commit/6fc76e46bb109f14ceea785a3fcd306323bc2c80
> feat(AudioController) Adds support for subscribing to audio sources.

- JitsiConference.ts
- authenticateAndUpgradeRole.js
Reverts jitsi/lib-jitsi-meet#2853
> Revert "Migrate `authenticateAndUpgradeRole.ts`"

- JitsiConference.ts
- JitsiMeetJS.ts
- modules/connectivity/ConnectionQuality.ts
- modules/connectivity/TrackStreamingStatus.ts
- modules/recording/JibriSession.ts
- modules/recording/RecordingManager.ts
- modules/statistics/AvgRTPStatsReporter.ts
- modules/statistics/SpeakerStatsCollector.ts
- modules/version/ComponentsVersions.ts
- modules/xmpp/ChatRoom.ts
- modules/xmpp/ConnectionPlugin.ts
- modules/xmpp/strophe.emuc.ts
Fix types of `any` and remove old @ts-ignore
> fix(type) add proper types instead of `any`

- JitsiConference.ts
- karma.conf.js
- modules/proxyconnection/ProxyConnectionPC.js
- modules/proxyconnection/ProxyConnectionService.js
- modules/sdp/SDP.spec.ts
- modules/sdp/SDP.ts
- modules/util/XMLParser.ts
- modules/util/XMLUtils.ts
- modules/xmpp/Caps.ts
- modules/xmpp/ChatRoom.spec.ts
- modules/xmpp/ChatRoom.ts
- modules/xmpp/JingleHelperFunctions.ts
- modules/xmpp/JingleSessionPC.spec.ts
- modules/xmpp/JingleSessionPC.ts
- modules/xmpp/moderator.js
- modules/xmpp/strophe.emuc.ts
- modules/xmpp/strophe.jingle.js
- modules/xmpp/strophe.rayo.ts
- modules/xmpp/xmpp.ts
- package-lock.json
- package.json
- webpack-shared-config.js
> ref(jquery): Remove
